# Generated by Django 5.2.17 on 2026-09-15 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0175_alter_paymentdocument_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable payment batch identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.PositiveBigIntegerField(blank=True, db_comment='Official immutable number allocated at first submission.', null=True)),
                ('payment_mode', models.CharField(choices=[('LOAN-JAWABU', 'Loan - Jawabu'), ('CASH', 'Cash')], db_comment='Single payment route applied to the whole batch.', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Head of Rural review'), ('review_complete', 'Review complete'), ('awaiting_scan', 'Awaiting signed scan'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_comment='Current server-controlled payment batch lifecycle state.', db_index=True, default='draft', max_length=24)),
                ('revision', models.PositiveBigIntegerField(db_comment='Optimistic concurrency revision for all batch mutations.', default=1)),
                ('batch_digest', models.CharField(blank=True, db_comment='SHA-256 binding of current mode, number, membership, and case payment data.', default='', max_length=64)),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='When the official number was allocated and review began.', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_comment='When the current workbook was generated from approved cases.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_comment='When the exact signed scan was accepted and the batch locked.', null=True)),
                ('cancellation_reason', models.TextField(blank=True, db_comment='Required operational reason when an unfinished batch is cancelled.', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the payment batch was opened.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the payment batch last changed.')),
                ('completed_by', models.ForeignKey(blank=True, db_comment='Staff user whose accepted scan completed the batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, db_comment='Staff user who generated the current reviewed workbook.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_comment='Staff user who opened the batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_document', models.ForeignKey(blank=True, db_comment='Latest generated workbook for this batch revision.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='governed_payment_batches', to='core.paymentdocument')),
                ('group_configuration', models.ForeignKey(db_comment='Jawabu workflow configuration owning this batch.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='core.groupsheetconfiguration')),
                ('submitted_by', models.ForeignKey(blank=True, db_comment='Staff user who first submitted the batch for review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_batch',
                'db_table_comment': 'Authoritative editable payment batch; completed only after an exact signed scan is accepted.',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBatchCase',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable membership identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_comment='Whether this case is currently included in the batch.', db_index=True, default=True)),
                ('case_digest', models.CharField(db_comment='Current payment-data digest captured when membership or review changed.', max_length=64)),
                ('removed_reason', models.TextField(blank=True, db_comment='Required reason for the latest removal.', default='')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_comment='When this membership was first created.')),
                ('removed_at', models.DateTimeField(blank=True, db_comment='When this case was most recently removed.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When this membership last changed.')),
                ('added_by', models.ForeignKey(blank=True, db_comment='Staff user who most recently added this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(db_comment='Authoritative payment batch containing this membership history.', on_delete=django.db.models.deletion.PROTECT, related_name='case_memberships', to='payments.paymentbatch')),
                ('farmer', models.ForeignKey(db_comment='Canonical Portal case selected for payment.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_batch_memberships', to='core.jawabufarmermaster')),
                ('removed_by', models.ForeignKey(blank=True, db_comment='Staff user who most recently removed this case.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_batch_case',
                'db_table_comment': 'Current and removed case membership for an authoritative payment batch.',
            },
        ),
        migrations.CreateModel(
            name='PaymentBatchEvent',
            fields=[
                ('id', models.BigAutoField(db_comment='Immutable payment-batch event identifier.', primary_key=True, serialize=False)),
                ('action', models.CharField(db_comment='Stable machine-readable payment batch action.', max_length=40)),
                ('request_id', models.CharField(blank=True, db_comment='Idempotency request identifier; blank only for internal historical operations.', db_index=True, default='', max_length=128)),
                ('revision', models.PositiveBigIntegerField(db_comment='Batch revision produced by the action.')),
                ('metadata', models.JSONField(blank=True, db_comment='Customer-data-minimized action details needed for audit interpretation.', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When this immutable batch event was recorded.')),
                ('actor', models.ForeignKey(blank=True, db_comment='Staff user responsible for the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(db_comment='Payment batch changed by this event.', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.paymentbatch')),
            ],
            options={
                'db_table': 'payment_batch_event',
                'db_table_comment': 'Append-only customer-data-minimized history of payment batch mutations.',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCaseReview',
            fields=[
                ('id', models.BigAutoField(db_comment='Internal payment case-review identifier.', primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Awaiting review'), ('approved', 'Approved'), ('returned', 'Returned')], db_comment='Current Head of Rural decision for this case.', db_index=True, default='pending', max_length=16)),
                ('comment', models.TextField(blank=True, db_comment='Required operational review comment for an approve or return decision.', default='')),
                ('reviewed_digest', models.CharField(blank=True, db_comment='Exact case payment-data digest approved or returned by the reviewer.', default='', max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, db_comment='When the current decision was recorded.', null=True)),
                ('revision', models.PositiveBigIntegerField(db_comment='Monotonic review mutation revision.', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the review record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the review record last changed.')),
                ('membership', models.OneToOneField(db_comment='Case membership whose current values were reviewed.', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='payments.paymentbatchcase')),
                ('reviewed_by', models.ForeignKey(blank=True, db_comment='Head of Rural staff user responsible for the current decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_case_review',
                'db_table_comment': 'Durable per-case Head of Rural payment decision bound to exact case data.',
            },
        ),
        migrations.CreateModel(
            name='PaymentSequenceState',
            fields=[
                ('id', models.BigAutoField(db_comment='Internal payment-sequence state identifier.', primary_key=True, serialize=False)),
                ('next_number', models.PositiveBigIntegerField(db_comment='Next official payment number available for allocation.')),
                ('revision', models.PositiveBigIntegerField(db_comment='Optimistic concurrency revision.', default=1)),
                ('adjustment_reason', models.TextField(blank=True, db_comment='Reason for the latest manual adjustment.', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When this sequence state was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When this sequence state was last changed.')),
                ('group_configuration', models.OneToOneField(db_comment='Jawabu group governed by this payment sequence.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_sequence', to='core.groupsheetconfiguration')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='Staff user responsible for the latest sequence mutation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_sequence_state',
                'db_table_comment': 'Group-scoped allocator for official consecutive payment numbers.',
            },
        ),
        migrations.CreateModel(
            name='PaymentSequenceEvent',
            fields=[
                ('id', models.BigAutoField(db_comment='Immutable payment-sequence event identifier.', primary_key=True, serialize=False)),
                ('action', models.CharField(db_comment='Allocation or explicit administrative adjustment action.', max_length=24)),
                ('number_before', models.PositiveBigIntegerField(db_comment='Number available before this mutation.')),
                ('number_after', models.PositiveBigIntegerField(db_comment='Number available after this mutation.')),
                ('revision_after', models.PositiveBigIntegerField(db_comment='Sequence revision after this mutation.')),
                ('reason', models.TextField(db_comment='Required human-readable reason for allocation or adjustment.')),
                ('request_id', models.CharField(blank=True, db_comment='Idempotency request identifier; blank only for internal historical operations.', db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When this immutable sequence event was recorded.')),
                ('actor', models.ForeignKey(blank=True, db_comment='Staff user responsible for this mutation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, db_comment='Payment batch receiving an allocation, when applicable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sequence_events', to='payments.paymentbatch')),
                ('sequence', models.ForeignKey(db_comment='Sequence state changed by this event.', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.paymentsequencestate')),
            ],
            options={
                'db_table': 'payment_sequence_event',
                'db_table_comment': 'Immutable evidence for every payment-number allocation or adjustment.',
            },
        ),
        migrations.AddIndex(
            model_name='paymentbatch',
            index=models.Index(fields=['group_configuration', 'status'], name='payment_batch_group_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_number__isnull', False)), fields=('group_configuration', 'payment_number'), name='unique_group_payment_number'),
        ),
        migrations.AddIndex(
            model_name='paymentbatchcase',
            index=models.Index(fields=['batch', 'is_active'], name='payment_batch_case_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentbatchcase',
            constraint=models.UniqueConstraint(fields=('batch', 'farmer'), name='unique_payment_batch_case'),
        ),
        migrations.AddConstraint(
            model_name='paymentbatchevent',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('request_id',), name='unique_payment_batch_event_request'),
        ),
        migrations.AddConstraint(
            model_name='paymentsequenceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('request_id',), name='unique_payment_sequence_request'),
        ),
    ]
