# Generated by Django 5.1.6 on 2026-10-06 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def require_unique_numbers(apps, schema_editor):
    Batch = apps.get_model('payments', 'PaymentBatch')
    duplicates = Batch.objects.using(schema_editor.connection.alias).exclude(payment_number=None).values('group_configuration_id', 'payment_number').annotate(n=models.Count('pk')).filter(n__gt=1)
    if duplicates.exists():
        raise RuntimeError('Rollback blocked: payment numbers were reused. Reconcile historical display numbers before restoring the legacy unique constraint.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_jawabufarmermaster_requisition_batch_and_more'),
        ('payments', '0004_payment_receipt_batches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNumberClaim',
            fields=[
                ('id', models.BigAutoField(db_comment='Internal payment-number-slot identifier.', primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField(db_comment='Printed number, not the immutable payment identity.')),
            ],
            options={
                'db_table': 'payment_number_claim',
                'db_table_comment': 'Authoritative lifetime payment number slots; no automatic purge or historical recycling.',
            },
        ),
        migrations.RemoveConstraint(
            model_name='paymentbatch',
            name='unique_group_payment_number',
        ),
        migrations.AddField(
            model_name='paymentreceiptbatch',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_comment='Workspace hiding timestamp; source invoices remain untouched.', null=True),
        ),
        migrations.AddField(
            model_name='paymentreceiptbatch',
            name='archived_by',
            field=models.ForeignKey(blank=True, db_comment='Staff user who last archived the delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='paymentbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_number__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('group_configuration', 'payment_number'), name='unique_group_payment_number'),
        ),
        migrations.AddField(
            model_name='paymentnumberclaim',
            name='batch',
            field=models.OneToOneField(blank=True, db_comment='Current owner, null after explicit cancellation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_claim', to='payments.paymentbatch'),
        ),
        migrations.AddField(
            model_name='paymentnumberclaim',
            name='sequence',
            field=models.ForeignKey(db_comment='Locked group allocator.', on_delete=django.db.models.deletion.PROTECT, related_name='number_claims', to='payments.paymentsequencestate'),
        ),
        migrations.AddConstraint(
            model_name='paymentnumberclaim',
            constraint=models.UniqueConstraint(fields=('sequence', 'number'), name='unique_payment_number_claim'),
        ),
        migrations.RunPython(migrations.RunPython.noop, require_unique_numbers),
    ]
