# Generated by Django 5.1.6 on 2026-10-06 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_jawabufarmermaster_requisition_batch_and_more'),
        ('payments', '0006_bind_payment_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNameAgreement',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable agreement identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(db_comment='Original signed scan filename.', max_length=255)),
                ('content_type', models.CharField(db_comment='Validated PDF or image media type.', max_length=100)),
                ('file_content', models.BinaryField(db_comment='Private retained scan bytes; never a public media URL.')),
                ('checksum', models.CharField(db_comment='SHA-256 of the accepted signed scan.', max_length=64)),
                ('identity_facts', models.JSONField(db_comment='Exact case, invoice and confirmed household facts cleared by this agreement.')),
                ('accepted_by', models.CharField(db_comment='Recorded staff actor who attested the uploaded agreement.', max_length=255)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_comment='When the signed agreement was accepted.')),
                ('artifact', models.OneToOneField(db_comment='Exact sent governed letter agreed by its signatories.', on_delete=django.db.models.deletion.PROTECT, related_name='signed_agreement', to='core.invoicenamechangeletterartifact')),
            ],
            options={
                'db_table': 'payment_invoice_name_agreement',
                'db_table_comment': 'Immutable signed identity-clearance evidence; lifetime retention until owning configuration reset. No automatic purge.',
            },
        ),
    ]
