# Generated by Django 5.1.6 on 2026-09-18 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0183_complaint_voice_transcription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxCursor',
            fields=[
                ('singleton_key', models.CharField(db_comment='Stable singleton key for the dedicated statement inbox.', default='statement_inbox', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('history_id', models.CharField(blank=True, db_comment='Last completely processed Gmail history identifier.', default='', max_length=255)),
                ('last_polled_at', models.DateTimeField(blank=True, db_comment='Most recent polling attempt time.', null=True)),
                ('last_succeeded_at', models.DateTimeField(blank=True, db_comment='Most recent fully successful polling time.', null=True)),
                ('last_error_code', models.CharField(blank=True, db_comment='Privacy-safe code for the latest polling failure.', default='', max_length=80)),
                ('lease_owner', models.CharField(blank=True, db_comment='Short-lived worker identifier holding the polling lease.', default='', max_length=128)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_comment='Server time when the polling lease expires.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the cursor or worker health last changed.')),
            ],
            options={
                'db_table': 'credit_assessment_mailbox_cursor',
                'db_table_comment': 'Durable singleton cursor and worker-health evidence for the dedicated Gmail statement inbox.',
            },
        ),
        migrations.CreateModel(
            name='AnalysisPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(db_comment='Monotonic package revision.')),
                ('content_digest', models.CharField(db_comment='Canonical digest of report and question revision content.', db_index=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_comment='When the analyst froze this package.')),
                ('submitted_by', models.ForeignKey(blank=True, db_comment='Credit Analyst who submitted the package.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_assessment_analysis_package',
                'db_table_comment': 'Immutable analyst-submitted report and question-set revision.',
            },
        ),
        migrations.CreateModel(
            name='AnalysisQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(db_comment='Stable display order within the package.')),
                ('text', models.TextField(db_comment='Analyst question requiring BRO response.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When this immutable question was recorded.')),
                ('created_by', models.ForeignKey(blank=True, db_comment='Credit Analyst who raised the question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(db_comment='Frozen analysis package containing this question.', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='credit_assessments.analysispackage')),
            ],
            options={
                'db_table': 'credit_assessment_question_item',
                'db_table_comment': 'Immutable structured question raised in one frozen analysis package.',
            },
        ),
        migrations.CreateModel(
            name='AssessmentDocument',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable assessment-document version identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('pre_appraisal', 'Pre-appraisal form'), ('signed_laf', 'Signed LAF'), ('mpesa_statement', 'M-PESA statement'), ('spin_report', 'SPIN report'), ('crb_report', 'Metropol CRB report'), ('analysis_report', 'Credit analysis report')], db_comment='Governed semantic evidence type.', db_index=True, max_length=32)),
                ('version', models.PositiveIntegerField(db_comment='Monotonic version within assessment and document type.')),
                ('original_filename', models.CharField(db_comment='Sanitized staff-visible source filename.', max_length=255)),
                ('mime_type', models.CharField(db_comment='Validated MIME type.', max_length=100)),
                ('size', models.PositiveBigIntegerField(db_comment='File size in bytes.')),
                ('content_hash', models.CharField(db_comment='SHA-256 binding decisions to exact file bytes.', db_index=True, max_length=64)),
                ('drive_file_id', models.CharField(blank=True, db_comment='Restricted Google Drive file identifier; never an authorization token.', default='', max_length=255)),
                ('source_reference', models.CharField(blank=True, db_comment='Existing governed document or mailbox reference when bytes were not newly uploaded.', default='', max_length=255)),
                ('is_current', models.BooleanField(db_comment='Whether this is the active version for its semantic type.', db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When this immutable version was recorded.')),
                ('uploaded_by', models.ForeignKey(blank=True, db_comment='Staff actor who supplied this version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_assessment_document_evidence',
                'db_table_comment': 'Immutable versioned file evidence for governed credit assessments.',
            },
        ),
        migrations.AddField(
            model_name='analysispackage',
            name='analysis_document',
            field=models.ForeignKey(db_comment='Mandatory consolidated analysis report bound to this package.', on_delete=django.db.models.deletion.PROTECT, related_name='analysis_packages', to='credit_assessments.assessmentdocument'),
        ),
        migrations.CreateModel(
            name='CreditAssessment',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable credit-assessment identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Pre-appraisal draft'), ('pending_authorization', 'Awaiting Branch Manager authorization'), ('returned_pre_analysis', 'Returned for a full-year statement'), ('analysis', 'Credit analysis in progress'), ('bro_review', 'Awaiting BRO review'), ('analyst_validation', 'Awaiting analyst validation'), ('pending_decision', 'Awaiting Branch Manager decision'), ('returned_to_bro', 'Returned to BRO'), ('approved', 'Approved'), ('declined', 'Declined')], db_comment='Current server-controlled assessment lifecycle state.', db_index=True, default='draft', max_length=32)),
                ('revision', models.PositiveBigIntegerField(db_comment='Optimistic concurrency revision incremented by every accepted mutation.', default=1)),
                ('statement_period_start', models.DateField(blank=True, db_comment='Chronologically earlier date parsed from the statement filename or subject.', null=True)),
                ('statement_period_end', models.DateField(blank=True, db_comment='Chronologically later date parsed from the statement filename or subject.', null=True)),
                ('statement_full_year', models.BooleanField(blank=True, db_comment='Whether statement coverage satisfies the twelve-calendar-month policy.', null=True)),
                ('signed_laf_reference', models.CharField(blank=True, db_comment='Governed Origination reference or historical LAF evidence reference relied on for consent.', default='', max_length=255)),
                ('signed_laf_hash', models.CharField(blank=True, db_comment='SHA-256 of the exact signed LAF relied upon for consent.', default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Server time when assessment tracking began.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Server time of the latest accepted assessment mutation.')),
                ('created_by', models.ForeignKey(blank=True, db_comment='BRO who opened the assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tat_case', models.OneToOneField(db_comment='TAT case whose timing, product, branch, and operational identity govern this assessment.', on_delete=django.db.models.deletion.PROTECT, related_name='credit_assessment', to='core.tattrackercase')),
            ],
            options={
                'db_table': 'credit_assessment_case_root',
                'db_table_comment': 'Django source of truth for the governed credit-assessment lifecycle attached to one TAT case.',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField(db_comment='Versioned authenticated ciphertext; never plaintext.')),
                ('key_version', models.CharField(db_comment='Configured encryption-key version required for controlled rotation.', max_length=32)),
                ('reveal_count', models.PositiveIntegerField(db_comment='Number of authorized passcode reveals.', default=0)),
                ('last_revealed_at', models.DateTimeField(blank=True, db_comment='Most recent authorized reveal time.', null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, db_comment='When ciphertext was irreversibly removed after use.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When this protected secret record last changed.')),
                ('assessment', models.OneToOneField(db_comment='Assessment whose statement passcode is encrypted here.', on_delete=django.db.models.deletion.PROTECT, related_name='statement_secret', to='credit_assessments.creditassessment')),
            ],
            options={
                'db_table': 'credit_assessment_statement_secret',
                'db_table_comment': 'Short-lived encrypted M-PESA statement passcode; excluded from every projection and log.',
            },
        ),
        migrations.CreateModel(
            name='AssessmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_comment='Stable machine-readable action.', db_index=True, max_length=64)),
                ('revision', models.PositiveBigIntegerField(db_comment='Assessment revision produced or observed by this event.')),
                ('request_id', models.CharField(blank=True, db_comment='Idempotency key; blank only for system ingestion events.', db_index=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, db_comment='Customer-data-minimized evidence needed to interpret the event.', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the immutable event was written.')),
                ('actor', models.ForeignKey(blank=True, db_comment='Staff actor responsible for the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(db_comment='Assessment changed by this event.', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='credit_assessments.creditassessment')),
            ],
            options={
                'db_table': 'credit_assessment_audit_event',
                'db_table_comment': 'Append-only customer-data-minimized audit history for credit assessments.',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='assessmentdocument',
            name='assessment',
            field=models.ForeignKey(db_comment='Assessment owning this immutable evidence version.', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='credit_assessments.creditassessment'),
        ),
        migrations.CreateModel(
            name='AssessmentDecision',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable decision event identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate', models.CharField(choices=[('authorization', 'Analysis authorization'), ('final', 'Final decision')], db_comment='Authorization or final-decision gate.', db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('returned', 'Returned'), ('declined', 'Declined')], db_comment='Server-validated manager action.', max_length=16)),
                ('assessment_revision', models.PositiveBigIntegerField(db_comment='Exact assessment revision reviewed.')),
                ('evidence_digest', models.CharField(db_comment='Canonical hash binding the action to reviewed evidence.', max_length=64)),
                ('comment', models.TextField(blank=True, db_comment='Manager explanation; mandatory for final actions and non-approval authorization actions.', default='')),
                ('request_id', models.CharField(db_comment='Idempotency key for this immutable decision.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the decision was recorded.')),
                ('actor', models.ForeignKey(blank=True, db_comment='Branch Manager responsible for this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, db_comment='Exact analysis package reviewed for a final action.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='credit_assessments.analysispackage')),
                ('assessment', models.ForeignKey(db_comment='Assessment decided at this gate.', on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='credit_assessments.creditassessment')),
            ],
            options={
                'db_table': 'credit_assessment_manager_decision',
                'db_table_comment': 'Immutable Branch Manager action bound to exact assessment and evidence revisions.',
            },
        ),
        migrations.AddField(
            model_name='analysispackage',
            name='assessment',
            field=models.ForeignKey(db_comment='Assessment owning this frozen package revision.', on_delete=django.db.models.deletion.PROTECT, related_name='analysis_packages', to='credit_assessments.creditassessment'),
        ),
        migrations.CreateModel(
            name='EngineJob',
            fields=[
                ('id', models.UUIDField(db_comment='Future engine job identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_revision', models.PositiveBigIntegerField(db_comment='Assessment revision to which an engine result must bind.')),
                ('source_digest', models.CharField(db_comment='Digest of exact source document identifiers and hashes.', db_index=True, max_length=64)),
                ('contract_version', models.CharField(db_comment='Versioned disabled-by-default engine interface contract.', default='v1', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_comment='Future engine job state.', db_index=True, default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, db_comment='Future structured result; never authoritative without analyst review.', default=dict)),
                ('error_code', models.CharField(blank=True, db_comment='Privacy-safe future engine failure code.', default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the future engine job was requested.')),
                ('completed_at', models.DateTimeField(blank=True, db_comment='When the future engine result was accepted.', null=True)),
                ('assessment', models.ForeignKey(db_comment='Assessment whose immutable evidence would be processed.', on_delete=django.db.models.deletion.PROTECT, related_name='engine_jobs', to='credit_assessments.creditassessment')),
            ],
            options={
                'db_table': 'credit_assessment_engine_job',
                'db_table_comment': 'Dormant versioned job boundary for a future isolated extraction and report engine.',
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(db_comment='Monotonic response revision for this question.')),
                ('text', models.TextField(db_comment='BRO response text.')),
                ('responded_at', models.DateTimeField(auto_now_add=True, db_comment='When the response revision was submitted.')),
                ('question', models.ForeignKey(db_comment='Question answered by this immutable response revision.', on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='credit_assessments.analysisquestion')),
                ('responded_by', models.ForeignKey(blank=True, db_comment='BRO who submitted this response.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_assessment_question_response',
                'db_table_comment': 'Append-only BRO response revisions to analyst questions.',
            },
        ),
        migrations.CreateModel(
            name='QuestionValidationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted'), ('returned', 'Returned')], db_comment='Analyst validation result.', max_length=16)),
                ('comment', models.TextField(blank=True, db_comment='Required explanation when a response is returned.', default='')),
                ('request_id', models.CharField(db_comment='Idempotency key for this append-only validation event.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When validation was recorded.')),
                ('response', models.ForeignKey(db_comment='Exact response revision validated by the analyst.', on_delete=django.db.models.deletion.PROTECT, related_name='validation_events', to='credit_assessments.questionresponse')),
                ('validated_by', models.ForeignKey(blank=True, db_comment='Credit Analyst responsible for validation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_assessment_response_validation',
                'db_table_comment': 'Append-only analyst validation of an exact BRO response revision.',
            },
        ),
        migrations.CreateModel(
            name='StatementMailReceipt',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable mailbox-receipt identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gmail_message_id', models.CharField(db_comment='Gmail message identifier used with the attachment identifier for idempotent ingestion.', max_length=255)),
                ('gmail_attachment_id', models.CharField(db_comment='Gmail attachment identifier used with the message identifier for idempotent ingestion.', max_length=255)),
                ('gmail_thread_id', models.CharField(blank=True, db_comment='Gmail thread identifier retained for operational traceability.', default='', max_length=255)),
                ('forwarding_sender', models.EmailField(blank=True, db_comment='Normalized staff email that forwarded the statement.', db_index=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, db_comment='Forwarded subject containing only the provider supplied masked phone and period.', default='', max_length=998)),
                ('original_sent_at', models.DateTimeField(blank=True, db_comment='Original forwarded-message time when recoverable from message evidence.', null=True)),
                ('inbox_received_at', models.DateTimeField(db_comment='Trusted time the dedicated Gmail inbox received the forward.', db_index=True)),
                ('original_time_source', models.CharField(blank=True, db_comment='Evidence quality label for original_sent_at.', default='', max_length=32)),
                ('attachment_name', models.CharField(db_comment='Validated M-PESA statement filename.', max_length=255)),
                ('attachment_hash', models.CharField(db_comment='SHA-256 of the encrypted source PDF.', db_index=True, max_length=64)),
                ('attachment_size', models.PositiveBigIntegerField(db_comment='Encrypted source PDF size in bytes.')),
                ('masked_phone_pattern', models.CharField(blank=True, db_comment='Provider-supplied masked phone pattern used only for candidate matching.', default='', max_length=32)),
                ('statement_period_start', models.DateField(blank=True, db_comment='Chronologically earlier statement date parsed without opening the PDF.', null=True)),
                ('statement_period_end', models.DateField(blank=True, db_comment='Chronologically later statement date parsed without opening the PDF.', null=True)),
                ('statement_full_year', models.BooleanField(blank=True, db_comment='Whether parsed dates cover at least twelve calendar months.', null=True)),
                ('drive_file_id', models.CharField(blank=True, db_comment='Restricted Google Drive source-file identifier.', default='', max_length=255)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('linked', 'Linked'), ('ambiguous', 'Needs review'), ('ignored', 'Ignored'), ('invalid', 'Invalid')], db_comment='Current server-controlled matching state.', db_index=True, default='unclaimed', max_length=16)),
                ('error_code', models.CharField(blank=True, db_comment='Privacy-safe ingestion or validation error code.', default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When Django ingested this mailbox receipt.')),
            ],
            options={
                'db_table': 'credit_assessment_statement_receipt',
                'db_table_comment': 'Immutable Gmail receipt metadata and restricted M-PESA statement artifact pointer.',
                'indexes': [models.Index(fields=['forwarding_sender', 'status', 'inbox_received_at'], name='credit_stmt_sender_status_idx'), models.Index(fields=['masked_phone_pattern', 'status'], name='credit_stmt_phone_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('gmail_message_id', 'gmail_attachment_id'), name='unique_credit_mail_attachment')],
            },
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='statement_receipt',
            field=models.ForeignKey(blank=True, db_comment='Confirmed Gmail statement receipt linked to this case.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_assessments', to='credit_assessments.statementmailreceipt'),
        ),
        migrations.AddConstraint(
            model_name='analysisquestion',
            constraint=models.UniqueConstraint(fields=('package', 'sequence'), name='unique_credit_question_sequence'),
        ),
        migrations.AddConstraint(
            model_name='assessmentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('assessment', 'request_id'), name='unique_credit_assessment_request'),
        ),
        migrations.AddIndex(
            model_name='assessmentdocument',
            index=models.Index(fields=['assessment', 'document_type', 'is_current'], name='credit_document_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdocument',
            constraint=models.UniqueConstraint(fields=('assessment', 'document_type', 'version'), name='unique_credit_document_version'),
        ),
        migrations.AddConstraint(
            model_name='analysispackage',
            constraint=models.UniqueConstraint(fields=('assessment', 'revision'), name='unique_credit_package_revision'),
        ),
        migrations.AddConstraint(
            model_name='enginejob',
            constraint=models.UniqueConstraint(fields=('assessment', 'assessment_revision', 'source_digest'), name='unique_credit_engine_source_revision'),
        ),
        migrations.AddConstraint(
            model_name='questionresponse',
            constraint=models.UniqueConstraint(fields=('question', 'revision'), name='unique_credit_response_revision'),
        ),
        migrations.AddIndex(
            model_name='creditassessment',
            index=models.Index(fields=['state', 'updated_at'], name='credit_assessment_state_idx'),
        ),
    ]
