# Generated by Django 6.0 on 2026-04-15 12:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_message_id', models.CharField(db_index=True, max_length=255)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['telegram_message_id', 'received_at'], name='core_rawmes_telegra_cbecf6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Successfully Processed'), ('failed', 'Processing Failed'), ('partial', 'Partially Processed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_records', to='core.rawmessage')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('raw_message', models.TextField()),
                ('item', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gps_link', models.URLField(blank=True, default='', max_length=500)),
                ('image_flag', models.BooleanField(default=False)),
                ('source', models.CharField(default='whatsapp_telegram', max_length=50)),
                ('synced_to_sheets', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_records', to='core.processedmessage')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['message_id'], name='core_parsed_message_8b884d_idx'), models.Index(fields=['synced_to_sheets'], name='core_parsed_synced__23301e_idx')],
            },
        ),
    ]
