# Generated by Django 6.0 on 2026-04-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmessage',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='sync_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
