# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parsedmessage_last_sync_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedmessage',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='complaint_category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='complaint_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='complaint_status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='resolution_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='days_open',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='risk_level',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
