# Generated by Django 5.0.4 on 2026-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_multi_group_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedmessage',
            name='sheet_id',
        ),
        migrations.AlterField(
            model_name='parsedmessage',
            name='group_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='parsedmessage',
            name='source',
            field=models.CharField(default='telegram bot', max_length=50),
        ),
    ]
