# Generated by Django 5.0.4 on 2026-05-11 06:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_parsedmessage_sheet_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('telegram_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('reply_to_telegram_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('old_status', models.CharField(blank=True, default='', max_length=255)),
                ('new_status', models.CharField(blank=True, default='', max_length=255)),
                ('resolution_text', models.TextField(blank=True, default='')),
                ('risk_level', models.CharField(blank=True, default='', max_length=100)),
                ('loan_at_risk', models.CharField(blank=True, default='', max_length=100)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('raw_update_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='batch_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='source_telegram_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Original Telegram message_id before batch splitting.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='rawmessage',
            index=models.Index(fields=['source_telegram_message_id', 'received_at'], name='core_rawmes_source__9b97a3_idx'),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='parsed_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_updates', to='core.parsedmessage'),
        ),
        migrations.AddIndex(
            model_name='caseupdate',
            index=models.Index(fields=['group_id', 'created_at'], name='core_caseup_group_i_cca7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='caseupdate',
            index=models.Index(fields=['telegram_message_id'], name='core_caseup_telegra_140976_idx'),
        ),
        migrations.AddIndex(
            model_name='caseupdate',
            index=models.Index(fields=['reply_to_telegram_message_id'], name='core_caseup_reply_t_3692ab_idx'),
        ),
    ]
