# Generated by Django 5.0.4 on 2026-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_caseupdate_rawmessage_batch_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSheetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, help_text='Telegram group chat ID, for example -1001234567890.', max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, default='', help_text='Human-friendly name shown in the admin list.', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('sheet_id', models.CharField(help_text='Google spreadsheet ID for this group.', max_length=255)),
                ('sheet_name', models.CharField(default='Complaints Register', help_text='Worksheet/tab name inside the spreadsheet.', max_length=255)),
                ('sheet_schema', models.JSONField(blank=True, default=dict, help_text='Optional canonical-field to sheet-header mapping.')),
                ('workflow', models.JSONField(blank=True, default=dict, help_text='Optional status/update workflow settings for this group.')),
                ('parser_rules', models.JSONField(blank=True, default=dict, help_text='Optional parsing rules for this group.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional labels, owner notes, or deployment metadata.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group sheet configuration',
                'verbose_name_plural': 'Group sheet configurations',
                'ordering': ['group_id'],
            },
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='sheet_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Google spreadsheet ID this case was last mirrored from/to.', max_length=255),
        ),
        migrations.AddField(
            model_name='parsedmessage',
            name='sheet_name',
            field=models.CharField(blank=True, default='', help_text='Worksheet/tab name this case was last mirrored from/to.', max_length=255),
        ),
        migrations.AlterField(
            model_name='parsedmessage',
            name='message_id',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='parsedmessage',
            index=models.Index(fields=['group_id', 'sheet_id'], name='core_parsed_group_i_cefdda_idx'),
        ),
        migrations.AddConstraint(
            model_name='parsedmessage',
            constraint=models.UniqueConstraint(fields=('group_id', 'message_id'), name='unique_case_message_per_group'),
        ),
    ]
