# Generated by Django 5.0.4 on 2026-06-27 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_jawabuvisitrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcaImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('sheet_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sheet_tab', models.CharField(blank=True, default='', max_length=255)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('telegram_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_filename', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_sheet', models.CharField(blank=True, default='', max_length=255)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('customer_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('primary_phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('fca_visit_date', models.DateField(blank=True, null=True)),
                ('fca_comment', models.TextField(blank=True, default='')),
                ('fca_decision', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('review_needed', 'Review Needed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('parsed_fields', models.JSONField(blank=True, default=dict)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FCA import record',
                'verbose_name_plural': 'FCA import records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group_id', 'created_at'], name='core_fcaimp_group_i_d8eaf0_idx'), models.Index(fields=['group_id', 'source_filename', 'source_sheet', 'source_row'], name='core_fcaimp_group_i_ce993c_idx'), models.Index(fields=['primary_phone', 'customer_name'], name='core_fcaimp_primary_fa6180_idx'), models.Index(fields=['import_status', 'fca_decision'], name='core_fcaimp_import__e8fb75_idx')],
            },
        ),
    ]
