# Generated by Django 5.0.4 on 2026-07-02 05:29

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fcaimportrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabuFarmerMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, default='jawabu_farmers_csv', max_length=100)),
                ('source_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('customer_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('national_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('primary_phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('secondary_phone', models.CharField(blank=True, default='', max_length=32)),
                ('county', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('sub_county', models.CharField(blank=True, default='', max_length=128)),
                ('ward', models.CharField(blank=True, default='', max_length=128)),
                ('village', models.CharField(blank=True, default='', max_length=255)),
                ('landmark', models.TextField(blank=True, default='')),
                ('branch', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('gps_link', models.URLField(blank=True, default='', max_length=1000)),
                ('latitude', models.CharField(blank=True, default='', max_length=64)),
                ('longitude', models.CharField(blank=True, default='', max_length=64)),
                ('duplicate_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review_needed', 'Review Needed'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=32)),
                ('cleaning_notes', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jawabu farmer master record',
                'verbose_name_plural': 'Jawabu farmer master data',
                'ordering': ['customer_name', 'national_id', 'primary_phone'],
                'indexes': [models.Index(fields=['duplicate_key'], name='core_jawabu_duplica_044aac_idx'), models.Index(fields=['national_id', 'primary_phone'], name='core_jawabu_nationa_845284_idx'), models.Index(fields=['customer_name', 'county'], name='core_jawabu_custome_084448_idx'), models.Index(fields=['status', 'updated_at'], name='core_jawabu_status_7ace6e_idx'), models.Index(fields=['source', 'source_fingerprint'], name='core_jawabu_source_7213de_idx')],
            },
        ),
    ]
