# Generated by Django 5.0.4 on 2026-07-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_jawabufarmermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='actual_receipts',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='actual_receipts_currency',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='contract_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='created_date',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='hb_sales_person',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='hbg_contract_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='installation_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='lead_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='sign_date',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='jawabufarmermaster',
            index=models.Index(fields=['hbg_contract_name'], name='core_jawabu_hbg_con_e81a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='jawabufarmermaster',
            index=models.Index(fields=['hb_sales_person'], name='core_jawabu_hb_sale_3dbb1e_idx'),
        ),
    ]
