# Generated by Django 5.0.4 on 2026-07-02 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_jawabufarmermaster_actual_receipts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabuFarmerUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('telegram_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sender', models.CharField(blank=True, default='', max_length=255)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('committed', 'Committed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=32)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('review_needed', models.PositiveIntegerField(default=0)),
                ('committed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('parsed_rows', models.JSONField(blank=True, default=list)),
                ('mapping', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jawabu farmer upload batch',
                'verbose_name_plural': 'Jawabu farmer upload batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group_id', 'created_at'], name='core_jawabu_group_i_2334c8_idx'), models.Index(fields=['status', 'created_at'], name='core_jawabu_status_9cc287_idx'), models.Index(fields=['telegram_message_id'], name='core_jawabu_telegra_1d22d8_idx')],
            },
        ),
    ]
