# Generated by Django 5.0.4 on 2026-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_fcaimportrecord_fca_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='credit_decided_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the credit decision was recorded.', null=True),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='credit_decided_by',
            field=models.CharField(blank=True, default='', help_text='Telegram sender who set the credit decision.', max_length=255),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='credit_decision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('Exemption Approved', 'Exemption Approved'), ('Pending', 'Pending')], db_index=True, default='', help_text='Credit Analysis decision from master data dropdown.', max_length=80),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='jbl_officer',
            field=models.CharField(blank=True, default='', help_text='Name of the JBL BRO / field officer who conducted the visit.', max_length=255),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='jbl_visit_comment',
            field=models.TextField(blank=True, default='', help_text='Optional free-text comment from the JBL officer.'),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='jbl_visit_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date the JBL officer visited this farmer.', null=True),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='jbl_visit_status',
            field=models.CharField(blank=True, choices=[('Approved - Paid', 'Approved - Paid'), ('Approved - Pending Invoice', 'Approved - Pending Invoice'), ('Approved - Pending Minimum Deposit', 'Approved - Pending Minimum Deposit'), ('Approved - Requisition Cancelled', 'Approved - Requisition Cancelled'), ('Awaiting Analysis', 'Awaiting Analysis'), ('JBL to Schedule Visit', 'JBL to Schedule Visit'), ('Visit Pending / Reschedule', 'Visit Pending / Reschedule'), ('Deferred / On Hold', 'Deferred / On Hold'), ('Rejected by JBL', 'Rejected by JBL'), ('Cancelled', 'Cancelled'), ('Client Withdrew', 'Client Withdrew'), ('Opted for Cash', 'Opted for Cash')], db_index=True, default='', help_text='Jawabu Comment After Visit — 12-option dropdown set by JBL officer.', max_length=80),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Order No. assigned by admin after credit approval.', max_length=128),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='requisition_date',
            field=models.DateField(blank=True, help_text='Jawabu Requisition Date — only set after Credit Decision = Approved.', null=True),
        ),
        migrations.AddIndex(
            model_name='jawabufarmermaster',
            index=models.Index(fields=['jbl_visit_date'], name='core_jawabu_jbl_vis_3161c5_idx'),
        ),
        migrations.AddIndex(
            model_name='jawabufarmermaster',
            index=models.Index(fields=['credit_decision'], name='core_jawabu_credit__5f4c46_idx'),
        ),
        migrations.AddIndex(
            model_name='jawabufarmermaster',
            index=models.Index(fields=['order_number'], name='core_jawabu_order_n_c72bdf_idx'),
        ),
    ]
