# Generated by Django 5.0.4 on 2026-07-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_jawabufarmermaster_pipeline_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='JBL Requisition Form', max_length=255)),
                ('file', models.FileField(help_text='Upload the Excel (.xlsx) template here.', upload_to='requisition/')),
                ('is_active', models.BooleanField(default=True, help_text='Mark this as the active template used for generation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Requisition template',
                'verbose_name_plural': 'Requisition templates',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
