# Generated by Django 5.0.4 on 2026-07-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_requisitiontemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabufarmermaster',
            name='jbl_visit_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Awaiting Analysis', 'Awaiting Analysis'), ('JBL to Schedule Visit', 'JBL to Schedule Visit'), ('Rescheduled', 'Rescheduled'), ('Deferred / On Hold', 'Deferred / On Hold'), ('Rejected by JBL', 'Rejected by JBL'), ('Opted for Cash', 'Opted for Cash'), ('Opted for other Partner', 'Opted for other Partner')], db_index=True, default='', help_text='Jawabu Comment After Visit — 12-option dropdown set by JBL officer.', max_length=80),
        ),
    ]
