# Generated by Django 5.0.4 on 2026-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_jawabufarmermaster_balance_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='final_decided_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the final decision was recorded.', null=True),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='final_decided_by',
            field=models.CharField(blank=True, default='', help_text='Telegram sender who set the final decision.', max_length=255),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('Under Review', 'Under Review')], db_index=True, default='', help_text='Head of Rural final decision. Approved records are ready for order batching.', max_length=80),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='final_decision_comment',
            field=models.TextField(blank=True, default='', help_text='Head of Rural decision comment shown before order batching.'),
        ),
        migrations.AddIndex(
            model_name='jawabufarmermaster',
            index=models.Index(fields=['final_decision'], name='core_jawabu_final_d_c85c3c_idx'),
        ),
    ]
