# Generated by Django 5.0.4 on 2026-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_jawabufarmermaster_final_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='customer_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='IMAB customer number required before Head of Rural review.', max_length=64),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='imab_created',
            field=models.CharField(blank=True, default='', help_text='Whether the customer has been created on IMAB before Head of Rural review.', max_length=32),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='jbl_media_urls',
            field=models.TextField(blank=True, default='', help_text='Drive links for documents/images uploaded during the JBL visit stage.'),
        ),
        migrations.AddIndex(
            model_name='jawabufarmermaster',
            index=models.Index(fields=['customer_no'], name='core_jawabu_custome_60ba33_idx'),
        ),
    ]
