# Generated by Django 5.0.4 on 2026-07-10 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_jawabufarmermaster_customer_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=128, unique=True)),
                ('requisition_date', models.DateField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, default='', max_length=255)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(default='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', max_length=255)),
                ('file_content', models.BinaryField(blank=True, default=bytes)),
                ('farmer_ids', models.JSONField(blank=True, default=list)),
                ('farmer_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('invoices_uploaded', 'Invoices Uploaded'), ('partially_invoiced', 'Partially Invoiced'), ('completed', 'Completed'), ('needs_review', 'Needs Review')], db_index=True, default='generated', max_length=32)),
                ('invoice_summary', models.JSONField(blank=True, default=dict)),
                ('last_invoice_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Requisition batch',
                'verbose_name_plural': 'Requisition batches',
                'ordering': ['-requisition_date', '-updated_at'],
                'indexes': [models.Index(fields=['order_number'], name='core_requis_order_n_097497_idx'), models.Index(fields=['status', 'updated_at'], name='core_requis_status_907d25_idx')],
            },
        ),
    ]
