# Generated by Django 5.0.4 on 2026-07-10 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_requisitionbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinCreditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('sheet_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('telegram_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_message_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_chat', models.CharField(blank=True, default='', max_length=255)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_message_index', models.PositiveIntegerField(blank=True, null=True)),
                ('request_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('request_type', models.CharField(choices=[('spin', 'SPIN'), ('crb', 'CRB Report')], db_index=True, max_length=40)),
                ('customer_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('national_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('raw_id_text', models.CharField(blank=True, default='', max_length=255)),
                ('primary_phone', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('secondary_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_type', models.CharField(blank=True, default='', max_length=50)),
                ('loan_product', models.CharField(blank=True, default='', max_length=255)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tenor', models.CharField(blank=True, default='', max_length=100)),
                ('business_notes', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('raw_message', models.TextField(blank=True, default='')),
                ('parsed_fields', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('import_status', models.CharField(choices=[('imported', 'Imported'), ('review_needed', 'Review Needed'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='review_needed', max_length=30)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SPIN / CRB request',
                'verbose_name_plural': 'SPIN / CRB requests',
                'ordering': ['-request_datetime', '-created_at'],
                'indexes': [models.Index(fields=['group_id', 'request_datetime'], name='core_spincr_group_i_e351be_idx'), models.Index(fields=['group_id', 'national_id', 'primary_phone'], name='core_spincr_group_i_3654bd_idx'), models.Index(fields=['group_id', 'import_status'], name='core_spincr_group_i_0b0e81_idx'), models.Index(fields=['source_message_hash'], name='core_spincr_source__df5fb4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='spincreditrequest',
            constraint=models.UniqueConstraint(fields=('group_id', 'source_message_hash'), name='unique_spin_request_source_per_group'),
        ),
    ]

