# Generated by Django 5.0.4 on 2026-07-13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_spincreditrequest_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TatTrackerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('actor_name', models.CharField(blank=True, default='', max_length=255)),
                ('actor_telegram_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('actor_role', models.CharField(blank=True, default='', max_length=80)),
                ('stage_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('stage_label', models.CharField(blank=True, default='', max_length=160)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('mini_app', 'Mini App'), ('telegram', 'Telegram'), ('sheet_sync', 'Sheet Sync'), ('admin_correction', 'Admin Correction')], db_index=True, default='mini_app', max_length=40)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('synced_to_sheet', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TAT tracker event',
                'verbose_name_plural': 'TAT tracker events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TatTrackerCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('sheet_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('sheet_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('case_id', models.CharField(db_index=True, max_length=128)),
                ('product_key', models.CharField(db_index=True, max_length=80)),
                ('product_label', models.CharField(blank=True, default='', max_length=120)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('branch', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('bro_name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('stage_values', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected'), ('Declined', 'Declined'), ('Deferred', 'Deferred'), ('Stalled', 'Stalled'), ('Pending Docs', 'Pending Docs')], db_index=True, default='Active', max_length=40)),
                ('remarks', models.TextField(blank=True, default='')),
                ('current_stage', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_telegram_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('last_updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TAT tracker case',
                'verbose_name_plural': 'TAT tracker cases',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['group_id', 'status'], name='core_tattra_group_i_31ef1b_idx'),
                    models.Index(fields=['group_id', 'product_key', 'status'], name='core_tattra_group_i_24095f_idx'),
                    models.Index(fields=['group_id', 'client_name'], name='core_tattra_group_i_900a38_idx'),
                    models.Index(fields=['group_id', 'current_stage'], name='core_tattra_group_i_f41aa3_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='tattrackercase',
            constraint=models.UniqueConstraint(fields=('group_id', 'case_id'), name='unique_tat_case_id_per_group'),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tattrackercase'),
        ),
        migrations.AddIndex(
            model_name='tattrackerevent',
            index=models.Index(fields=['group_id', 'created_at'], name='core_tattra_group_i_96be48_idx'),
        ),
        migrations.AddIndex(
            model_name='tattrackerevent',
            index=models.Index(fields=['group_id', 'stage_key'], name='core_tattra_group_i_3edbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='tattrackerevent',
            index=models.Index(fields=['case', 'created_at'], name='core_tattra_case_id_17ad34_idx'),
        ),
    ]
