# Generated by Django 5.0.4 on 2026-07-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tattrackerevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TatTrackerStaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telegram_user_id', models.CharField(blank=True, db_index=True, default='', help_text='Numeric Telegram user ID. Preferred because usernames can change.', max_length=100)),
                ('telegram_username', models.CharField(blank=True, db_index=True, default='', help_text='Telegram username without @. Used if user ID is unavailable.', max_length=100)),
                ('roles', models.CharField(default='BRO', max_length=255)),
                ('branches', models.CharField(blank=True, default='ALL', max_length=500)),
                ('products', models.CharField(blank=True, default='ALL', max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tat_tracker_staff', to='core.groupsheetconfiguration')),
            ],
            options={
                'verbose_name': 'TAT tracker staff member',
                'verbose_name_plural': 'TAT tracker staff members',
                'ordering': ['group_configuration', 'name'],
                'indexes': [
                    models.Index(fields=['group_configuration', 'active'], name='core_tattra_group_c_c1fecc_idx'),
                    models.Index(fields=['telegram_user_id'], name='core_tattra_telegra_edcd57_idx'),
                    models.Index(fields=['telegram_username'], name='core_tattra_telegra_178c5e_idx'),
                ],
            },
        ),
    ]