# Generated by Codex on 2026-07-14
from django.db import migrations, models
from django.utils import timezone


def backfill_spin_public_sequences(apps, schema_editor):
    SpinCreditRequest = apps.get_model('core', 'SpinCreditRequest')
    SpinRequestSequence = apps.get_model('core', 'SpinRequestSequence')
    next_numbers = {}
    records = SpinCreditRequest.objects.order_by('group_id', 'request_datetime', 'created_at', 'id')
    for record in records:
        dt = record.request_datetime or record.created_at
        year = timezone.localtime(dt).year if dt and timezone.is_aware(dt) else (dt.year if dt else timezone.now().year)
        key = (record.group_id, year)
        number = next_numbers.get(key, 1)
        record.public_sequence_year = year
        record.public_sequence_number = number
        record.save(update_fields=['public_sequence_year', 'public_sequence_number'])
        next_numbers[key] = number + 1
    for (group_id, year), next_number in next_numbers.items():
        SpinRequestSequence.objects.update_or_create(
            group_id=group_id,
            year=year,
            defaults={'next_number': next_number},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tattrackercase_create_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spincreditrequest',
            name='public_sequence_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='public_sequence_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='SpinRequestSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SPIN request sequence',
                'verbose_name_plural': 'SPIN request sequences',
            },
        ),
        migrations.RunPython(backfill_spin_public_sequences, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='spincreditrequest',
            index=models.Index(fields=['group_id', 'public_sequence_year', 'public_sequence_number'], name='core_spincr_group_i_1f2945_idx'),
        ),
        migrations.AddConstraint(
            model_name='spincreditrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('public_sequence_number__isnull', False)), fields=('group_id', 'public_sequence_year', 'public_sequence_number'), name='unique_spin_public_sequence_per_group_year'),
        ),
        migrations.AddConstraint(
            model_name='spinrequestsequence',
            constraint=models.UniqueConstraint(fields=('group_id', 'year'), name='unique_spin_sequence_group_year'),
        ),
    ]
