# Generated by Django 5.1.6 on 2026-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_spin_public_sequence'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spincreditrequest',
            new_name='core_spincr_group_i_76ce4a_idx',
            old_name='core_spincr_group_i_1f2945_idx',
        ),
        migrations.AlterField(
            model_name='jawabufarmermaster',
            name='jbl_visit_status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Awaiting Analysis', 'Awaiting Analysis'), ('JBL to Schedule Visit', 'JBL to Schedule Visit'), ('Rescheduled', 'Rescheduled'), ('Deferred / On Hold', 'Deferred / On Hold'), ('Rejected by JBL', 'Rejected by JBL'), ('Opted for Cash', 'Opted for Cash'), ('Opted for other Partner', 'Opted for other Partner')], db_index=True, default='', help_text='Jawabu Comment After Visit Ã¢â‚¬â€\x9d 12-option dropdown set by JBL officer.', max_length=80),
        ),
        migrations.AlterField(
            model_name='jawabufarmermaster',
            name='requisition_date',
            field=models.DateField(blank=True, help_text='Jawabu Requisition Date Ã¢â‚¬â€\x9d only set after Credit Decision = Approved.', null=True),
        ),
        migrations.AlterField(
            model_name='spincreditrequest',
            name='import_status',
            field=models.CharField(choices=[('imported', 'Imported'), ('review_needed', 'Review Needed'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('completed', 'Completed')], db_index=True, default='review_needed', max_length=30),
        ),
    ]
