# Generated by Django 5.0.4 on 2026-07-19 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_tattrackercase_customer_identifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCaseEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_url', models.URLField(blank=True, default='', max_length=1000)),
                ('upload_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('upload_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCaseStaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telegram_user_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('telegram_username', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('OFFICER', 'Case officer'), ('MANAGER', 'Case manager')], default='OFFICER', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint case staff member',
                'verbose_name_plural': 'Complaint case staff members',
                'ordering': ['group_configuration', 'name'],
            },
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='client_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='gps_link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='source',
            field=models.CharField(default='telegram', max_length=50),
        ),
        migrations.AddIndex(
            model_name='caseupdate',
            index=models.Index(fields=['parsed_message', 'client_request_id'], name='core_caseup_parsed__f9fe63_idx'),
        ),
        migrations.AddField(
            model_name='complaintcaseevidence',
            name='case_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.caseupdate'),
        ),
        migrations.AddField(
            model_name='complaintcaseevidence',
            name='parsed_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_evidence', to='core.parsedmessage'),
        ),
        migrations.AddField(
            model_name='complaintcasestaffmember',
            name='group_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_case_staff', to='core.groupsheetconfiguration'),
        ),
        migrations.AddIndex(
            model_name='complaintcaseevidence',
            index=models.Index(fields=['parsed_message', 'created_at'], name='core_compla_parsed__5f420e_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcaseevidence',
            index=models.Index(fields=['group_id', 'upload_status'], name='core_compla_group_i_922acb_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcasestaffmember',
            index=models.Index(fields=['group_configuration', 'active'], name='core_compla_group_c_05589a_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcasestaffmember',
            index=models.Index(fields=['telegram_user_id'], name='core_compla_telegra_8aacd6_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcasestaffmember',
            index=models.Index(fields=['telegram_username'], name='core_compla_telegra_fd3524_idx'),
        ),
    ]
