# Generated by Django 5.0.4 on 2026-07-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_complaintcaseevidence_complaintcasestaffmember_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caseupdate',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('parsed_message', 'client_request_id'), name='unique_complaint_case_update_request'),
        ),
    ]
