# Generated by Django 5.0.4 on 2026-07-20 10:21

from django.db import migrations


def rename_sme_in_group_config(apps, schema_editor):
    GroupSheetConfiguration = apps.get_model('core', 'GroupSheetConfiguration')
    for config in GroupSheetConfiguration.objects.all():
        workflow = config.workflow
        if not workflow or workflow.get('type') != 'tat_tracker':
            continue
        
        changed = False
        
        if 'products' in workflow and isinstance(workflow['products'], list):
            if 'sme' in workflow['products']:
                workflow['products'] = ['business' if p == 'sme' else p for p in workflow['products']]
                changed = True
        
        if 'tat_targets_minutes' in workflow and isinstance(workflow['tat_targets_minutes'], dict):
            if 'sme' in workflow['tat_targets_minutes']:
                workflow['tat_targets_minutes']['business'] = workflow['tat_targets_minutes'].pop('sme')
                changed = True
        
        if 'staff' in workflow and isinstance(workflow['staff'], list):
            for staff_member in workflow['staff']:
                products_str = staff_member.get('products')
                if products_str and isinstance(products_str, str) and 'sme' in products_str:
                    staff_member['products'] = products_str.replace('sme', 'business')
                    changed = True
                
                sheets_str = staff_member.get('sheets')
                if sheets_str and isinstance(sheets_str, str) and 'sme' in sheets_str:
                    staff_member['sheets'] = sheets_str.replace('sme', 'business')
                    changed = True
        
        if changed:
            config.workflow = workflow
            config.save(update_fields=['workflow'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_sme_product_to_business'),
    ]

    operations = [
        migrations.RunPython(rename_sme_in_group_config, reverse_code=migrations.RunPython.noop),
    ]
