# Generated by Django 5.0.4 on 2026-07-20 10:58

from django.db import migrations


def rename_sme_in_group_config_lists(apps, schema_editor):
    GroupSheetConfiguration = apps.get_model('core', 'GroupSheetConfiguration')
    for config in GroupSheetConfiguration.objects.all():
        workflow = config.workflow
        if not workflow or workflow.get('type') != 'tat_tracker':
            continue
        
        changed = False
        
        # 1. workflow['products']
        if 'products' in workflow and isinstance(workflow['products'], list):
            if 'sme' in workflow['products']:
                workflow['products'] = ['business' if p == 'sme' else p for p in workflow['products']]
                changed = True
                
        # 2. workflow['default_products']
        if 'default_products' in workflow and isinstance(workflow['default_products'], list):
            if 'sme' in workflow['default_products']:
                workflow['default_products'] = ['business' if p == 'sme' else p for p in workflow['default_products']]
                changed = True
        
        # 3. workflow['tat_targets_minutes']
        if 'tat_targets_minutes' in workflow and isinstance(workflow['tat_targets_minutes'], dict):
            if 'sme' in workflow['tat_targets_minutes']:
                workflow['tat_targets_minutes']['business'] = workflow['tat_targets_minutes'].pop('sme')
                changed = True
        
        # 4. workflow['staff']
        if 'staff' in workflow and isinstance(workflow['staff'], list):
            for staff_member in workflow['staff']:
                # handle products
                products = staff_member.get('products')
                if isinstance(products, str) and 'sme' in products:
                    staff_member['products'] = products.replace('sme', 'business')
                    changed = True
                elif isinstance(products, list) and 'sme' in products:
                    staff_member['products'] = ['business' if p == 'sme' else p for p in products]
                    changed = True
                
                # handle sheets
                sheets = staff_member.get('sheets')
                if isinstance(sheets, str) and 'sme' in sheets:
                    staff_member['sheets'] = sheets.replace('sme', 'business')
                    changed = True
                elif isinstance(sheets, list) and 'sme' in sheets:
                    staff_member['sheets'] = ['business' if p == 'sme' else p for p in sheets]
                    changed = True
                    
        if changed:
            config.workflow = workflow
            config.save(update_fields=['workflow'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_sme_in_group_config'),
    ]

    operations = [
        migrations.RunPython(rename_sme_in_group_config_lists, reverse_code=migrations.RunPython.noop),
    ]
