# Generated by Django 5.0.4 on 2026-07-20 12:01

from django.db import migrations


def rename_sme_in_staff_members(apps, schema_editor):
    """
    Replace 'sme' with 'business' in the products CSV column of
    TatTrackerStaffMember rows.

    The products field stores a comma-separated string such as:
        "sme,logbook"   →  "business,logbook"
        "ALL"           →  unchanged
        "logbook"       →  unchanged
    """
    TatTrackerStaffMember = apps.get_model('core', 'TatTrackerStaffMember')

    to_update = []
    for staff in TatTrackerStaffMember.objects.all():
        products = str(staff.products or '').strip()
        if not products:
            continue
        # Split CSV, replace 'sme' token, rejoin
        parts = [p.strip() for p in products.split(',') if p.strip()]
        if 'sme' not in parts:
            continue
        new_parts = ['business' if p == 'sme' else p for p in parts]
        staff.products = ','.join(new_parts)
        to_update.append(staff)

    if to_update:
        TatTrackerStaffMember.objects.bulk_update(to_update, ['products'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_sme_in_group_config_lists'),
    ]

    operations = [
        migrations.RunPython(
            rename_sme_in_staff_members,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
