# Generated by Django 5.0.4 on 2026-07-21 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_sme_in_staff_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinBatchReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('telegram_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_message_hash', models.CharField(db_index=True, max_length=64)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('source_message_index', models.PositiveIntegerField(blank=True, null=True)),
                ('source_sender', models.CharField(blank=True, default='', max_length=255)),
                ('source_received_at', models.DateTimeField(blank=True, null=True)),
                ('raw_message', models.TextField()),
                ('category', models.CharField(choices=[('incomplete', 'Incomplete SPIN request'), ('ambiguous', 'Possible SPIN request')], db_index=True, max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('detected_fields', models.JSONField(blank=True, default=dict)),
                ('candidate_fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('resolved', 'Resolved to SPIN request'), ('rejected', 'Marked not SPIN')], db_index=True, default='pending', max_length=20)),
                ('resolution_fields', models.JSONField(blank=True, default=dict)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_batch_review_items', to='core.spincreditrequest')),
            ],
            options={
                'ordering': ['-source_received_at', '-created_at'],
                'indexes': [models.Index(fields=['group_id', 'status', 'created_at'], name='core_spinba_group_i_769f7c_idx'), models.Index(fields=['group_id', 'category', 'status'], name='core_spinba_group_i_686c68_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='spinbatchreviewitem',
            constraint=models.UniqueConstraint(fields=('group_id', 'source_message_hash'), name='unique_spin_batch_review_source_per_group'),
        ),
    ]
