# Generated by Codex on 2026-07-21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_spinbatchreviewitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCaseSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint case sequence',
                'verbose_name_plural': 'Complaint case sequences',
            },
        ),
        migrations.AddConstraint(
            model_name='complaintcasesequence',
            constraint=models.UniqueConstraint(fields=('group_id', 'year'), name='unique_complaint_sequence_group_year'),
        ),
    ]
