# Generated by Django 5.1.6 on 2026-07-23 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_tattrackercase_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='imab_customer_name',
            field=models.CharField(blank=True, default='', help_text='Customer name from the IMAB/system export used for payment documents.', max_length=255),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='payment_product',
            field=models.CharField(blank=True, default='', help_text='Payment document product value captured before order/payment generation.', max_length=128),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='repayment_date',
            field=models.CharField(blank=True, default='', help_text='Repayment date/day captured before order/payment generation.', max_length=64),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='repayment_tenor',
            field=models.CharField(blank=True, default='', help_text='Loan tenor captured before order/payment generation.', max_length=64),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='system_branch',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Branch from the IMAB/system export used for payment documents.', max_length=128),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='system_deposit_paid_jbl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deposit paid to JBL from the IMAB/system export.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='system_loan_officer',
            field=models.CharField(blank=True, default='', help_text='Loan officer from the IMAB/system export; JBL officer is used as fallback.', max_length=255),
        ),
        migrations.CreateModel(
            name='InvoiceUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='application/pdf', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('parse_failed', 'Parse Failed'), ('partially_matched', 'Partially Matched'), ('matched', 'Matched'), ('needs_review', 'Needs Review')], db_index=True, default='uploaded', max_length=32)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('total_parsed', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice upload batch',
                'verbose_name_plural': 'Invoice upload batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_invoic_status_71e6e7_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='core_invoic_uploade_261f65_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('final', 'Final'), ('failed', 'Failed')], db_index=True, default='preview', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(default='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', max_length=255)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_url', models.URLField(blank=True, default='', max_length=1000)),
                ('generated_by', models.CharField(blank=True, default='', max_length=255)),
                ('finalized_by', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('farmer_ids', models.JSONField(blank=True, default=list)),
                ('invoice_batch_ids', models.JSONField(blank=True, default=list)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment document',
                'verbose_name_plural': 'Payment documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number', 'status'], name='core_paymen_order_n_125c1c_idx'), models.Index(fields=['status', 'created_at'], name='core_paymen_status_04bf55_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'final')), fields=('order_number', 'version'), name='unique_final_payment_document_version')],
            },
        ),
        migrations.CreateModel(
            name='ParsedInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.PositiveIntegerField(default=0)),
                ('invoice_no', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_date_raw', models.CharField(blank=True, default='', max_length=64)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('customer_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('customer_phone', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_after_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_due_check', models.CharField(blank=True, default='', max_length=128)),
                ('calculated_balance_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_due_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_due_check_basis', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('ambiguous', 'Ambiguous'), ('ignored', 'Ignored')], db_index=True, default='unmatched', max_length=32)),
                ('matched_order_number', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.invoiceuploadbatch')),
                ('matched_farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsed_invoices', to='core.jawabufarmermaster')),
            ],
            options={
                'verbose_name': 'Parsed invoice',
                'verbose_name_plural': 'Parsed invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice_no'], name='core_parsed_invoice_d34219_idx'), models.Index(fields=['status', 'created_at'], name='core_parsed_status_4d11bc_idx'), models.Index(fields=['matched_order_number', 'status'], name='core_parsed_matched_d85c97_idx')],
            },
        ),
    ]
