# Generated by Django 5.1.6 on 2026-07-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_jawabufarmermaster_imab_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbatch',
            name='drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='drive_upload_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='drive_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
