# Generated by Django 5.1.6 on 2026-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_requisitionbatch_drive_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HB Payment Document', max_length=255)),
                ('file', models.FileField(help_text='Upload the Excel (.xlsx) payment template here.', upload_to='payment_documents/')),
                ('is_active', models.BooleanField(default=True, help_text='Mark this as the active template used for payment generation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment document template',
                'verbose_name_plural': 'Payment document templates',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
