# Generated by Django 5.1.6 on 2026-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_paymentdocumenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_drive_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_generated_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisitionbatch',
            name='status',
            field=models.CharField(choices=[('preview', 'Preview'), ('generated', 'Generated'), ('invoices_uploaded', 'Invoices Uploaded'), ('partially_invoiced', 'Partially Invoiced'), ('completed', 'Completed'), ('needs_review', 'Needs Review')], db_index=True, default='generated', max_length=32),
        ),
    ]
