# Generated by Codex on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_requisitionbatch_preview_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocumenttemplate',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paymentdocumenttemplate',
            name='content_type',
            field=models.CharField(blank=True, default='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentdocumenttemplate',
            name='drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentdocumenttemplate',
            name='drive_upload_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentdocumenttemplate',
            name='drive_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdocumenttemplate',
            name='drive_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='paymentdocumenttemplate',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentdocumenttemplate',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='content_type',
            field=models.CharField(blank=True, default='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='drive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='drive_upload_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='drive_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='drive_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
