# Generated by Django 5.1.6 on 2026-07-23 15:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_template_drive_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedInvoiceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('ignored', 'Ignored'), ('restored', 'Restored'), ('note', 'Note')], db_index=True, max_length=32)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.parsedinvoice')),
            ],
            options={
                'verbose_name': 'Parsed invoice event',
                'verbose_name_plural': 'Parsed invoice events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'created_at'], name='core_parsed_invoice_aa9800_idx'), models.Index(fields=['action', 'created_at'], name='core_parsed_action_d20141_idx')],
            },
        ),
    ]
