# Generated by Django 5.1.6 on 2026-07-24 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_initialize_jawabu_case360'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIdentityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(db_index=True, max_length=255)),
                ('candidate_records', models.JSONField(default=list)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_identity_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('telegram_username', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('telegram_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name', 'telegram_id'],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker')], db_index=True, max_length=40)),
                ('role', models.CharField(db_index=True, max_length=80)),
                ('branch', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('product', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source', models.CharField(default='admin', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_grants', to='core.groupsheetconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workflow', 'role', 'branch', 'product'],
                'constraints': [models.UniqueConstraint(fields=('user', 'workflow', 'role', 'branch', 'product', 'group_configuration'), name='unique_user_access_scope')],
            },
        ),
        migrations.CreateModel(
            name='LegacyStaffUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_model', models.CharField(max_length=80)),
                ('legacy_id', models.CharField(max_length=100)),
                ('match_method', models.CharField(max_length=40)),
                ('confidence', models.CharField(default='high', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_staff_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('legacy_model', 'legacy_id'), name='unique_legacy_staff_mapping')],
            },
        ),
    ]
