# Generated by Django 5.1.6 on 2026-07-24 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_unified_staff_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accessgrant',
            name='unique_user_access_scope',
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('group_configuration__isnull', False)), fields=('user', 'workflow', 'role', 'branch', 'product', 'group_configuration'), name='unique_user_group_access_scope'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.UniqueConstraint(condition=models.Q(('group_configuration__isnull', True)), fields=('user', 'workflow', 'role', 'branch', 'product'), name='unique_user_global_access_scope'),
        ),
    ]
