# Generated by Django 5.1.6 on 2026-07-24 12:55

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_accessgrant_null_scope_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_id__gt', '')), fields=('telegram_id',), name='unique_bound_telegram_id'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('telegram_username'), condition=models.Q(('telegram_username__gt', '')), name='unique_enrolled_telegram_username'),
        ),
    ]
