# Generated by Django 5.1.6 on 2026-07-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_telegram_username_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocument',
            name='payment_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
