# Generated by Django 5.1.6 on 2026-07-27 07:09

import django.db.models.functions.text
from django.db import migrations, models


DEFAULT_BRANCHES = ('Biogas Unit', 'Embu', 'Nakuru', 'West Nairobi')
DEFAULT_COUNTIES = (
    'BARINGO', 'BOMET', 'BUNGOMA', 'BUSIA', 'ELGEYO MARAKWET', 'EMBU',
    'GARISSA', 'HOMA BAY', 'ISIOLO', 'KAJIADO', 'KAKAMEGA', 'KERICHO',
    'KIAMBU', 'KILIFI', 'KIRINYAGA', 'KISII', 'KISUMU', 'KITUI', 'KWALE',
    'LAIKIPIA', 'LAMU', 'MACHAKOS', 'MAKUENI', 'MANDERA', 'MARSABIT',
    'MERU', 'MIGORI', 'MOMBASA', 'MURANGA', 'NAIROBI', 'NAKURU', 'NANDI',
    'NAROK', 'NYAMIRA', 'NYANDARUA', 'NYERI', 'SAMBURU', 'SIAYA',
    'TAITA TAVETA', 'TANA RIVER', 'THARAKA NITHI', 'TRANS NZOIA',
    'TURKANA', 'UASIN GISHU', 'VIHIGA', 'WAJIR', 'WEST POKOT',
)


def seed_operational_locations(apps, schema_editor):
    OperationalLocation = apps.get_model('core', 'OperationalLocation')
    for location_type, values in (('branch', DEFAULT_BRANCHES), ('county', DEFAULT_COUNTIES)):
        for sort_order, name in enumerate(values):
            OperationalLocation.objects.get_or_create(
                location_type=location_type,
                name=name,
                defaults={'sort_order': sort_order},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_paymentdocument_payment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('branch', 'Branch'), ('county', 'County')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operational location',
                'verbose_name_plural': 'Operational locations',
                'ordering': ['location_type', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('location_type'), name='unique_operational_location_name_ci')],
            },
        ),
        migrations.RunPython(seed_operational_locations, migrations.RunPython.noop),
    ]
