# Generated by Django 5.1.6 on 2026-07-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_seed_default_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceuploadbatch',
            name='client_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='invoiceuploadbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('client_request_id',), name='unique_invoice_upload_client_request'),
        ),
    ]
