# Generated by Django 5.1.6 on 2026-07-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_invoiceuploadbatch_client_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='workflow',
            field=models.CharField(choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40),
        ),
    ]
