# Generated by Django 5.1.6 on 2026-07-27 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_tat_signer_history(apps, schema_editor):
    """Snapshot legacy signer details before dropping the staff tables."""
    Certificate = apps.get_model('core', 'TatTrackerApprovalCertificate')
    Mapping = apps.get_model('core', 'LegacyStaffUserMapping')
    UserProfile = apps.get_model('core', 'UserProfile')

    mappings = {
        str(mapping.legacy_id): mapping.user_id
        for mapping in Mapping.objects.filter(legacy_model='TatTrackerStaffMember')
    }
    for certificate in Certificate.objects.select_related('staff_member'):
        staff = certificate.staff_member
        certificate.signer_name = staff.name
        certificate.signer_telegram_id = staff.telegram_user_id
        certificate.signer_national_id = staff.signing_national_id
        certificate.signer_phone_number = staff.signing_phone_number
        certificate.signer_email = staff.signing_email
        certificate.staff_user_id = mappings.get(str(staff.pk))
        certificate.save(update_fields=[
            'staff_user', 'signer_name', 'signer_telegram_id',
            'signer_national_id', 'signer_phone_number', 'signer_email',
        ])

    for legacy_id, user_id in mappings.items():
        staff = apps.get_model('core', 'TatTrackerStaffMember').objects.filter(pk=legacy_id).first()
        profile = UserProfile.objects.filter(user_id=user_id).first()
        if not staff or not profile:
            continue
        updates = {}
        for field in ('signing_national_id', 'signing_phone_number', 'signing_email'):
            if not getattr(profile, field, '') and getattr(staff, field, ''):
                updates[field] = getattr(staff, field)
        if updates:
            for field, value in updates.items():
                setattr(profile, field, value)
            profile.save(update_fields=[*updates, 'updated_at'])


def refuse_rollback(apps, schema_editor):
    """Do not recreate empty legacy identity tables after this destructive cutover."""
    raise RuntimeError(
        'core.0062 removes legacy staff identity data and cannot be reversed safely.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_accessgrant_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tattrackerapprovalcertificate',
            name='signer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='tattrackerapprovalcertificate',
            name='signer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tattrackerapprovalcertificate',
            name='signer_national_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='tattrackerapprovalcertificate',
            name='signer_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tattrackerapprovalcertificate',
            name='signer_telegram_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tattrackerapprovalcertificate',
            name='staff_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tat_approval_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signing_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signing_national_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signing_phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.RunPython(preserve_tat_signer_history, refuse_rollback),
        migrations.RemoveField(
            model_name='complaintcasestaffmember',
            name='group_configuration',
        ),
        migrations.DeleteModel(
            name='JawabuPortalStaffMember',
        ),
        migrations.RemoveField(
            model_name='legacystaffusermapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffidentityreview',
            name='resolved_user',
        ),
        migrations.RemoveField(
            model_name='tattrackerstaffmember',
            name='group_configuration',
        ),
        migrations.RemoveField(
            model_name='tattrackerapprovalcertificate',
            name='staff_member',
        ),
        migrations.DeleteModel(
            name='ComplaintCaseStaffMember',
        ),
        migrations.DeleteModel(
            name='LegacyStaffUserMapping',
        ),
        migrations.DeleteModel(
            name='StaffIdentityReview',
        ),
        migrations.DeleteModel(
            name='TatTrackerStaffMember',
        ),
    ]
