# Generated by Django 5.1.6 on 2026-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_complaintcasestaffmember_group_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_version',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Latest stored preview version for this order.'),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='version',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Latest final requisition version for this order; starts at 1 when generated.'),
        ),
    ]
