# Generated by Django 5.1.6 on 2026-07-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_requisitionbatch_preview_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocument',
            name='call_up_comments',
            field=models.TextField(blank=True, default='', help_text='Head of Rural approval comment written to the payment template COL column.'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='status',
            field=models.CharField(choices=[('preview', 'Preview'), ('pending_review', 'Pending Head of Rural review'), ('reviewed', 'Reviewed'), ('final', 'Final'), ('failed', 'Failed')], db_index=True, default='preview', max_length=32),
        ),
    ]
