# Generated by Django 5.1.6 on 2026-07-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_paymentdocument_call_up_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocument',
            name='case_call_up_comments',
            field=models.JSONField(blank=True, default=dict, help_text='Per-case Head of Rural payment COL comments keyed by farmer ID.'),
        ),
    ]
