# Generated by Django 5.1.6 on 2026-07-28 06:12

from django.db import migrations, models


def backfill_pending_credit_decisions(apps, schema_editor):
    Farmer = apps.get_model('core', 'JawabuFarmerMaster')
    Farmer.objects.filter(credit_decision='').update(credit_decision='Pending')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_paymentdocument_case_call_up_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabufarmermaster',
            name='credit_decision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('Exemption Approved', 'Exemption Approved'), ('Pending', 'Pending')], db_index=True, default='Pending', help_text='Credit Analysis decision from master data dropdown.', max_length=80),
        ),
        migrations.RunPython(backfill_pending_credit_decisions, migrations.RunPython.noop),
    ]
