# Generated by Django 5.1.6 on 2026-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_jawabufarmeruploadbatch_import_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocument',
            name='drive_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='drive_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='drive_sync_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='drive_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='drive_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='drive_sync_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_drive_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_drive_next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='preview_drive_sync_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
