# Generated by Django 5.1.6 on 2026-07-29 10:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_paymentdocument_drive_last_sync_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40)),
                ('role', models.CharField(db_index=True, max_length=80)),
                ('capability_key', models.CharField(db_index=True, max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'workflow role capability',
                'verbose_name_plural': 'workflow role capabilities',
                'ordering': ['workflow', 'role', 'capability_key'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'role', 'capability_key'), name='unique_workflow_role_capability')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRoleCapabilityAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40)),
                ('role', models.CharField(db_index=True, max_length=80)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='admin_matrix', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workflow capability audit event',
                'verbose_name_plural': 'workflow capability audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'role', 'created_at'], name='core_workfl_workflo_1d90b5_idx')],
            },
        ),
    ]
