# Generated by Django 5.1.6 on 2026-07-29 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def initialize_access_control_state(apps, schema_editor):
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    State = apps.get_model('core', 'AccessControlPolicyState')
    Snapshot = apps.get_model('core', 'AccessControlPolicySnapshot')
    Grant = apps.get_model('core', 'AccessGrant')
    Group = apps.get_model('auth', 'Group')
    Capability.objects.filter(enabled=False).update(effect='deny')
    state, _created = State.objects.get_or_create(singleton=1, defaults={'version': 1})
    grants = []
    for row in Grant.objects.order_by('user_id', 'workflow', 'role', 'branch', 'product').values('id', 'user_id', 'workflow', 'role', 'branch', 'product', 'group_configuration_id', 'active', 'source'):
        row['id'] = str(row['id'])
        grants.append(row)
    Snapshot.objects.get_or_create(
        version=state.version,
        defaults={'state': {
            'capabilities': list(Capability.objects.order_by('workflow', 'role', 'capability_key').values('workflow', 'role', 'capability_key', 'effect')),
            'grants': grants,
        }},
    )
    Group.objects.get_or_create(name='Access Policy Approvers')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_seed_workflow_role_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlPolicyState',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='workflowrolecapability',
            name='effect',
            field=models.CharField(choices=[('allow', 'Allow'), ('deny', 'Explicit deny')], default='allow', max_length=12),
        ),
        migrations.CreateModel(
            name='AccessControlChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('capability_policy', 'Role capability policy'), ('access_grant', 'Staff access grant')], db_index=True, max_length=32)),
                ('workflow', models.CharField(blank=True, choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, default='', max_length=40)),
                ('role', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('proposed_snapshot', models.JSONField(blank=True, default=dict)),
                ('impact', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('stale', 'Stale')], db_index=True, default='draft', max_length=16)),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_access_control_changes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_access_control_changes', to=settings.AUTH_USER_MODEL)),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_requests', to='core.accesscontrolchangerequest')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_control_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessControlNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('admin', 'Admin'), ('telegram', 'Telegram')], max_length=16)),
                ('event', models.CharField(max_length=64)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.accesscontrolchangerequest')),
            ],
        ),
        migrations.CreateModel(
            name='AccessControlPolicySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(unique=True)),
                ('state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_snapshot', to='core.accesscontrolchangerequest')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('workflow', models.CharField(db_index=True, max_length=40)),
                ('capability_key', models.CharField(db_index=True, max_length=120)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40)),
                ('role', models.CharField(max_length=80)),
                ('branch', models.CharField(blank=True, default='', max_length=120)),
                ('product', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.TextField()),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activated_emergency_access', to=settings.AUTH_USER_MODEL)),
                ('group_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.groupsheetconfiguration')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_emergency_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accesscontrolchangerequest',
            index=models.Index(fields=['status', 'requested_at'], name='core_access_status_76f2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='accesscontrolchangerequest',
            index=models.Index(fields=['workflow', 'role', 'status'], name='core_access_workflo_b53355_idx'),
        ),
        migrations.AddIndex(
            model_name='capabilityusagedaily',
            index=models.Index(fields=['workflow', 'capability_key', 'day'], name='core_capabi_workflo_f1e66c_idx'),
        ),
        migrations.AddConstraint(
            model_name='capabilityusagedaily',
            constraint=models.UniqueConstraint(fields=('day', 'user', 'workflow', 'capability_key'), name='unique_daily_capability_usage'),
        ),
        migrations.AddIndex(
            model_name='emergencyaccessgrant',
            index=models.Index(fields=['user', 'workflow', 'expires_at'], name='core_emerge_user_id_01aa6c_idx'),
        ),
        migrations.RunPython(initialize_access_control_state, migrations.RunPython.noop),
    ]
