# Generated by Django 5.1.6 on 2026-07-29 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_accesscontrolpolicystate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(db_index=True, max_length=40)),
                ('context_key', models.CharField(db_index=True, max_length=180)),
                ('payload', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniapp_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['workflow', 'context_key', 'expires_at'], name='core_miniap_workflo_cc1b73_idx'), models.Index(fields=['user', 'expires_at'], name='core_miniap_user_id_25d95f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'workflow', 'context_key'), name='unique_miniapp_draft_context_per_user')],
            },
        ),
    ]
