# Generated by Django 5.1.6 on 2026-07-29 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_miniapp_drafts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='workflow_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='workflow_state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='workflow_state_entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabupipelineevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jawabu_pipeline_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabupipelineevent',
            name='authority_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jawabu_pipeline_authorized_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabupipelineevent',
            name='from_state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='jawabupipelineevent',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jawabupipelineevent',
            name='revision_after',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabupipelineevent',
            name='revision_before',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabupipelineevent',
            name='to_state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='jawabupipelineevent',
            name='transition_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='workflow_revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tat_tracker_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='authority_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tat_tracker_authorized_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='from_state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='revision_after',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='revision_before',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='to_state',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tattrackerevent',
            name='transition_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='tattrackerevent',
            name='source',
            field=models.CharField(choices=[('mini_app', 'Mini App'), ('telegram', 'Telegram'), ('sheet_sync', 'Sheet Sync'), ('admin_correction', 'Admin Correction'), ('workflow_transition', 'Workflow Transition')], db_index=True, default='mini_app', max_length=40),
        ),
        migrations.CreateModel(
            name='WorkflowSlaEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('jawabu_pipeline', 'Jawabu Pipeline'), ('tat_tracker', 'TAT Tracker')], db_index=True, max_length=40)),
                ('subject_id', models.CharField(db_index=True, max_length=64)),
                ('group_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('stage_key', models.CharField(db_index=True, max_length=120)),
                ('target_minutes', models.PositiveIntegerField()),
                ('overdue_minutes', models.PositiveIntegerField()),
                ('escalation_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending follow-up'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'workflow SLA escalation',
                'verbose_name_plural': 'workflow SLA escalations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'status', 'created_at'], name='core_workfl_workflo_107dda_idx'), models.Index(fields=['group_id', 'stage_key', 'status'], name='core_workfl_group_i_259eb8_idx')],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'subject_id', 'stage_key', 'escalation_date'), name='unique_workflow_sla_escalation_day')],
            },
        ),
    ]
