# Generated by Django 5.1.6 on 2026-07-29 14:36

from django.db import migrations


def _state_for(farmer):
    if farmer.deferred_until:
        return 'deferred'
    if farmer.order_number:
        return 'ordered'
    if farmer.final_decision == 'Approved':
        return 'order'
    if farmer.final_decision == 'Rejected':
        return 'rejected'
    if farmer.final_decision == 'Deferred':
        return 'deferred'
    if farmer.credit_decision == 'Rejected':
        return 'rejected'
    if farmer.credit_decision == 'Deferred':
        return 'deferred'
    if farmer.credit_decision in {'Approved', 'Exemption Approved'}:
        return 'final_review'
    if farmer.jbl_visit_status == 'Rejected by JBL':
        return 'rejected'
    if farmer.jbl_visit_status in {'Opted for Cash', 'Opted for other Partner'}:
        return 'withdrawn'
    if farmer.jbl_visit_date:
        return 'credit'
    return 'jbl_visit'


def backfill_workflow_integrity(apps, schema_editor):
    Farmer = apps.get_model('core', 'JawabuFarmerMaster')
    # This establishes a safe current-state baseline without manufacturing
    # retroactive transition events or attributing old work to an actor.
    for farmer in Farmer.objects.filter(workflow_state='').iterator(chunk_size=500):
        farmer.workflow_state = _state_for(farmer)
        farmer.workflow_state_entered_at = farmer.updated_at or farmer.created_at
        farmer.workflow_revision = max(int(farmer.workflow_revision or 1), 1)
        farmer.save(update_fields=['workflow_state', 'workflow_state_entered_at', 'workflow_revision'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_workflow_integrity'),
    ]

    operations = [
        migrations.RunPython(backfill_workflow_integrity, migrations.RunPython.noop),
    ]
