# Generated by Django 5.1.6 on 2026-07-29 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_backfill_workflow_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tattrackerevent',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('case', 'request_id'), name='unique_tat_event_request_per_case'),
        ),
    ]
