# Generated by Django 5.1.6 on 2026-07-29 15:37

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_tat_workflow_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabuDataQualityResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('corrected', 'Corrected canonical value'), ('accepted', 'Accepted source value'), ('linked', 'Linked to existing customer'), ('ignored', 'Accepted documented exception'), ('rejected', 'Rejected source row')], db_index=True, max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('before_value', models.TextField(blank=True, default='')),
                ('after_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='core.jawabudataqualityissue')),
            ],
            options={
                'verbose_name': 'Jawabu data-quality resolution',
                'verbose_name_plural': 'Jawabu data-quality resolutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Operational product',
                'verbose_name_plural': 'Operational products',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='jawabu_unique_operational_product_name_ci'), models.UniqueConstraint(django.db.models.functions.text.Lower('code'), condition=models.Q(('code', ''), _negated=True), name='jawabu_unique_operational_product_code_ci')],
            },
        ),
        migrations.CreateModel(
            name='JawabuCustomerFieldProvenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_index=True, max_length=80)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('source', models.CharField(db_index=True, max_length=40)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_provenance', to='core.jawabufarmermaster')),
            ],
            options={
                'verbose_name': 'Jawabu customer field provenance',
                'verbose_name_plural': 'Jawabu customer field provenance',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['farmer', 'field_name', 'occurred_at'], name='core_jawabu_farmer__723e63_idx'), models.Index(fields=['source', 'occurred_at'], name='core_jawabu_source_0bbcf9_idx')],
            },
        ),
        migrations.CreateModel(
            name='JawabuCustomerPhoneHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_history', to='core.jawabucustomer')),
            ],
            options={
                'verbose_name': 'Jawabu customer phone history',
                'verbose_name_plural': 'Jawabu customer phone history',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['phone', 'is_current'], name='core_jawabu_phone_592615_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'phone'), name='jawabu_unique_customer_phone_history')],
            },
        ),
    ]
