# Generated by Django 5.1.6 on 2026-07-29 17:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_seed_operational_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendarHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business calendar holiday',
                'verbose_name_plural': 'business calendar holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_workflow_sla_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='branch',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='follow_up_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_workflow_sla_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='responsible_role',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='threshold_percent',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.CreateModel(
            name='WorkflowTatDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(db_index=True)),
                ('workflow', models.CharField(choices=[('jawabu_pipeline', 'Jawabu Pipeline'), ('tat_tracker', 'TAT Tracker')], db_index=True, max_length=40)),
                ('group_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('branch', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('product_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('stage_key', models.CharField(db_index=True, max_length=120)),
                ('responsible_role', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('overdue_count', models.PositiveIntegerField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('median_sla_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('p90_sla_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('median_wall_clock_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'workflow TAT daily metric',
                'verbose_name_plural': 'workflow TAT daily metrics',
                'ordering': ['-metric_date', 'workflow', 'stage_key'],
                'indexes': [models.Index(fields=['workflow', 'metric_date', 'branch'], name='core_workfl_workflo_b73053_idx'), models.Index(fields=['group_id', 'metric_date', 'stage_key'], name='core_workfl_group_i_366afd_idx')],
                'constraints': [models.UniqueConstraint(fields=('metric_date', 'workflow', 'group_id', 'branch', 'product_key', 'stage_key', 'responsible_role'), name='unique_workflow_tat_daily_metric')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTimelineAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('jawabu_pipeline', 'Jawabu Pipeline'), ('tat_tracker', 'TAT Tracker')], db_index=True, max_length=40)),
                ('subject_id', models.CharField(db_index=True, max_length=64)),
                ('source_event_id', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('correction', 'Correction'), ('redaction', 'Redaction'), ('artifact_link', 'Artifact link')], db_index=True, max_length=20)),
                ('supersedes_event_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('artifact_name', models.CharField(blank=True, default='', max_length=255)),
                ('artifact_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_timeline_annotations', to=settings.AUTH_USER_MODEL)),
                ('authority_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_timeline_annotation_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'workflow timeline annotation',
                'verbose_name_plural': 'workflow timeline annotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'subject_id', 'created_at'], name='core_workfl_workflo_6703d6_idx'), models.Index(fields=['workflow', 'source_event_id', 'kind'], name='core_workfl_workflo_d4bc84_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'redaction')), fields=('workflow', 'subject_id', 'source_event_id', 'kind'), name='unique_workflow_timeline_redaction')],
            },
        ),
    ]
