# Generated by Django 5.1.6 on 2026-07-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_businesscalendarholiday_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowtatdailymetric',
            name='unique_workflow_tat_daily_metric',
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='responsible_actor',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='workflowtatdailymetric',
            name='responsible_actor',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AddConstraint(
            model_name='workflowtatdailymetric',
            constraint=models.UniqueConstraint(fields=('metric_date', 'workflow', 'group_id', 'branch', 'product_key', 'stage_key', 'responsible_role', 'responsible_actor'), name='unique_workflow_tat_daily_metric'),
        ),
    ]
