# Generated by Django 5.1.6 on 2026-07-29 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_document_signoff_policy(apps, schema_editor):
    """Seed the explicit initial policy without granting a broad new role."""
    Policy = apps.get_model('core', 'DocumentSignoffPolicy')
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    for document_type in ('requisition', 'payment'):
        Policy.objects.get_or_create(
            document_type=document_type,
            defaults={
                'workflow': 'jawabu_portal',
                # Portal Head of Rural review is presently represented by the
                # controlled ADMIN role.  Future changes use maker-checker.
                'approval_role': 'ADMIN',
                'is_active': True,
            },
        )
    Capability.objects.get_or_create(
        workflow='jawabu_portal',
        role='ADMIN',
        capability_key='portal.documents.sign',
        defaults={'enabled': True, 'effect': 'allow'},
    )


def unseed_document_signoff_policy(apps, schema_editor):
    Policy = apps.get_model('core', 'DocumentSignoffPolicy')
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    Policy.objects.filter(document_type__in=('requisition', 'payment')).delete()
    Capability.objects.filter(
        workflow='jawabu_portal',
        role='ADMIN',
        capability_key='portal.documents.sign',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_remove_workflowtatdailymetric_unique_workflow_tat_daily_metric_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignoffPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('requisition', 'Requisition / order'), ('payment', 'Payment schedule')], max_length=24, unique=True)),
                ('workflow', models.CharField(choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], default='jawabu_portal', editable=False, max_length=40)),
                ('approval_role', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'document sign-off policy',
                'verbose_name_plural': 'document sign-off policies',
                'ordering': ['document_type'],
            },
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='file_content',
            field=models.BinaryField(blank=True, default=bytes),
        ),
        migrations.AlterField(
            model_name='accesscontrolchangerequest',
            name='change_type',
            field=models.CharField(choices=[('capability_policy', 'Role capability policy'), ('access_grant', 'Staff access grant'), ('document_signoff_policy', 'Document sign-off policy')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='DocumentPhysicalSignoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('requisition', 'Requisition / order'), ('payment', 'Payment schedule')], db_index=True, max_length=24)),
                ('source_version', models.PositiveIntegerField(default=1)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_content_type', models.CharField(max_length=255)),
                ('source_checksum', models.CharField(db_index=True, max_length=64)),
                ('source_file_content', models.BinaryField(blank=True, default=bytes)),
                ('scan_filename', models.CharField(max_length=255)),
                ('scan_content_type', models.CharField(max_length=255)),
                ('scan_size', models.PositiveIntegerField(default=0)),
                ('scan_checksum', models.CharField(db_index=True, max_length=64)),
                ('scan_file_content', models.BinaryField(blank=True, default=bytes)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_url', models.URLField(blank=True, default='', max_length=1000)),
                ('drive_sync_attempts', models.PositiveIntegerField(default=0)),
                ('drive_last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('drive_next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('drive_upload_error', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('upload_pending', 'Upload pending'), ('signed_approved', 'Signed scan approved'), ('upload_failed', 'Upload retry required'), ('rejected', 'Rejected')], db_index=True, default='upload_pending', max_length=32)),
                ('attested_complete', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_physical_document_signoffs', to=settings.AUTH_USER_MODEL)),
                ('payment_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_signoffs', to='core.paymentdocument')),
                ('requisition_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_signoffs', to='core.requisitionbatch')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_physical_document_signoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'physical document sign-off',
                'verbose_name_plural': 'physical document sign-offs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPhysicalSignoffEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('upload_failed', 'Upload failed'), ('retry_started', 'Retry started'), ('rejected', 'Rejected')], db_index=True, max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.documentphysicalsignoff')),
            ],
            options={
                'verbose_name': 'physical document sign-off event',
                'verbose_name_plural': 'physical document sign-off events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentphysicalsignoff',
            index=models.Index(fields=['document_type', 'status', 'created_at'], name='core_docume_documen_b7a11a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentphysicalsignoff',
            index=models.Index(fields=['requisition_batch', 'source_version'], name='core_docume_requisi_79caba_idx'),
        ),
        migrations.AddIndex(
            model_name='documentphysicalsignoff',
            index=models.Index(fields=['payment_document', 'source_version'], name='core_docume_payment_bf6132_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentphysicalsignoff',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document_type', 'requisition'), ('payment_document__isnull', True), ('requisition_batch__isnull', False)), models.Q(('document_type', 'payment'), ('payment_document__isnull', False), ('requisition_batch__isnull', True)), _connector='OR'), name='document_signoff_matches_artifact_type'),
        ),
        migrations.AddConstraint(
            model_name='documentphysicalsignoff',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('request_id',), name='unique_document_signoff_request_id'),
        ),
        migrations.AddConstraint(
            model_name='documentphysicalsignoff',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'requisition'), ('status', 'signed_approved')), fields=('requisition_batch', 'source_version'), name='unique_signed_requisition_version'),
        ),
        migrations.AddConstraint(
            model_name='documentphysicalsignoff',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'payment'), ('status', 'signed_approved')), fields=('payment_document', 'source_version'), name='unique_signed_payment_version'),
        ),
        migrations.AddIndex(
            model_name='documentphysicalsignoffevent',
            index=models.Index(fields=['signoff', 'created_at'], name='core_docume_signoff_db748c_idx'),
        ),
        migrations.RunPython(seed_document_signoff_policy, unseed_document_signoff_policy),
    ]
