# Generated by Django 5.1.6 on 2026-07-30 06:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_approval_controls_capability(apps, schema_editor):
    """Give the existing controlled Portal Admin role the new gate only."""
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    Capability.objects.get_or_create(
        workflow='jawabu_portal',
        role='ADMIN',
        capability_key='portal.approval.delegation.authorize',
        defaults={'enabled': True, 'effect': 'allow'},
    )


def unseed_approval_controls_capability(apps, schema_editor):
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    Capability.objects.filter(
        workflow='jawabu_portal', role='ADMIN',
        capability_key='portal.approval.delegation.authorize',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_physical_document_signoffs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabuApprovalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('satisfaction_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jawabu approval condition',
                'verbose_name_plural': 'Jawabu approval conditions',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JawabuApprovalDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate', models.CharField(choices=[('credit', 'Credit analysis'), ('final_review', 'Head of Rural final review'), ('payment_review', 'Head of Rural payment review')], db_index=True, max_length=32)),
                ('source_role', models.CharField(default='ADMIN', max_length=80)),
                ('branch', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('product', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('reason', models.TextField()),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jawabu approval delegation',
                'verbose_name_plural': 'Jawabu approval delegations',
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='JawabuApprovalDelegationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('revoked', 'Revoked')], max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Jawabu approval delegation event',
                'verbose_name_plural': 'Jawabu approval delegation events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JawabuApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate', models.CharField(choices=[('credit', 'Credit analysis'), ('final_review', 'Head of Rural final review'), ('payment_review', 'Head of Rural payment review')], db_index=True, max_length=32)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('approved_with_conditions', 'Approved with conditions'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('returned_for_rework', 'Returned for rework')], max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('conditions_pending', 'Conditions pending'), ('invalidated', 'Invalidated'), ('expired', 'Expired'), ('superseded', 'Superseded'), ('legacy', 'Legacy approval')], db_index=True, default='active', max_length=32)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('comment', models.TextField(blank=True, default='')),
                ('source_revision', models.PositiveIntegerField(default=1)),
                ('authority_role', models.CharField(blank=True, default='', max_length=80)),
                ('decided_by_label', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jawabu approval record',
                'verbose_name_plural': 'Jawabu approval records',
                'ordering': ['-decided_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JawabuMediaAccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(default='view', max_length=32)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Jawabu media access event',
                'verbose_name_plural': 'Jawabu media access events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='capture_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='capture_location_unavailable_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='capture_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='jawabu_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_attachments', to='core.jawabufarmermaster'),
        ),
        migrations.AlterField(
            model_name='jawabufarmermaster',
            name='credit_decision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Approved with Conditions', 'Approved with Conditions'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('Exemption Approved', 'Exemption Approved'), ('Pending', 'Pending')], db_index=True, default='Pending', help_text='Credit Analysis decision from master data dropdown.', max_length=80),
        ),
        migrations.AlterField(
            model_name='jawabufarmermaster',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Approved with Conditions', 'Approved with Conditions'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('Under Review', 'Under Review')], db_index=True, default='', help_text='Head of Rural final decision. Approved records are ready for order batching.', max_length=80),
        ),
        migrations.AddIndex(
            model_name='mediaattachment',
            index=models.Index(fields=['jawabu_farmer', 'file_type', 'upload_status'], name='core_mediaa_jawabu__7eb7e0_idx'),
        ),
        migrations.AddField(
            model_name='jawabuapprovalcondition',
            name='satisfied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabuapprovaldelegation',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_jawabu_approval_delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabuapprovaldelegation',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jawabu_approval_delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabuapprovaldelegation',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_jawabu_approval_delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabuapprovaldelegationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabuapprovaldelegationevent',
            name='delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.jawabuapprovaldelegation'),
        ),
        migrations.AddField(
            model_name='jawabuapprovalrecord',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabuapprovalrecord',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to='core.jawabuapprovaldelegation'),
        ),
        migrations.AddField(
            model_name='jawabuapprovalrecord',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_records', to='core.jawabufarmermaster'),
        ),
        migrations.AddField(
            model_name='jawabuapprovalrecord',
            name='invalidated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabuapprovalrecord',
            name='payment_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_approval_records', to='core.paymentdocument'),
        ),
        migrations.AddField(
            model_name='jawabuapprovalcondition',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core.jawabuapprovalrecord'),
        ),
        migrations.AddField(
            model_name='jawabumediaaccessevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabumediaaccessevent',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='core.mediaattachment'),
        ),
        migrations.AddField(
            model_name='jawabumediaaccessevent',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_access_events', to='core.jawabufarmermaster'),
        ),
        migrations.AddIndex(
            model_name='jawabuapprovaldelegation',
            index=models.Index(fields=['delegate', 'gate', 'expires_at'], name='core_jawabu_delegat_0f36e9_idx'),
        ),
        migrations.AddIndex(
            model_name='jawabuapprovalrecord',
            index=models.Index(fields=['farmer', 'gate', 'status'], name='core_jawabu_farmer__f32a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='jawabuapprovalrecord',
            index=models.Index(fields=['payment_document', 'gate', 'status'], name='core_jawabu_payment_bccca5_idx'),
        ),
        migrations.AddIndex(
            model_name='jawabumediaaccessevent',
            index=models.Index(fields=['farmer', 'created_at'], name='core_jawabu_farmer__053e27_idx'),
        ),
        migrations.RunPython(
            seed_approval_controls_capability,
            unseed_approval_controls_capability,
        ),
    ]
