# Generated by Django 5.1.6 on 2026-07-30 07:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_jawabuapprovalcondition_jawabuapprovaldelegation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetRegisterContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_key', models.CharField(max_length=80)),
                ('sheet_name', models.CharField(max_length=255)),
                ('publication_mode', models.CharField(choices=[('publication_only', 'Django publication only')], default='publication_only', max_length=32)),
                ('subject_type', models.CharField(choices=[('none', 'No row-level subject audit'), ('tat_tracker_case', 'TAT tracker case')], default='none', max_length=32)),
                ('header_row', models.PositiveIntegerField(default=1)),
                ('data_start_row', models.PositiveIntegerField(default=2)),
                ('row_key_header', models.CharField(blank=True, default='', max_length=255)),
                ('expected_headers', models.JSONField(blank=True, default=list)),
                ('field_ownership', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_register_contracts', to='core.groupsheetconfiguration')),
            ],
            options={
                'verbose_name': 'Sheet register contract',
                'verbose_name_plural': 'Sheet register contracts',
                'ordering': ['group_configuration__group_id', 'register_key'],
            },
        ),
        migrations.CreateModel(
            name='SheetSyncAuditSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('schema_drift', 'Schema drift'), ('divergence', 'Divergence found'), ('unavailable', 'Unavailable')], db_index=True, max_length=32)),
                ('expected_header_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('actual_header_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('missing_headers', models.JSONField(blank=True, default=list)),
                ('duplicate_headers', models.JSONField(blank=True, default=list)),
                ('reordered_headers', models.BooleanField(default=False)),
                ('rows_checked', models.PositiveIntegerField(default=0)),
                ('discrepancy_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error', models.TextField(blank=True, default='')),
                ('checked_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_snapshots', to='core.sheetregistercontract')),
            ],
            options={
                'verbose_name': 'Sheet sync audit snapshot',
                'verbose_name_plural': 'Sheet sync audit snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetSyncDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('field_name', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(choices=[('missing_row', 'Django record missing from Sheet'), ('orphan_row', 'Sheet row has no Django record'), ('duplicate_row_key', 'Duplicate Sheet row key'), ('row_pointer_mismatch', 'Stored row pointer mismatch'), ('field_value_mismatch', 'Backend-owned field differs')], db_index=True, max_length=48)),
                ('expected_value_hash', models.CharField(blank=True, default='', max_length=64)),
                ('actual_value_hash', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='core.sheetsyncauditsnapshot')),
            ],
            options={
                'verbose_name': 'Sheet sync discrepancy',
                'verbose_name_plural': 'Sheet sync discrepancies',
                'ordering': ['kind', 'record_key', 'field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='sheetregistercontract',
            index=models.Index(fields=['enabled', 'subject_type'], name='core_sheetr_enabled_114a77_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheetregistercontract',
            constraint=models.UniqueConstraint(fields=('group_configuration', 'register_key'), name='unique_sheet_register_contract_per_group'),
        ),
        migrations.AddIndex(
            model_name='sheetsyncauditsnapshot',
            index=models.Index(fields=['contract', 'created_at'], name='core_sheets_contrac_41c9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetsyncauditsnapshot',
            index=models.Index(fields=['status', 'created_at'], name='core_sheets_status_8768bc_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetsyncdiscrepancy',
            index=models.Index(fields=['snapshot', 'kind'], name='core_sheets_snapsho_9500ab_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetsyncdiscrepancy',
            index=models.Index(fields=['record_key', 'kind'], name='core_sheets_record__282b5d_idx'),
        ),
    ]
