# Generated by Django 5.1.6 on 2026-07-30 09:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_compliance_audit_chain(apps, schema_editor):
    apps.get_model('core', 'ComplianceAuditChainState').objects.get_or_create(singleton=1)


def unseed_compliance_audit_chain(apps, schema_editor):
    apps.get_model('core', 'ComplianceAuditChainState').objects.filter(singleton=1).delete()


def create_postgres_audit_immutability(apps, schema_editor):
    """Reject mutation even when code bypasses Django model methods.

    This protects the application database role. A PostgreSQL owner can still
    alter database objects, so daily external checkpoints remain necessary
    tamper-evidence rather than an inaccurate claim of absolute immutability.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION core_prevent_compliance_audit_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'Compliance audit events are append-only';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    schema_editor.execute(
        """

        CREATE TRIGGER core_compliance_audit_event_immutable
        BEFORE UPDATE OR DELETE ON core_complianceauditevent
        FOR EACH ROW EXECUTE FUNCTION core_prevent_compliance_audit_mutation();
        """
    )


def remove_postgres_audit_immutability(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute('DROP TRIGGER IF EXISTS core_compliance_audit_event_immutable ON core_complianceauditevent;')
    schema_editor.execute('DROP FUNCTION IF EXISTS core_prevent_compliance_audit_mutation();')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_sheet_register_governance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAuditChainState',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_position', models.PositiveBigIntegerField(default=0)),
                ('last_hash', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'compliance audit chain state',
                'verbose_name_plural': 'compliance audit chain state',
            },
        ),
        migrations.CreateModel(
            name='ComplianceAuditCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_date', models.DateField(db_index=True, unique=True)),
                ('chain_position', models.PositiveBigIntegerField(default=0)),
                ('chain_hash', models.CharField(blank=True, default='', max_length=64)),
                ('event_count', models.PositiveBigIntegerField(default=0)),
                ('recipient_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('disabled', 'Delivery disabled'), ('pending', 'Ready to deliver'), ('sent', 'Delivered'), ('failed', 'Delivery failed')], db_index=True, default='disabled', max_length=24)),
                ('delivery_attempts', models.PositiveIntegerField(default=0)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'compliance audit checkpoint',
                'verbose_name_plural': 'compliance audit checkpoints',
                'ordering': ['-checkpoint_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('portal', 'Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin', 'SPIN / CRB'), ('access_control', 'Access control')], db_index=True, max_length=40)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(db_index=True, default='workflow', max_length=40)),
                ('origin', models.CharField(choices=[('human', 'Human action'), ('system', 'System automation'), ('external_sync', 'External synchronization')], db_index=True, default='human', max_length=24)),
                ('subject_type', models.CharField(db_index=True, max_length=80)),
                ('subject_id', models.CharField(db_index=True, max_length=128)),
                ('customer_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('authority_label', models.CharField(blank=True, default='', max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('source_model', models.CharField(blank=True, default='', max_length=120)),
                ('source_event_id', models.CharField(blank=True, default='', max_length=160)),
                ('deduplication_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('before_values', models.JSONField(blank=True, default=dict)),
                ('after_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sensitive', models.BooleanField(db_index=True, default=False)),
                ('retention_class', models.CharField(choices=[('legal_hold', 'Legal hold - no automatic purge')], db_index=True, default='legal_hold', max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chain_position', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('previous_hash', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('payload_hash', models.CharField(editable=False, max_length=64)),
                ('integrity_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('authority_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_audit_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'compliance audit event',
                'verbose_name_plural': 'compliance audit events',
                'ordering': ['-chain_position'],
                'permissions': [('export_complianceauditevent', 'Can export compliance audit evidence'), ('verify_complianceauditevent', 'Can verify compliance audit integrity')],
                'indexes': [models.Index(fields=['workflow', 'occurred_at'], name='core_compli_workflo_2aaf73_idx'), models.Index(fields=['subject_type', 'subject_id', 'occurred_at'], name='core_compli_subject_ab22f9_idx'), models.Index(fields=['actor', 'occurred_at'], name='core_compli_actor_i_3a02e1_idx'), models.Index(fields=['action', 'occurred_at'], name='core_compli_action_ce2c94_idx'), models.Index(fields=['sensitive', 'occurred_at'], name='core_compli_sensiti_cb186b_idx')],
            },
        ),
        migrations.RunPython(seed_compliance_audit_chain, unseed_compliance_audit_chain),
        migrations.RunPython(create_postgres_audit_immutability, remove_postgres_audit_immutability),
    ]
