# Generated by Django 5.1.6 on 2026-07-30 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_complianceauditchainstate_complianceauditcheckpoint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCircuitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('half_open', 'Half open')], db_index=True, default='closed', max_length=16)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('failure_window_started_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('next_probe_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'integration circuit state',
                'verbose_name_plural': 'integration circuit states',
            },
        ),
        migrations.CreateModel(
            name='IntegrationOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration', models.CharField(choices=[('google_sheets', 'Google Sheets'), ('google_drive', 'Google Drive'), ('telegram', 'Telegram')], db_index=True, max_length=32)),
                ('operation_type', models.CharField(db_index=True, max_length=80)),
                ('deduplication_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source_model', models.CharField(blank=True, default='', max_length=120)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('requested_by_label', models.CharField(blank=True, default='', max_length=255)),
                ('payload_digest', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('retryable_failure', 'Retryable failure'), ('dead_letter', 'Dead letter')], db_index=True, default='pending', max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'integration operation',
                'verbose_name_plural': 'integration operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', 'status', 'updated_at'], name='core_integr_integra_12ee4a_idx'), models.Index(fields=['source_model', 'source_id', 'created_at'], name='core_integr_source__17544e_idx'), models.Index(fields=['request_id', 'created_at'], name='core_integr_request_ccbd7e_idx')],
            },
        ),
    ]
