# Generated by Django 5.1.6 on 2026-07-30 11:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_integrationcircuitstate_integrationoperation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tattrackercase',
            name='stage_target_snapshots',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TatEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_percent', models.PositiveSmallIntegerField()),
                ('routing_role', models.CharField(choices=[('RESPONSIBLE_ROLE', 'Responsible role'), ('BRANCH_MANAGER', 'Branch manager'), ('MANAGEMENT', 'Management')], max_length=80)),
                ('branch', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('approved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tat_escalation_rules', to=settings.AUTH_USER_MODEL)),
                ('group_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tat_escalation_rules', to='core.groupsheetconfiguration')),
            ],
            options={
                'ordering': ['branch', 'threshold_percent', '-approved_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('group_configuration', 'branch', 'threshold_percent'), name='unique_active_tat_escalation_rule')],
            },
        ),
        migrations.CreateModel(
            name='UserMiniAppPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40)),
                ('default_screen', models.CharField(blank=True, default='', max_length=80)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('compact_cards', models.BooleanField(default=False)),
                ('alert_mode', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily digest'), ('quiet', 'Quiet')], default='immediate', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniapp_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workflow', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'workflow'), name='unique_user_miniapp_preference')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfigurationChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('tat_tracker', 'TAT Tracker')], db_index=True, default='tat_tracker', max_length=40)),
                ('setting_key', models.CharField(choices=[('tat_targets', 'TAT targets'), ('business_calendar', 'Business calendar'), ('tat_escalation', 'TAT escalation rules')], db_index=True, max_length=40)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('proposed_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('group_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_configuration_requests', to='core.groupsheetconfiguration')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_workflow_configuration_changes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_workflow_configuration_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['workflow', 'setting_key', 'status', 'requested_at'], name='core_workfl_workflo_e32b4b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('requested_by', 'request_id'), name='unique_workflow_config_request_id')],
            },
        ),
    ]
