# Generated by Django 5.1.6 on 2026-07-30 11:40

from django.db import migrations


def seed_open_stage_targets(apps, schema_editor):
    """Freeze the currently active target for open stages at feature rollout."""
    GroupSheetConfiguration = apps.get_model('core', 'GroupSheetConfiguration')
    TatTrackerCase = apps.get_model('core', 'TatTrackerCase')
    from core.services.tat_tracker import product_by_key, stage_target_minutes

    workflows = {
        str(row.group_id): (row.workflow or {})
        for row in GroupSheetConfiguration.objects.all().only('group_id', 'workflow')
    }
    for case in TatTrackerCase.objects.filter(is_deleted=False, status='Active').iterator():
        workflow = workflows.get(str(case.group_id))
        if workflow is None:
            continue
        try:
            product = product_by_key(case.product_key)
        except ValueError:
            continue
        stage = next((item for item in product.stages if item.key == case.current_stage), None)
        if not stage:
            stage = next((item for item in product.stages if not (case.stage_values or {}).get(item.key)), None)
        if not stage:
            continue
        snapshots = dict(case.stage_target_snapshots or {})
        if stage.key in snapshots:
            continue
        target = stage_target_minutes(workflow, product, stage)
        if target is None:
            continue
        snapshots[stage.key] = {
            'target_minutes': str(target),
            'settings_version': int(workflow.get('settings_version') or 1),
            'started_at': '',
        }
        case.stage_target_snapshots = snapshots
        case.save(update_fields=['stage_target_snapshots'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_tattrackercase_stage_target_snapshots_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_open_stage_targets, migrations.RunPython.noop),
    ]
