# Generated by Django 5.1.6 on 2026-07-30

"""Separate workflow Business Administrator from Django technical administration.

Only effective access/policy rows are renamed.  Historical approval and audit
records intentionally retain their original ``ADMIN`` evidence label.
"""

from django.db import migrations, models


WORKFLOWS = ('jawabu_portal', 'tat_tracker', 'spin_credit_analysis')
LEGACY_ROLE = 'ADMIN'
BUSINESS_ROLE = 'BUSINESS_ADMIN'


def _assert_no_forward_collisions(apps):
    AccessGrant = apps.get_model('core', 'AccessGrant')
    for grant in AccessGrant.objects.filter(workflow__in=WORKFLOWS, role=LEGACY_ROLE).iterator():
        if AccessGrant.objects.filter(
            user_id=grant.user_id,
            workflow=grant.workflow,
            role=BUSINESS_ROLE,
            branch=grant.branch,
            product=grant.product,
            group_configuration_id=grant.group_configuration_id,
        ).exists():
            raise RuntimeError(
                'Cannot rename legacy ADMIN access: a matching BUSINESS_ADMIN grant already exists. '
                'Run check_business_admin_cutover --strict and resolve the collision first.'
            )


def _assert_no_reverse_collisions(apps):
    AccessGrant = apps.get_model('core', 'AccessGrant')
    for grant in AccessGrant.objects.filter(workflow__in=WORKFLOWS, role=BUSINESS_ROLE).iterator():
        if AccessGrant.objects.filter(
            user_id=grant.user_id,
            workflow=grant.workflow,
            role=LEGACY_ROLE,
            branch=grant.branch,
            product=grant.product,
            group_configuration_id=grant.group_configuration_id,
        ).exists():
            raise RuntimeError('Cannot reverse Business Administrator role cutover because a matching legacy ADMIN grant exists.')


def _merge_capability_rows(Capability, *, source_role, target_role):
    """Preserve the existing effective policy when seed rows overlap."""
    for row in Capability.objects.filter(workflow__in=WORKFLOWS, role=source_role).iterator():
        target = Capability.objects.filter(
            workflow=row.workflow,
            role=target_role,
            capability_key=row.capability_key,
        ).first()
        if target:
            target.effect = row.effect
            target.enabled = row.enabled
            target.save(update_fields=['effect', 'enabled', 'updated_at'])
            row.delete()
            continue
        row.role = target_role
        row.save(update_fields=['role', 'updated_at'])


def rename_effective_roles_forward(apps, schema_editor):
    _assert_no_forward_collisions(apps)
    AccessGrant = apps.get_model('core', 'AccessGrant')
    EmergencyAccessGrant = apps.get_model('core', 'EmergencyAccessGrant')
    WorkflowRoleCapability = apps.get_model('core', 'WorkflowRoleCapability')
    DocumentSignoffPolicy = apps.get_model('core', 'DocumentSignoffPolicy')
    for model in (AccessGrant, EmergencyAccessGrant):
        model.objects.filter(workflow__in=WORKFLOWS, role=LEGACY_ROLE).update(role=BUSINESS_ROLE)
    _merge_capability_rows(WorkflowRoleCapability, source_role=LEGACY_ROLE, target_role=BUSINESS_ROLE)
    DocumentSignoffPolicy.objects.filter(workflow='jawabu_portal', approval_role=LEGACY_ROLE).update(approval_role=BUSINESS_ROLE)


def rename_effective_roles_backward(apps, schema_editor):
    _assert_no_reverse_collisions(apps)
    AccessGrant = apps.get_model('core', 'AccessGrant')
    EmergencyAccessGrant = apps.get_model('core', 'EmergencyAccessGrant')
    WorkflowRoleCapability = apps.get_model('core', 'WorkflowRoleCapability')
    DocumentSignoffPolicy = apps.get_model('core', 'DocumentSignoffPolicy')
    for model in (AccessGrant, EmergencyAccessGrant):
        model.objects.filter(workflow__in=WORKFLOWS, role=BUSINESS_ROLE).update(role=LEGACY_ROLE)
    _merge_capability_rows(WorkflowRoleCapability, source_role=BUSINESS_ROLE, target_role=LEGACY_ROLE)
    DocumentSignoffPolicy.objects.filter(workflow='jawabu_portal', approval_role=BUSINESS_ROLE).update(approval_role=LEGACY_ROLE)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_repair_tat_stage_target_snapshot_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabuapprovaldelegation',
            name='source_role',
            field=models.CharField(default='BUSINESS_ADMIN', max_length=80),
        ),
        migrations.RunPython(rename_effective_roles_forward, rename_effective_roles_backward),
    ]
