# Generated by Django 5.1.6 on 2026-07-30 15:00

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # Reverse migration drops only these two private workspace metadata tables.
    # It must never modify JawabuFarmerMaster, workflow, financial, or audit
    # tables; the FK cascade here is only from a case/user deletion forward.

    dependencies = [
        ('core', '0088_business_admin_role_cutover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalCaseWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('recent_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('unavailable_since', models.DateTimeField(blank=True, null=True)),
                ('last_open_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_workspace_items', to='core.jawabufarmermaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_case_workspace_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-pinned_at', '-last_opened_at'],
                'indexes': [models.Index(fields=['user', 'pinned', 'unavailable_since'], name='core_portal_user_id_e45d21_idx'), models.Index(fields=['user', 'last_opened_at'], name='core_portal_user_id_d30e7d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'farmer'), name='unique_portal_case_workspace_per_user')],
            },
        ),
        migrations.CreateModel(
            name='PortalSavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('screen', models.CharField(max_length=80)),
                ('queue', models.CharField(blank=True, default='', max_length=80)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('ordering', models.CharField(choices=[('queue_default', 'Queue default'), ('newest', 'Newest first')], default='queue_default', max_length=24)),
                ('is_startup', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_startup', '-last_used_at', '-updated_at', 'name'],
                'indexes': [models.Index(fields=['user', 'is_startup'], name='core_portal_user_id_5d962c_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='unique_portal_saved_view_name_per_user'), models.UniqueConstraint(condition=models.Q(('is_startup', True)), fields=('user',), name='unique_portal_saved_startup_view_per_user')],
            },
        ),
    ]
