# Generated by Django 5.1.6 on 2026-07-31 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


LEGACY_APPROVER_GROUP = 'Access Policy Approvers'


def backfill_legacy_approver_group(apps, schema_editor):
    """Preserve existing checker authority while moving away from Group writes."""
    Group = apps.get_model('auth', 'Group')
    Assignment = apps.get_model('core', 'AccessControlCheckerAssignment')
    group = Group.objects.filter(name=LEGACY_APPROVER_GROUP).first()
    if group is None:
        return
    for user in group.user_set.filter(is_active=True).order_by('pk').iterator():
        if Assignment.objects.filter(user_id=user.pk, revoked_at__isnull=True).exists():
            continue
        Assignment.objects.create(
            user_id=user.pk,
            appointment_reason=(
                'Backfilled from the legacy Access Policy Approvers Django group '
                'during the audited checker-authority cutover.'
            ),
            source='legacy_group_backfill',
        )


class Migration(migrations.Migration):
    # To undo: export checker-appointment evidence, then migrate to core.0089.
    # Reverse drops only this new checker-appointment table; it never changes
    # staff identities, Access Grants, workflow state, financial data, or the
    # append-only compliance ledger. Do not reverse a production release
    # before preserving the appointment/revocation evidence externally.

    dependencies = [
        ('core', '0089_portalcaseworkspace_portalsavedview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControlCheckerAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_reason', models.TextField()),
                ('source', models.CharField(choices=[('bootstrap_override', 'Bootstrap override'), ('superuser_appointment', 'Superuser appointment'), ('legacy_group_backfill', 'Legacy approver-group backfill')], default='superuser_appointment', max_length=32)),
                ('appointed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('appointed_by', models.ForeignKey(blank=True, help_text='Blank only for an evidence-preserving legacy group backfill.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointed_access_control_checkers', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_access_control_checkers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_control_checker_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access control checker',
                'verbose_name_plural': 'access control checkers',
                'ordering': ['-appointed_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='core_access_user_id_c5377f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user',), name='unique_active_access_control_checker')],
            },
        ),
        migrations.RunPython(backfill_legacy_approver_group, migrations.RunPython.noop),
    ]
