# Generated by Django 5.1.6 on 2026-07-31 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


IT_CAPABILITIES = (
    ('jawabu_portal', 'IT', 'portal.health.read'),
    ('jawabu_portal', 'IT', 'portal.health.maintenance.manage'),
)


def _snapshot_state(Capability, Grant):
    grants = []
    for row in Grant.objects.order_by(
        'user_id', 'workflow', 'role', 'branch', 'product',
    ).values(
        'id', 'user_id', 'workflow', 'role', 'branch', 'product',
        'group_configuration_id', 'active', 'source',
    ):
        row['id'] = str(row['id'])
        grants.append(row)
    return {
        'capabilities': list(Capability.objects.order_by(
            'workflow', 'role', 'capability_key',
        ).values('workflow', 'role', 'capability_key', 'effect')),
        'grants': grants,
    }


def seed_it_portal_maintenance_access(apps, schema_editor):
    """Seed only missing IT support capabilities and preserve explicit denies."""
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    PolicyState = apps.get_model('core', 'AccessControlPolicyState')
    Snapshot = apps.get_model('core', 'AccessControlPolicySnapshot')
    CapabilityAudit = apps.get_model('core', 'WorkflowRoleCapabilityAuditEvent')
    Grant = apps.get_model('core', 'AccessGrant')

    created = []
    for workflow, role, capability_key in IT_CAPABILITIES:
        row, was_created = Capability.objects.get_or_create(
            workflow=workflow,
            role=role,
            capability_key=capability_key,
            defaults={'enabled': True, 'effect': 'allow'},
        )
        if was_created:
            created.append({
                'workflow': workflow,
                'role': role,
                'capability_key': capability_key,
                'effect': row.effect,
            })
    if not created:
        return

    state, _created = PolicyState.objects.get_or_create(singleton=1, defaults={'version': 1})
    state.version += 1
    state.save(update_fields=['version', 'updated_at'])
    Snapshot.objects.get_or_create(
        version=state.version,
        defaults={'state': _snapshot_state(Capability, Grant)},
    )
    policy_audit = CapabilityAudit.objects.create(
        workflow='jawabu_portal',
        role='IT',
        actor=None,
        source='system_migration',
        changes={
            'reason': 'IT-only Portal readiness and maintenance control.',
            'created_capabilities': created,
            'policy_version': state.version,
        },
    )

    # Policy versioning makes active Mini Apps refresh capability metadata on
    # their next navigation rather than retaining a stale client-side set.
    from core.services.compliance_audit import record_event

    record_event(
        workflow='access_control',
        action='access_control.portal_maintenance.it_seeded',
        category='authorization',
        origin='system',
        subject_type='workflow_role_capability',
        subject_id='jawabu_portal:IT:portal.health.maintenance.manage',
        deduplication_key='migration:core:0092:portal-maintenance-it-seeded',
        source_model='WorkflowRoleCapabilityAuditEvent',
        source_event_id=str(policy_audit.pk),
        before_values={},
        after_values={'created_capabilities': created, 'policy_version': state.version},
        metadata={'migration': '0092_portal_maintenance_state'},
        sensitive=True,
    )


class Migration(migrations.Migration):

    # To undo: python manage.py migrate core 0091_pause_portal_workspace_to_it
    # This reverse removes only the maintenance-state table. Policy and
    # compliance evidence deliberately remain append-only, and no case,
    # customer, document, payment, or Sheet data is touched.

    dependencies = [
        ('core', '0091_pause_portal_workspace_to_it'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMaintenanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('maintenance', 'Under maintenance')], db_index=True, default='live', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal maintenance state',
                'verbose_name_plural': 'Portal maintenance state',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton', 1)), name='portal_maintenance_singleton_one')],
            },
        ),
        migrations.RunPython(seed_it_portal_maintenance_access, migrations.RunPython.noop),
    ]
