# Generated by Django 5.1.6 on 2026-07-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_portal_maintenance_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbatch',
            name='generation_request_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Mini App retry key for the committed requisition generation.', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='requisitionbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_request_id', ''), _negated=True), fields=('generation_request_id',), name='unique_requisition_batch_generation_request'),
        ),
    ]
