# Generated by Django 5.1.6 on 2026-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_requisition_publication_retry_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jawabuapprovalrecord',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('returned_for_rework', 'Returned for rework')], max_length=40),
        ),
        migrations.AlterField(
            model_name='jawabufarmermaster',
            name='credit_decision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('Exemption Approved', 'Exemption Approved'), ('Pending', 'Pending')], db_index=True, default='Pending', help_text='Credit Analysis decision from master data dropdown.', max_length=80),
        ),
        migrations.AlterField(
            model_name='jawabufarmermaster',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deferred', 'Deferred'), ('Under Review', 'Under Review')], db_index=True, default='', help_text='Head of Rural final decision. Approved records are ready for order batching.', max_length=80),
        ),
    ]
