# Generated by Django 5.1.6 on 2026-08-03 06:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_jawabuapprovalrecord_decision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JawabuCaseComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_key', models.CharField(db_index=True, max_length=40)),
                ('comment', models.TextField()),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('role_code', models.CharField(blank=True, default='', max_length=64)),
                ('role_label', models.CharField(blank=True, default='', max_length=128)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jawabu_case_comments', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_comments', to='core.jawabufarmermaster')),
                ('pipeline_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_comments', to='core.jawabupipelineevent')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
                'indexes': [models.Index(fields=['farmer', 'occurred_at'], name='jawabu_comment_timeline_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('comment', ''), _negated=True), name='jawabu_case_comment_not_empty'), models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('farmer', 'request_id'), name='jawabu_unique_comment_request')],
            },
        ),
    ]
