# Generated by Django 5.1.6 on 2026-08-03 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


IMPORT_CAPABILITY = ('jawabu_portal', 'IT', 'portal.imports.view')


def _snapshot_state(Capability, Grant):
    grants = []
    for row in Grant.objects.order_by(
        'user_id', 'workflow', 'role', 'branch', 'product',
    ).values(
        'id', 'user_id', 'workflow', 'role', 'branch', 'product',
        'group_configuration_id', 'active', 'source',
    ):
        row['id'] = str(row['id'])
        grants.append(row)
    return {
        'capabilities': list(Capability.objects.order_by(
            'workflow', 'role', 'capability_key',
        ).values('workflow', 'role', 'capability_key', 'effect')),
        'grants': grants,
    }


def seed_it_import_review_capability(apps, schema_editor):
    """Seed only missing IT review access; preserve every explicit policy choice."""
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    PolicyState = apps.get_model('core', 'AccessControlPolicyState')
    Snapshot = apps.get_model('core', 'AccessControlPolicySnapshot')
    CapabilityAudit = apps.get_model('core', 'WorkflowRoleCapabilityAuditEvent')
    Grant = apps.get_model('core', 'AccessGrant')

    workflow, role, capability_key = IMPORT_CAPABILITY
    row, created = Capability.objects.get_or_create(
        workflow=workflow,
        role=role,
        capability_key=capability_key,
        defaults={'enabled': True, 'effect': 'allow'},
    )
    if not created:
        return

    state, _created = PolicyState.objects.get_or_create(singleton=1, defaults={'version': 1})
    state.version += 1
    state.save(update_fields=['version', 'updated_at'])
    Snapshot.objects.get_or_create(
        version=state.version,
        defaults={'state': _snapshot_state(Capability, Grant)},
    )
    policy_audit = CapabilityAudit.objects.create(
        workflow=workflow,
        role=role,
        actor=None,
        source='system_migration',
        changes={
            'reason': 'IT-only Portal import staging and review.',
            'created_capabilities': [{'workflow': workflow, 'role': role, 'capability_key': capability_key, 'effect': row.effect}],
            'policy_version': state.version,
        },
    )
    from core.services.compliance_audit import record_event

    record_event(
        workflow='access_control',
        action='access_control.portal_imports.it_seeded',
        category='authorization',
        origin='system',
        subject_type='workflow_role_capability',
        subject_id='jawabu_portal:IT:portal.imports.view',
        deduplication_key='migration:core:0096:portal-imports-it-seeded',
        source_model='WorkflowRoleCapabilityAuditEvent',
        source_event_id=str(policy_audit.pk),
        before_values={},
        after_values={'created_capabilities': [capability_key], 'policy_version': state.version},
        metadata={'migration': '0096_portal_import_archives'},
        sensitive=True,
    )


class Migration(migrations.Migration):

    # To undo: python manage.py migrate core 0095_jawabucasecomment
    # This removes only the archival metadata and source payload fields. It
    # never changes customers, cases, orders, payments, Drive files, or the
    # append-only policy/compliance evidence created by the seed below.

    dependencies = [
        ('core', '0095_jawabucasecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='archive_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='archive_file_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='archive_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='archive_next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='archive_sync_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='archive_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jawabu_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='source_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='source_content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='source_mime_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='source_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='upload_request_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='jawabufarmeruploadbatch',
            index=models.Index(fields=['archive_next_retry_at'], name='core_jawabu_archive_ec982a_idx'),
        ),
        migrations.RunPython(seed_it_import_review_capability, migrations.RunPython.noop),
    ]
