# Generated by Django 5.1.6 on 2026-08-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_portal_import_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignoffpolicy',
            name='approval_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
