# Generated by Django 5.1.6 on 2026-08-03 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


REPORT_CAPABILITIES = ('portal.reports.view', 'portal.reports.manage')
PORTAL_ROLES = (
    'JBL_OFFICER', 'CREDIT_ANALYST', 'HB_STAFF', 'OPERATIONS_ADMIN', 'IT',
    'BUSINESS_ADMIN',
)


def _policy_snapshot(Capability, Grant):
    """Keep the matrix versioned without querying or changing customer data."""
    return {
        'capabilities': list(Capability.objects.order_by(
            'workflow', 'role', 'capability_key',
        ).values('workflow', 'role', 'capability_key', 'effect')),
        'grants': [
            {
                **row,
                'id': str(row['id']),
            }
            for row in Grant.objects.order_by(
                'user_id', 'workflow', 'role', 'branch', 'product',
            ).values('id', 'user_id', 'workflow', 'role', 'branch', 'product', 'group_configuration_id', 'active', 'source')
        ],
    }


def seed_portal_reporting_capabilities(apps, schema_editor):
    """Seed the approved IT-only reporting policy with durable evidence."""
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    CapabilityAudit = apps.get_model('core', 'WorkflowRoleCapabilityAuditEvent')
    PolicyState = apps.get_model('core', 'AccessControlPolicyState')
    Snapshot = apps.get_model('core', 'AccessControlPolicySnapshot')
    Grant = apps.get_model('core', 'AccessGrant')

    changed = []
    for role in PORTAL_ROLES:
        before = {
            row['capability_key']: row['effect']
            for row in Capability.objects.filter(
                workflow='jawabu_portal', role=role,
                capability_key__in=REPORT_CAPABILITIES,
            ).values('capability_key', 'effect')
        }
        expected = {
            key: ('allow' if role == 'IT' else 'deny')
            for key in REPORT_CAPABILITIES
        }
        for capability_key, effect in expected.items():
            Capability.objects.update_or_create(
                workflow='jawabu_portal', role=role, capability_key=capability_key,
                defaults={'effect': effect, 'enabled': effect == 'allow'},
            )
        if before != expected:
            event = CapabilityAudit.objects.create(
                workflow='jawabu_portal', role=role, actor=None,
                source='system_migration',
                changes={
                    'reason': 'Approved Portal reporting v1: IT-only controlled reporting capability seed.',
                    'before': before,
                    'after': expected,
                },
            )
            changed.append({'role': role, 'audit_event_id': str(event.pk), 'after': expected})

    if not changed:
        return
    policy, _created = PolicyState.objects.get_or_create(singleton=1, defaults={'version': 1})
    policy.version += 1
    policy.save(update_fields=['version', 'updated_at'])
    Snapshot.objects.get_or_create(
        version=policy.version,
        defaults={'state': _policy_snapshot(Capability, Grant)},
    )

    # `record_event` hash-chains the policy seed. It records no customer data
    # and allows later investigation even if a report definition is archived.
    from core.services.compliance_audit import record_event

    record_event(
        workflow='access_control',
        action='access_control.portal_reporting.seeded',
        category='authorization', origin='system',
        subject_type='workflow_role_capability',
        subject_id='jawabu_portal:portal.reports',
        deduplication_key='migration:core:0099:portal-reporting-capabilities',
        source_model='WorkflowRoleCapabilityAuditEvent',
        source_event_id=str(changed[0]['audit_event_id']),
        before_values={},
        after_values={'changed_roles': changed, 'policy_version': policy.version},
        metadata={'migration': '0099_portal_reporting'},
        sensitive=True,
    )


class Migration(migrations.Migration):
    # Accepted for merge/local validation only. Production application needs
    # explicit release approval. To undo a non-production apply:
    #   python manage.py migrate core 0098_portal_role_separation
    # That drops only report-definition/chart tables. The reverse seed is a
    # no-op so matrix and compliance evidence remain append-only; it never
    # changes cases, Access Grants, documents, financial data, or Drive/Sheet data.

    dependencies = [
        ('core', '0098_portal_role_separation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('source_key', models.CharField(choices=[('portal_cases', 'Portal customer cases')], default='portal_cases', max_length=40)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('create_request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_portal_report_definitions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portal_report_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portal report definition',
                'verbose_name_plural': 'Portal report definitions',
                'ordering': ['-is_active', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PortalReportChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar chart'), ('doughnut', 'Doughnut chart'), ('line', 'Line chart')], max_length=16)),
                ('dimension_field', models.CharField(max_length=80)),
                ('metric_field', models.CharField(blank=True, default='', max_length=80)),
                ('aggregation', models.CharField(choices=[('count', 'Count cases'), ('sum', 'Sum'), ('average', 'Average')], default='count', max_length=16)),
                ('date_bucket', models.CharField(blank=True, choices=[('', 'No date bucket'), ('day', 'Day'), ('month', 'Month')], default='', max_length=12)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='core.portalreportdefinition')),
            ],
            options={
                'verbose_name': 'Portal report chart',
                'verbose_name_plural': 'Portal report charts',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portalreportdefinition',
            index=models.Index(fields=['is_active', 'title'], name='core_portal_is_acti_edc73f_idx'),
        ),
        migrations.AddIndex(
            model_name='portalreportdefinition',
            index=models.Index(fields=['created_by', 'created_at'], name='core_portal_created_b6ff92_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalreportdefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('create_request_id', ''), _negated=True), fields=('create_request_id',), name='unique_portal_report_create_request'),
        ),
        migrations.AddConstraint(
            model_name='portalreportchart',
            constraint=models.UniqueConstraint(fields=('definition', 'position'), name='unique_portal_report_chart_position'),
        ),
        migrations.RunPython(seed_portal_reporting_capabilities, migrations.RunPython.noop),
    ]
