# Generated by Django 5.1.6 on 2026-08-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    # Accepted for merge/local validation only. Production application needs
    # explicit release approval. To undo a non-production apply:
    #   python manage.py migrate core 0099_portal_reporting
    # The reverse removes only Portal working-list archive metadata/indexes.
    # It never deletes staged source data, Drive files, customer records,
    # report definitions, workflow events, or compliance audit evidence.

    dependencies = [
        ('core', '0099_portal_reporting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='is_portal_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='portal_archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jawabufarmeruploadbatch',
            name='portal_archived_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='archived_portal_import_batches',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='jawabufarmeruploadbatch',
            index=models.Index(
                fields=['is_portal_archived', 'group_id', 'created_at'],
                name='core_jawabu_is_port_6d09e3_idx',
            ),
        ),
    ]
