# Generated by Django 5.1.6 on 2026-08-13 08:22

import django.db.models.deletion
import django.utils.timezone
import re
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


TAT_PRODUCTS = {
    'logbook': ('Logbook', 'TRACKER-LOGBOOK', 'JBL-LB', '50000', '700000', 28, 27, 29),
    'mjengo': ('Mjengo', 'TRACKER-MJENGO', 'JBL-MJ', '10000', '500000', 27, 26, 28),
    'kilimo': ('Kilimo', 'TRACKER-KILIMO', 'JBL-KI', '50000', '300000', 27, 26, 28),
    'micro_asset': ('Micro Asset', 'TRACKER-MICRO-ASSET', 'JBL-MA', '10000', '300000', 27, 26, 28),
    'business': ('Business', 'TRACKER-Business', 'JBL-BS', '5000', None, 20, 19, 21),
}

SPIN_PRODUCTS = (
    'Kilimo Biashara', 'Asset Finance', 'Boda Boda Plus', 'Boda Boda',
    'Maendeleo', 'Daraja', 'Msingi', 'Digital', 'Fedha Chap Chap', 'Inua',
    'Partnership', 'Flex', 'Biashara',
)

SPIN_ALIASES = {
    'asset finance': 'Asset Finance',
    'boda boda plus': 'Boda Boda Plus',
    'boda boda': 'Boda Boda',
    'kilimo biashara': 'Kilimo Biashara',
    'log book': 'Logbook',
    'micro-asset': 'Micro Asset',
    'micro asset': 'Micro Asset',
    'microasset': 'Micro Asset',
    'daranja': 'Daraja',
}


def _normalized(value):
    return re.sub(r'[^a-z0-9]+', '_', str(value or '').casefold()).strip('_')


def _version_snapshot(version, product):
    return {
        'product_id': product.pk,
        'product_code': product.code,
        'product_name': product.name,
        'version_id': str(version.pk),
        'version': version.version,
        'currency': version.currency,
        'min_amount': str(version.min_amount),
        'max_amount': str(version.max_amount) if version.max_amount is not None else '',
        'min_tenor': version.min_tenor,
        'max_tenor': version.max_tenor,
        'tenor_unit': version.tenor_unit,
        'interest_method': version.interest_method,
        'interest_rate': str(version.interest_rate),
        'interest_rate_period': version.interest_rate_period,
        'repayment_frequency': version.repayment_frequency,
        'quote_amount_field_key': version.quote_amount_field_key,
        'quote_tenor_field_key': version.quote_tenor_field_key,
    }


def backfill_global_products(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    Alias = apps.get_model('core', 'ProductAlias')
    Version = apps.get_model('core', 'ProductVersion')
    TatConfig = apps.get_model('core', 'ProductTatConfiguration')
    MappingIssue = apps.get_model('core', 'ProductMappingIssue')
    OriginationDefinition = apps.get_model('core', 'OriginationProductDefinition')

    used_codes = set()
    for product in Product.objects.order_by('pk'):
        base = _normalized(product.code or product.name) or f'product_{product.pk}'
        code = base
        suffix = 2
        while code in used_codes:
            code = f'{base}_{suffix}'
            suffix += 1
        used_codes.add(code)
        if product.code != code:
            product.code = code
            product.save(update_fields=['code'])
        for raw_alias in (product.name, product.code):
            normalized = _normalized(raw_alias)
            if normalized:
                Alias.objects.get_or_create(
                    normalized_alias=normalized,
                    defaults={'product_id': product.pk, 'alias': raw_alias},
                )

    # Origination-only products did not previously exist in OperationalProduct.
    for definition in OriginationDefinition.objects.all().iterator():
        product = Product.objects.filter(code__iexact=definition.product_key).first()
        if product is None:
            product = Product.objects.create(
                name=definition.name, code=_normalized(definition.product_key), active=True,
                sort_order=Product.objects.count(), category='loan',
            )
        Alias.objects.get_or_create(
            normalized_alias=_normalized(definition.product_key),
            defaults={'product_id': product.pk, 'alias': definition.product_key},
        )

    # Preserve every product spelling historically recognised by the SPIN
    # parser, while moving the authoritative identities into this catalogue.
    for name in SPIN_PRODUCTS:
        code = _normalized(name)
        product = Product.objects.filter(code__iexact=code).first()
        if product is None:
            product = Product.objects.create(
                name=name, code=code, active=True,
                sort_order=Product.objects.count(), category='loan',
            )
        Alias.objects.get_or_create(
            normalized_alias=code,
            defaults={'product_id': product.pk, 'alias': name},
        )
    for raw_alias, product_name in SPIN_ALIASES.items():
        product = Product.objects.filter(name__iexact=product_name).first()
        if product:
            Alias.objects.get_or_create(
                normalized_alias=_normalized(raw_alias),
                defaults={'product_id': product.pk, 'alias': raw_alias},
            )

    today = django.utils.timezone.localdate()
    versions = {}
    for product in Product.objects.all().iterator():
        tat = TAT_PRODUCTS.get(product.code)
        min_amount = Decimal(tat[3]) if tat else Decimal('0')
        max_amount = Decimal(tat[4]) if tat and tat[4] is not None else None
        version, _created = Version.objects.get_or_create(
            product_id=product.pk, version=1,
            defaults={
                'status': 'published', 'currency': 'KES',
                'min_amount': min_amount, 'max_amount': max_amount,
                'min_tenor': 1, 'max_tenor': 120, 'tenor_unit': 'month',
                'interest_method': 'flat', 'interest_rate': Decimal('0'),
                'interest_rate_period': 'annual', 'repayment_frequency': 'monthly',
                'effective_from': today, 'published_at': django.utils.timezone.now(),
            },
        )
        versions[product.code] = version
        if tat:
            stages = []
            if product.code == 'business':
                stage_specs = [
                    ('mpesa_to_admin', 'MPESA sent to Admin', 9, 'BRO'),
                    ('mpesa_verified', 'MPESA verified by Business Admin and sent to CA', 10, 'BUSINESS_ADMIN'),
                    ('ca_analysis_sent', 'Credit analysis sent', 11, 'CA'),
                    ('bro_response', 'BRO response to CA', 12, 'BRO'),
                    ('bm_response', 'BM response to CA', 13, 'BM'),
                    ('bro_applied', 'BRO applied loan on system', 14, 'BRO'),
                    ('disbursement_register', 'Business Admin disbursement register', 15, 'BUSINESS_ADMIN'),
                    ('register_approved', 'Register approved', 17, 'LOAN_APPROVER'),
                    ('disbursement', 'Finance disbursement', 18, 'FINANCE'),
                ]
            else:
                stage_specs = [
                    ('mpesa_to_admin', 'MPESA sent to Admin', 9, 'BRO'),
                    ('mpesa_verified', 'MPESA verified by Business Admin and sent to CA', 10, 'BUSINESS_ADMIN'),
                    ('ca_analysis_sent', 'Credit analysis sent', 11, 'CA'),
                    ('bro_response', 'BRO response to CA', 12, 'BRO'),
                ]
                if product.code == 'logbook':
                    stage_specs.append(('valuation_ready', 'Valuation ready', 13, 'BM'))
                    start = 14
                else:
                    start = 13
                stage_specs.extend([
                    ('bm_tat_request', 'BM TAT request sent', start, 'BM'),
                    ('tat_scheduled', 'HOCC scheduled', start + 1, 'SECRETARY'),
                    ('tat_held', 'HOCC held', start + 2, 'SECRETARY'),
                    ('decision', 'Decision', start + 3, 'CHAIR'),
                    ('minutes_shared', 'Minutes shared', start + 5, 'SECRETARY'),
                    ('sanctions', 'Sanctions', start + 6, 'LOAN_APPROVER'),
                    ('bro_applied', 'BRO applied on system', start + 8, 'BRO'),
                    ('disbursement_register', 'Business Admin disbursement register', start + 9, 'BUSINESS_ADMIN'),
                    ('register_approved', 'Register approved', start + 11, 'LOAN_APPROVER'),
                    ('disbursement', 'Finance disbursement', start + 12, 'FINANCE'),
                ])
            for key, label, column, role in stage_specs:
                dropdowns = {
                    'decision': (['Approved', 'Rejected', 'Deferred'], 'decision_ts'),
                    'minutes_shared': (['Yes', 'No'], 'minutes_shared_ts'),
                    'sanctions': (['Pending', 'Met', 'Not Met'], 'sanctions_ts'),
                    'bro_applied': (['Pending', 'Met', 'Not Met'], 'bro_applied_ts'),
                    'disbursement_register': (['10:00am', '1:00pm', '3:30pm'], 'register_ts'),
                    'register_approved': (['Approved', 'Pending'], 'register_approved_ts'),
                }
                options, timestamp_key = dropdowns.get(key, ([], ''))
                stages.append({
                    'key': key, 'label': label, 'column': column, 'role': role,
                    'kind': 'dropdown' if options else 'timestamp',
                    'options': options, 'auto_timestamp_key': timestamp_key,
                    'requires_signature_certificate': key == 'bm_response',
                })
            if product.code == 'business':
                stage_columns = {'created': 8, 'register_ts': 16}
                tat_column_start = 23
            elif product.code == 'logbook':
                stage_columns = {'created': 8, 'decision_ts': 18, 'sanctions_ts': 21, 'register_ts': 24}
                tat_column_start = 31
            else:
                stage_columns = {'created': 8, 'decision_ts': 17, 'sanctions_ts': 20, 'register_ts': 23}
                tat_column_start = 30
            stage_tat_columns = [
                {
                    'stage_key': item['key'],
                    'fallback_col': tat_column_start + index,
                    'aliases': [
                        f"{item['label']} TAT Minutes",
                        f"{item['label']} TAT",
                        f"{item['label']} Lag",
                        f"{item['label']} Lag Minutes",
                        f"{item['key']} TAT Minutes",
                    ],
                }
                for index, item in enumerate(stages)
            ]
            TatConfig.objects.get_or_create(
                product_version_id=version.pk,
                defaults={
                    'sheet_name': tat[1], 'case_prefix': tat[2],
                    'remarks_col': tat[5], 'status_col': tat[6], 'tat_start_col': tat[7],
                    'stage_columns': stage_columns, 'stages': stages,
                    'stage_tat_columns': stage_tat_columns,
                },
            )

    for definition in OriginationDefinition.objects.all().iterator():
        product = Product.objects.filter(code__iexact=definition.product_key).first()
        version = versions.get(product.code) if product else None
        if version:
            definition.product_version_id = version.pk
            definition.save(update_fields=['product_version'])

    def attach(model_name, raw_field, product_field='product', version_field=None, workflow=''):
        Model = apps.get_model('core', model_name)
        for record in Model.objects.all().iterator():
            raw = getattr(record, raw_field, '')
            normalized = _normalized(raw)
            product = Product.objects.filter(code__iexact=normalized).first()
            if product is None and normalized:
                alias = Alias.objects.filter(normalized_alias=normalized).first()
                product = Product.objects.filter(pk=alias.product_id).first() if alias else None
            if product is None:
                if normalized:
                    MappingIssue.objects.get_or_create(
                        normalized_value=normalized, source_workflow=workflow,
                        source_model=model_name, source_record_id=str(record.pk), status='open',
                        defaults={'raw_value': str(raw)},
                    )
                continue
            update_fields = [product_field]
            setattr(record, f'{product_field}_id', product.pk)
            version = versions.get(product.code)
            if version_field and version:
                setattr(record, f'{version_field}_id', version.pk)
                update_fields.append(version_field)
                if hasattr(record, 'product_terms_snapshot'):
                    record.product_terms_snapshot = _version_snapshot(version, product)
                    update_fields.append('product_terms_snapshot')
            record.save(update_fields=update_fields)

    attach('TatTrackerCase', 'product_key', version_field='product_version', workflow='tat_tracker')
    attach('TatRepairJob', 'product_key', workflow='tat_tracker')
    attach('WorkflowTatDailyMetric', 'product_key', workflow='tat_tracker')
    attach('SpinCreditRequest', 'loan_product', version_field='product_version', workflow='spin_credit_analysis')
    attach('JawabuFarmerMaster', 'payment_product', version_field='product_version', workflow='jawabu_portal')
    attach('AccessGrant', 'product', product_field='product_ref', workflow='access_control')
    attach('EmergencyAccessGrant', 'product', product_field='product_ref', workflow='access_control')
    attach('JawabuApprovalDelegation', 'product', product_field='product_ref', workflow='jawabu_portal')

    Application = apps.get_model('core', 'LoanOriginationApplication')
    for application in Application.objects.select_related('product_definition').all().iterator():
        version_id = application.product_definition.product_version_id
        if version_id:
            application.product_version_id = version_id
            version = Version.objects.get(pk=version_id)
            product = Product.objects.get(pk=version.product_id)
            application.product_terms_snapshot = _version_snapshot(version, product)
            application.save(update_fields=['product_version', 'product_terms_snapshot'])


def reverse_global_product_backfill(apps, schema_editor):
    # Legacy text snapshots are deliberately retained, so schema rollback does
    # not require rewriting operational records.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_origination_multi_product_builder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperationalProduct',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=160)),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('channel', models.CharField(blank=True, choices=[('portal', 'Portal'), ('telegram', 'Telegram'), ('admin', 'Django Admin'), ('import', 'Imports'), ('api', 'API')], db_index=True, default='', max_length=16)),
                ('scope_signature', models.CharField(editable=False, max_length=180)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['product__sort_order', 'product__name', 'workflow', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='ProductCustomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('attribute_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('money', 'Money'), ('date', 'Date'), ('boolean', 'Yes / No'), ('choice', 'Choice')], max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('options', models.JSONField(blank=True, default=list)),
                ('validation_config', models.JSONField(blank=True, default=dict)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('workflow_visibility', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed amount'), ('percentage', 'Percentage')], default='fixed', max_length=16)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('calculation_basis', models.CharField(choices=[('principal', 'Principal'), ('financed_principal', 'Financed principal'), ('interest', 'Interest'), ('principal_interest', 'Principal plus interest')], default='principal', max_length=24)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('collection_mode', models.CharField(choices=[('upfront', 'Upfront'), ('financed', 'Financed')], default='upfront', max_length=16)),
                ('mandatory', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductMappingIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(db_index=True, max_length=160)),
                ('source_workflow', models.CharField(db_index=True, max_length=40)),
                ('source_model', models.CharField(blank=True, default='', max_length=120)),
                ('source_record_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('requirement_type', models.CharField(choices=[('document', 'Document'), ('eligibility', 'Eligibility rule'), ('checkbox', 'Confirmation'), ('amount', 'Amount evidence'), ('text', 'Text evidence')], max_length=20)),
                ('workflow', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('enforcement_stage', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('required', models.BooleanField(default=True)),
                ('validation_config', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductTatConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=160)),
                ('case_prefix', models.CharField(max_length=32)),
                ('remarks_col', models.PositiveSmallIntegerField()),
                ('status_col', models.PositiveSmallIntegerField()),
                ('tat_start_col', models.PositiveSmallIntegerField()),
                ('stage_columns', models.JSONField(default=dict)),
                ('stages', models.JSONField(default=list)),
                ('stage_tat_columns', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='draft', max_length=16)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_tenor', models.PositiveSmallIntegerField(default=1)),
                ('max_tenor', models.PositiveSmallIntegerField(default=12)),
                ('tenor_unit', models.CharField(choices=[('week', 'Weeks'), ('month', 'Months')], default='month', max_length=12)),
                ('interest_method', models.CharField(choices=[('flat', 'Flat rate'), ('reducing', 'Reducing balance')], default='flat', max_length=16)),
                ('interest_rate', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('interest_rate_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='annual', max_length=12)),
                ('repayment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='monthly', max_length=16)),
                ('quote_amount_field_key', models.SlugField(default='loan_amount', help_text='Origination/workflow variable containing the requested principal.', max_length=80)),
                ('quote_tenor_field_key', models.SlugField(default='repayment_period', help_text='Origination/workflow variable containing the numeric tenor.', max_length=80)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product__sort_order', 'product__name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ProductVersionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='product_quote_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='product_custom_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='product_selected_fee_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='product_requirement_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='product_terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='product_custom_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='product_selected_fee_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='product_quote_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='product_requirement_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='product_terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='product_quote_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='product_custom_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='product_selected_fee_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='product_requirement_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='product_terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='product_quote_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='product_custom_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='product_selected_fee_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='product_requirement_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='product_terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='core.product'),
        ),
        migrations.AddField(
            model_name='emergencyaccessgrant',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_access_grants', to='core.product'),
        ),
        migrations.AddField(
            model_name='jawabuapprovaldelegation',
            name='product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jawabu_approval_delegations', to='core.product'),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jawabu_farmer_records', to='core.product'),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spin_credit_requests', to='core.product'),
        ),
        migrations.AddField(
            model_name='tatrepairjob',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tat_repair_jobs', to='core.product'),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tat_cases', to='core.product'),
        ),
        migrations.AddField(
            model_name='workflowtatdailymetric',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tat_daily_metrics', to='core.product'),
        ),
        migrations.AddField(
            model_name='productalias',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.product'),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='branch',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'branch'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_availability_assignments', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_assignments', to='core.product'),
        ),
        migrations.AddField(
            model_name='productmappingissue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapping_issues', to='core.product'),
        ),
        migrations.AddField(
            model_name='productmappingissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_product_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.product'),
        ),
        migrations.AddField(
            model_name='productversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_product_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productversion',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_versions', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='producttatconfiguration',
            name='product_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tat_configuration', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='productrequirement',
            name='product_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='productfee',
            name='product_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='productcustomattribute',
            name='product_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attributes', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jawabu_farmer_records', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origination_applications', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='originationproductdefinition',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origination_definitions', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spin_credit_requests', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tat_cases', to='core.productversion'),
        ),
        migrations.AddField(
            model_name='productversionevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productversionevent',
            name='product_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.productversion'),
        ),
        migrations.AddConstraint(
            model_name='productavailability',
            constraint=models.UniqueConstraint(fields=('product', 'scope_signature'), name='unique_product_availability_scope'),
        ),
        migrations.AddConstraint(
            model_name='productmappingissue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('normalized_value', 'source_workflow', 'source_model', 'source_record_id'), name='unique_open_product_mapping_issue'),
        ),
        migrations.AddIndex(
            model_name='productversion',
            index=models.Index(fields=['product', 'status', 'effective_from'], name='core_produc_product_0aa00b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productversion',
            constraint=models.UniqueConstraint(fields=('product', 'version'), name='unique_global_product_version'),
        ),
        migrations.AddConstraint(
            model_name='productrequirement',
            constraint=models.UniqueConstraint(fields=('product_version', 'key'), name='unique_product_requirement_key'),
        ),
        migrations.AddConstraint(
            model_name='productfee',
            constraint=models.UniqueConstraint(fields=('product_version', 'key'), name='unique_product_fee_key'),
        ),
        migrations.AddConstraint(
            model_name='productcustomattribute',
            constraint=models.UniqueConstraint(fields=('product_version', 'key'), name='unique_product_attribute_key'),
        ),
        migrations.RunPython(backfill_global_products, reverse_global_product_backfill),
    ]
