# Generated by Django 5.1.6 on 2026-08-13

import re
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


PARTNERSHIP_LAF_FIELDS = (
    'acknowledgement_amount', 'acknowledgement_recipient_name', 'amount_advanced',
    'applicant_dob', 'applicant_email', 'applicant_first_name', 'applicant_id_number',
    'applicant_middle_name', 'applicant_next_of_kin', 'applicant_next_of_kin_id',
    'applicant_next_of_kin_phone', 'applicant_other_phone', 'applicant_phone',
    'applicant_postal_address', 'applicant_postal_code', 'applicant_residence_address',
    'applicant_surname', 'applicant_town', 'approval_amount', 'borrower_full_name',
    'branch_manager_name', 'bro_1_name', 'bro_2_name', 'business_location', 'business_type',
    'commissioner_location', 'commissioner_oath_day', 'commissioner_oath_month',
    'commissioner_oath_year', 'deponent_full_name', 'deponent_id_number',
    'employer_business_address', 'guarantor_1_business_location', 'guarantor_1_employer',
    'guarantor_1_id_number', 'guarantor_1_name', 'guarantor_1_phone',
    'guarantor_1_relationship', 'guarantor_1_residence_location', 'guarantor_1_years_known',
    'guarantor_2_id_number', 'guarantor_2_name', 'guarantor_2_phone',
    'guarantor_2_relationship', 'installment_amount', 'interest_rate',
    'loan_agreement_repayment_period', 'loan_amount', 'loan_product', 'loan_product_other',
    'loan_purpose', 'monthly_expenses', 'monthly_household_expenses', 'monthly_income',
    'net_income', 'number_of_weeks', 'own_contribution', 'penalty_rate', 'project_cost',
    'repayment_period', 'security_1_current_value', 'security_1_description',
    'security_1_serial_number', 'security_1_year_of_purchase',
)

MONEY_FIELDS = {
    'acknowledgement_amount', 'amount_advanced', 'approval_amount', 'installment_amount',
    'loan_amount', 'monthly_expenses', 'monthly_household_expenses', 'monthly_income',
    'net_income', 'own_contribution', 'project_cost', 'security_1_current_value',
}

SYSTEM_FIELDS = (
    ('reference_number', 'Reference number', 'text', 'filter'),
    ('branch_code', 'Branch', 'text', 'dimension'),
    ('loan_officer_name', 'Loan officer', 'text', 'filter'),
    ('application_date', 'Application date', 'date', 'dimension'),
)


def _normalized(value):
    return re.sub(r'[^a-z0-9_]+', '_', str(value or '').casefold()).strip('_')


def _type_for(key):
    if key in MONEY_FIELDS:
        return 'money'
    if key.endswith('_phone') or key in {'applicant_phone', 'applicant_other_phone'}:
        return 'phone'
    if key.endswith('_id_number') or key in {
        'applicant_id_number', 'applicant_next_of_kin_id', 'deponent_id_number',
    }:
        return 'national_id'
    if key == 'applicant_dob':
        return 'date'
    if key == 'loan_product':
        return 'choice'
    return 'text'


def _category(key):
    if key.startswith(('applicant_', 'borrower_', 'deponent_')):
        return 'Applicant'
    if key.startswith('guarantor_'):
        return 'Guarantor'
    if key.startswith(('loan_', 'approval_', 'amount_', 'interest_', 'penalty_', 'repayment_')):
        return 'Facility'
    if key.startswith('security_'):
        return 'Security'
    if key.startswith(('commissioner_', 'bro_', 'branch_manager_')):
        return 'Officials'
    if key in {'business_location', 'business_type', 'employer_business_address'}:
        return 'Business'
    if key in MONEY_FIELDS or key in {'net_income', 'number_of_weeks', 'own_contribution', 'project_cost'}:
        return 'Financial'
    return 'Application'


def _governance(key, data_type, source='user_input'):
    if source == 'system':
        return 'internal', 'none'
    if data_type == 'money' or any(token in key for token in ('income', 'expense', 'interest', 'amount')):
        return 'financial', 'partial'
    pii_tokens = (
        'name', 'id', 'phone', 'email', 'address', 'location', 'town', 'dob',
        'next_of_kin', 'guarantor', 'employer',
    )
    if any(token in key for token in pii_tokens):
        return 'pii', 'partial'
    return 'internal', 'none'


def _options(raw_options):
    normalized = []
    seen = set()
    for raw in raw_options or []:
        label = str(raw.get('label') if isinstance(raw, dict) else raw).strip()
        code = _normalized(raw.get('code') if isinstance(raw, dict) else label)
        if not label or not code or code in seen:
            continue
        seen.add(code)
        normalized.append({'code': code, 'label': label, 'active': True})
    return normalized


def seed_origination_field_catalogue(apps, schema_editor):
    DataField = apps.get_model('core', 'OriginationDataField')
    DataFieldEvent = apps.get_model('core', 'OriginationDataFieldEvent')
    ProductDefinition = apps.get_model('core', 'OriginationProductDefinition')
    ReviewIssue = apps.get_model('core', 'OriginationFieldReviewIssue')

    seeded = {}
    for key in PARTNERSHIP_LAF_FIELDS:
        data_type = _type_for(key)
        sensitivity, masking = _governance(key, data_type)
        choice_options = []
        if key == 'loan_product':
            choice_options = _options([
                'Jawabu Express', 'Jawabu Advantage', 'Almasi', 'Landlord', 'Other',
            ])
        reporting_use = 'metric' if key == 'loan_amount' else (
            'filter' if data_type in {'national_id', 'phone'} else 'unavailable'
        )
        field = DataField.objects.create(
            key=key,
            label=key.replace('_', ' ').title().replace('Bro ', 'BRO '),
            category=_category(key), data_type=data_type,
            source_type='user_input', sensitivity=sensitivity,
            masking_policy=masking, reporting_use=reporting_use,
            export_allowed=key == 'loan_amount', choice_options=choice_options,
        )
        seeded[key] = field
        DataFieldEvent.objects.create(
            data_field_id=field.pk, action='seeded',
            metadata={'key': key, 'type': data_type},
        )

    for key, label, data_type, reporting_use in SYSTEM_FIELDS:
        field = DataField.objects.create(
            key=key, label=label, category='System', data_type=data_type,
            source_type='system', sensitivity='internal', masking_policy='none',
            reporting_use=reporting_use, export_allowed=True,
        )
        seeded[key] = field
        DataFieldEvent.objects.create(
            data_field_id=field.pk, action='seeded',
            metadata={'key': key, 'type': data_type},
        )

    for definition in ProductDefinition.objects.order_by('created_at', 'pk').iterator():
        schema = dict(definition.form_schema or {})
        fields = [item for item in (schema.get('fields') or []) if isinstance(item, dict)]
        changed = False
        for item in fields:
            key = str(item.get('key') or '').strip()
            data_type = str(item.get('type') or 'text').strip()
            if not key:
                continue
            candidate = seeded.get(key) or DataField.objects.filter(key=key).first()
            if candidate is None:
                sensitivity, masking = _governance(key, data_type)
                raw_options = item.get('options') if data_type == 'choice' else []
                candidate = DataField.objects.create(
                    key=key, label=str(item.get('label') or key.replace('_', ' ').title())[:160],
                    category=_category(key), data_type=data_type,
                    source_type='user_input', sensitivity=sensitivity,
                    masking_policy=masking, reporting_use='unavailable',
                    choice_options=_options(raw_options),
                )
                seeded[key] = candidate
                DataFieldEvent.objects.create(
                    data_field_id=candidate.pk, action='imported',
                    metadata={'key': key, 'type': data_type},
                )
            if candidate.data_type != data_type:
                ReviewIssue.objects.get_or_create(
                    product_definition_id=definition.pk, legacy_key=key,
                    defaults={
                        'legacy_type': data_type,
                        'legacy_label': str(item.get('label') or key.replace('_', ' ').title())[:160],
                        'reason': 'type_conflict', 'suggested_field_id': candidate.pk,
                    },
                )
                continue
            if definition.lifecycle_status == 'draft' and not item.get('data_field_id'):
                item.update({
                    'data_field_id': str(candidate.pk),
                    'sensitivity': candidate.sensitivity,
                    'masking_policy': candidate.masking_policy,
                    'reporting_use': candidate.reporting_use,
                    'export_allowed': candidate.export_allowed,
                    'source_type': candidate.source_type,
                })
                changed = True
        if changed:
            schema['fields'] = fields
            schema['_revision'] = int(schema.get('_revision') or 0) + 1
            definition.form_schema = schema
            definition.save(update_fields=['form_schema'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_product_productalias_productavailability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginationDataField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, default='Application', max_length=80)),
                ('data_type', models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('number', 'Number'), ('money', 'Money'), ('date', 'Date'), ('phone', 'Phone'), ('national_id', 'National ID'), ('choice', 'Choice'), ('boolean', 'Yes / No')], max_length=20)),
                ('source_type', models.CharField(choices=[('user_input', 'User input'), ('system', 'System derived')], default='user_input', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('pii', 'Personal data (PII)'), ('financial', 'Financial'), ('restricted', 'Restricted')], default='pii', max_length=20)),
                ('masking_policy', models.CharField(choices=[('none', 'No masking'), ('partial', 'Partial masking'), ('full', 'Full masking')], default='partial', max_length=16)),
                ('reporting_use', models.CharField(choices=[('unavailable', 'Not reportable'), ('filter', 'Filter only'), ('dimension', 'Dimension'), ('metric', 'Metric')], default='unavailable', max_length=16)),
                ('export_allowed', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('choice_options', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_origination_data_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['category', 'label', 'key']},
        ),
        migrations.CreateModel(
            name='OriginationDataFieldEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origination_data_field_events', to=settings.AUTH_USER_MODEL)),
                ('data_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.originationdatafield')),
            ],
            options={'ordering': ['occurred_at', 'id']},
        ),
        migrations.CreateModel(
            name='OriginationFieldReviewIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legacy_key', models.CharField(max_length=120)),
                ('legacy_type', models.CharField(blank=True, default='text', max_length=20)),
                ('legacy_label', models.CharField(blank=True, default='', max_length=160)),
                ('reason', models.CharField(blank=True, default='missing_catalogue_field', max_length=80)),
                ('status', models.CharField(choices=[('open', 'Needs review'), ('resolved', 'Resolved'), ('accepted_legacy', 'Accepted as legacy')], db_index=True, default='open', max_length=24)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_origination_field_reviews', to=settings.AUTH_USER_MODEL)),
                ('product_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_review_issues', to='core.originationproductdefinition')),
                ('resolution_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_legacy_reviews', to='core.originationdatafield')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_origination_field_reviews', to=settings.AUTH_USER_MODEL)),
                ('suggested_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suggested_legacy_reviews', to='core.originationdatafield')),
            ],
            options={'ordering': ['status', '-created_at']},
        ),
        migrations.CreateModel(
            name='OriginationReportingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(max_length=120)),
                ('value_type', models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('number', 'Number'), ('money', 'Money'), ('date', 'Date'), ('phone', 'Phone'), ('national_id', 'National ID'), ('choice', 'Choice'), ('boolean', 'Yes / No')], max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('pii', 'Personal data (PII)'), ('financial', 'Financial'), ('restricted', 'Restricted')], max_length=20)),
                ('masking_policy', models.CharField(choices=[('none', 'No masking'), ('partial', 'Partial masking'), ('full', 'Full masking')], max_length=16)),
                ('reporting_use', models.CharField(choices=[('unavailable', 'Not reportable'), ('filter', 'Filter only'), ('dimension', 'Dimension'), ('metric', 'Metric')], max_length=16)),
                ('export_allowed', models.BooleanField(default=False)),
                ('text_value', models.CharField(blank=True, max_length=500, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('choice_code', models.CharField(blank=True, max_length=120, null=True)),
                ('projected_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_values', to='core.loanoriginationapplication')),
                ('data_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_values', to='core.originationdatafield')),
            ],
            options={'ordering': ['application', 'field_key']},
        ),
        migrations.RunPython(seed_origination_field_catalogue, migrations.RunPython.noop),
        migrations.AddIndex(model_name='originationdatafield', index=models.Index(fields=['active', 'category', 'label'], name='core_origin_active_c188a9_idx')),
        migrations.AddIndex(model_name='originationfieldreviewissue', index=models.Index(fields=['status', 'updated_at'], name='core_origin_status_85057f_idx')),
        migrations.AddConstraint(model_name='originationfieldreviewissue', constraint=models.UniqueConstraint(fields=('product_definition', 'legacy_key'), name='unique_origination_field_review_key')),
        migrations.AddIndex(model_name='originationreportingvalue', index=models.Index(fields=['data_field', 'text_value'], name='orig_report_field_text_idx')),
        migrations.AddIndex(model_name='originationreportingvalue', index=models.Index(fields=['data_field', 'decimal_value'], name='orig_report_field_num_idx')),
        migrations.AddIndex(model_name='originationreportingvalue', index=models.Index(fields=['data_field', 'date_value'], name='orig_report_field_date_idx')),
        migrations.AddIndex(model_name='originationreportingvalue', index=models.Index(fields=['data_field', 'boolean_value'], name='orig_report_field_bool_idx')),
        migrations.AddIndex(model_name='originationreportingvalue', index=models.Index(fields=['data_field', 'choice_code'], name='orig_report_field_choice_idx')),
        migrations.AddConstraint(model_name='originationreportingvalue', constraint=models.UniqueConstraint(fields=('application', 'data_field'), name='unique_origination_reporting_value')),
        migrations.AddConstraint(
            model_name='originationreportingvalue',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(value_type__in=['text', 'textarea', 'phone', 'national_id'], text_value__isnull=False, decimal_value__isnull=True, date_value__isnull=True, boolean_value__isnull=True, choice_code__isnull=True)
                    | models.Q(value_type__in=['number', 'money'], text_value__isnull=True, decimal_value__isnull=False, date_value__isnull=True, boolean_value__isnull=True, choice_code__isnull=True)
                    | models.Q(value_type='date', text_value__isnull=True, decimal_value__isnull=True, date_value__isnull=False, boolean_value__isnull=True, choice_code__isnull=True)
                    | models.Q(value_type='boolean', text_value__isnull=True, decimal_value__isnull=True, date_value__isnull=True, boolean_value__isnull=False, choice_code__isnull=True)
                    | models.Q(value_type='choice', text_value__isnull=True, decimal_value__isnull=True, date_value__isnull=True, boolean_value__isnull=True, choice_code__isnull=False)
                ),
                name='orig_reporting_matching_typed_value',
            ),
        ),
    ]
