# Generated by Django 5.1.6 on 2026-08-14 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_compact_origination_product_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='originationsigningpackage',
            name='requirement_evidence_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OriginationCorrectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_revision', models.PositiveIntegerField()),
                ('summary', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('addressed', 'Addressed')], db_index=True, default='open', max_length=16)),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('addressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addressed_origination_corrections', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='core.loanoriginationapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origination_correction_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OriginationCorrectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('field', 'Application field'), ('requirement', 'Product requirement')], max_length=20)),
                ('target_key', models.CharField(max_length=120)),
                ('target_label', models.CharField(max_length=160)),
                ('instruction', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.originationcorrectionrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OriginationRequirementEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_revision', models.PositiveIntegerField()),
                ('requirement_key', models.CharField(max_length=80)),
                ('requirement_label', models.CharField(max_length=160)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('uploaded', 'Uploaded'), ('failed', 'Upload failed'), ('removed', 'Removed')], db_index=True, default='pending', max_length=16)),
                ('drive_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_url', models.URLField(blank=True, default='', max_length=1000)),
                ('upload_error', models.TextField(blank=True, default='')),
                ('request_id', models.CharField(max_length=128)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirement_evidence_files', to='core.loanoriginationapplication')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_origination_requirement_evidence', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_origination_requirement_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requirement_key', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='originationcorrectionrequest',
            index=models.Index(fields=['application', 'status', 'created_at'], name='orig_corr_app_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='originationcorrectionrequest',
            constraint=models.UniqueConstraint(fields=('application', 'application_revision'), name='unique_orig_correction_revision'),
        ),
        migrations.AddConstraint(
            model_name='originationcorrectionitem',
            constraint=models.UniqueConstraint(fields=('correction_request', 'target_type', 'target_key'), name='unique_orig_correction_target'),
        ),
        migrations.AddIndex(
            model_name='originationrequirementevidence',
            index=models.Index(fields=['application', 'requirement_key', 'status'], name='orig_evid_app_req_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='originationrequirementevidence',
            constraint=models.UniqueConstraint(fields=('application', 'request_id'), name='unique_orig_evidence_request'),
        ),
    ]
