# Generated by Django 5.1.6 on 2026-08-14 13:19

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import re
import unicodedata
import uuid
from django.conf import settings
from django.db import migrations, models


KNBS_SOURCE_TITLE = '2019 Kenya Population and Housing Census: Population by Sex, Households, Land Area and Density by Sub-county'
KNBS_SOURCE_URL = 'https://www.knbs.or.ke/wp-content/uploads/2023/09/2019-Kenya-population-and-Housing-Census-Population-households-density-by-sub-county.xlsx'
KNBS_SOURCE_SHA256 = 'f500d73dffd1bd6adfd92257970227ab5483809f0623936242f554a3a66b4528'
KENYA_COUNTY_SUB_COUNTIES = (
    (1, 'MOMBASA', ('CHANGAMWE', 'JOMVU', 'KISAUNI', 'LIKONI', 'MVITA', 'NYALI')),
    (2, 'KWALE', ('KINANGO', 'LUNGA LUNGA', 'MATUGA', 'MSAMBWENI', 'SAMBURU')),
    (3, 'KILIFI', ('CHONYI', 'GANZE', 'KALOLENI', 'KAUMA', 'KILIFI NORTH', 'KILIFI SOUTH', 'MAGARINI', 'MALINDI', 'RABAI')),
    (4, 'TANA RIVER', ('TANA DELTA', 'TANA NORTH', 'TANA RIVER')),
    (5, 'LAMU', ('LAMU EAST', 'LAMU WEST')),
    (6, 'TAITA/TAVETA', ('MWATATE', 'TAITA', 'TAVETA', 'VOI')),
    (7, 'GARISSA', ('BALAMBALA', 'DADAAB', 'FAFI', 'GARISSA', 'HULUGHO', 'IJARA', 'LAGDERA')),
    (8, 'WAJIR', ('BUNA', 'ELDAS', 'HABASWEIN', 'TARBAJ', 'WAJIR EAST', 'WAJIR NORTH', 'WAJIR SOUTH', 'WAJIR WEST')),
    (9, 'MANDERA', ('MANDERA WEST', 'BANISA', 'KUTULO', 'LAFEY', 'MANDERA CENTRAL', 'MANDERA EAST', 'MANDERA NORTH')),
    (10, 'MARSABIT', ('LOIYANGALANI', 'MARSABIT CENTRAL', 'MARSABIT NORTH', 'MARSABIT SOUTH', 'MOYALE', 'NORTH HORR', 'SOLOLO')),
    (11, 'ISIOLO', ('GARBATULLA', 'ISIOLO', 'MERTI')),
    (12, 'MERU', ('BUURI EAST', 'BUURI WEST', 'IGEMBE CENTRAL', 'IGEMBE NORTH', 'IGEMBE SOUTH', 'IMENTI NORTH', 'IMENTI SOUTH', 'MERU CENTRAL', 'TIGANIA CENTRAL', 'TIGANIA EAST', 'TIGANIA WEST', 'MERU NATIONAL PARK', 'MT. KENYA FOREST')),
    (13, 'THARAKA-NITHI', ("IGAMBANG'OMBE", 'MAARA', 'MERU SOUTH', 'THARAKA NORTH', 'THARAKA SOUTH', 'MOUNT KENYA FOREST')),
    (14, 'EMBU', ('EMBU EAST', 'EMBU NORTH', 'EMBU WEST', 'MBEERE SOUTH', 'MBEERE NORTH', 'MOUNT KENYA FOREST')),
    (15, 'KITUI', ('IKUTHA', 'KATULANI', 'KISASI', 'KITUI CENTRAL', 'KITUI WEST', 'KYUSO', 'LOWER YATTA', 'MATINYANI', 'MIGWANI', 'MUMONI', 'MUTITU', 'MUTITU NORTH', 'MUTOMO', 'MWINGI CENTRAL', 'MWINGI EAST', 'NZAMBANI', 'THAGICU', 'TSEIKURU')),
    (16, 'MACHAKOS', ('ATHI RIVER', 'KALAMA', 'KANGUNDO', 'KATHIANI', 'MACHAKOS', 'MASINGA', 'MATUNGULU', 'MWALA', 'YATTA')),
    (17, 'MAKUENI', ('KATHONZWENI', 'KIBWEZI', 'KILUNGU', 'MAKINDU', 'MAKUENI', 'MBOONI EAST', 'MBOONI WEST', 'MUKAA', 'NZAUI')),
    (18, 'NYANDARUA', ('KINANGOP', 'NYANDARUA SOUTH', 'MIRANGINE', 'KIPIPIRI', 'NYANDARUA CENTRAL', 'NYANDARUA WEST', 'NYANDARUA NORTH', 'ABERDARE NATIONAL PARK')),
    (19, 'NYERI', ('TETU', 'KIENI EAST', 'KIENI WEST', 'MATHIRA EAST', 'MATHIRA WEST', 'NYERI SOUTH', 'MUKURWE-INI', 'NYERI CENTRAL', 'MT. KENYA FOREST', 'ABERDARE FOREST')),
    (20, 'KIRINYAGA', ('KIRINYAGA CENTRAL', 'KIRINYAGA EAST', 'KIRINYAGA WEST', 'MWEA EAST', 'MWEA WEST', 'MOUNT KENYA FOREST')),
    (21, "MURANG'A", ("MURANG'A EAST", 'KANGEMA', 'MATHIOYA', 'KAHURO', "MURANG'A SOUTH", 'GATANGA', 'KIGUMO', 'KANDARA', 'ABERDARE FOREST')),
    (22, 'KIAMBU', ('GATUNDU NORTH', 'GATUNDU SOUTH', 'GITHUNGURI', 'JUJA', 'KABETE', 'KIAMBAA', 'KIAMBU', 'KIKUYU', 'LARI', 'LIMURU', 'RUIRU', 'THIKA EAST', 'THIKA WEST')),
    (23, 'TURKANA', ('KIBISH', 'LOIMA', 'TURKANA CENTRAL', 'TURKANA EAST', 'TURKANA NORTH', 'TURKANA SOUTH', 'TURKANA WEST')),
    (24, 'WEST POKOT', ('KIPKOMO', 'POKOT CENTRAL', 'POKOT NORTH', 'POKOT SOUTH', 'WEST POKOT')),
    (25, 'SAMBURU', ('SAMBURU CENTRAL', 'SAMBURU EAST', 'SAMBURU NORTH')),
    (26, 'TRANS NZOIA', ('TRANS NZOIA WEST', 'TRANS NZOIA EAST', 'KWANZA', 'ENDEBESS', 'KIMININI')),
    (27, 'UASIN GISHU', ('AINABKOI', 'KAPSERET', 'KESSES', 'MOIBEN', 'SOY', 'TURBO')),
    (28, 'ELGEYO/MARAKWET', ('KEIYO NORTH', 'KEIYO SOUTH', 'MARAKWET EAST', 'MARAKWET WEST')),
    (29, 'NANDI', ('CHESUMEI', 'NANDI CENTRAL', 'NANDI EAST', 'NANDI NORTH', 'NANDI SOUTH', 'TINDERET')),
    (30, 'BARINGO', ('BARINGO CENTRAL', 'BARINGO NORTH', 'EAST POKOT', 'KOIBATEK', 'MARIGAT', 'MOGOTIO', 'TIATY EAST', 'LAKE BARINGO')),
    (31, 'LAIKIPIA', ('LAIKIPIA CENTRAL', 'LAIKIPIA EAST', 'LAIKIPIA NORTH', 'LAIKIPIA WEST', 'NYAHURURU')),
    (32, 'NAKURU', ('GILGIL', 'KURESOI NORTH', 'KURESOI SOUTH', 'MOLO', 'NAIVASHA', 'NAKURU EAST', 'NAKURU NORTH', 'NAKURU WEST', 'NJORO', 'RONGAI', 'SUBUKIA')),
    (33, 'NAROK', ('NAROK EAST', 'NAROK NORTH', 'NAROK SOUTH', 'NAROK WEST', 'TRANS MARA EAST', 'TRANS MARA WEST', 'MAU FOREST')),
    (34, 'KAJIADO', ('ISINYA', 'KAJIADO CENTRAL', 'KAJIADO NORTH', 'KAJIADO WEST', 'LOITOKITOK', 'MASHUURU')),
    (35, 'KERICHO', ('BELGUT', 'BURETI', 'KERICHO EAST', 'KIPKELION', 'LONDIANI', 'SOIN SIGOWET', 'MAU FOREST', 'TINDERET FOREST')),
    (36, 'BOMET', ('BOMET EAST', 'CHEPALUNGU', 'KONOIN', 'SOTIK', 'BOMET CENTRAL', 'MAU FOREST')),
    (37, 'KAKAMEGA', ('BUTERE', 'KAKAMEGA CENTRAL', 'KAKAMEGA EAST', 'KAKAMEGA NORTH', 'KAKAMEGA SOUTH', 'KHWISERO', 'LIKUYANI', 'LUGARI', 'MATETE', 'MATUNGU', 'MUMIAS EAST', 'MUMIAS WEST', 'NAVAKHOLO')),
    (38, 'VIHIGA', ('EMUHAYA', 'VIHIGA', 'SABATIA', 'LUANDA', 'HAMISI', 'KAKAMEGA FOREST')),
    (39, 'BUNGOMA', ('BUMULA', 'BUNGOMA CENTRAL', 'BUNGOMA EAST', 'BUNGOMA NORTH', 'BUNGOMA SOUTH', 'CHEPTAIS', 'KIMILILI', 'MT ELGON', 'BUNGOMA WEST', 'TONGAREN', 'WEBUYE WEST', 'MT ELGON FOREST')),
    (40, 'BUSIA', ('BUNYALA', 'BUSIA', 'BUTULA', 'NAMBALE', 'SAMIA', 'TESO NORTH', 'TESO SOUTH')),
    (41, 'SIAYA', ('SIAYA', 'GEM', 'UGENYA', 'UGUNJA', 'BONDO', 'RARIEDA')),
    (42, 'KISUMU', ('KISUMU EAST', 'KISUMU CENTRAL', 'KISUMU WEST', 'SEME', 'MUHORONI', 'NYANDO', 'NYAKACH')),
    (43, 'HOMA BAY', ('HOMA BAY', 'NDHIWA', 'RACHUONYO NORTH', 'RACHUONYO EAST', 'RACHUONYO SOUTH', 'RANGWE', 'SUBA NORTH', 'SUBA SOUTH')),
    (44, 'MIGORI', ('AWENDO', 'KURIA EAST', 'KURIA WEST', 'NYATIKE', 'RONGO', 'SUNA EAST', 'SUNA WEST', 'URIRI')),
    (45, 'KISII', ('ETAGO', 'GUCHA', 'GUCHA SOUTH', 'KENYENYA', 'KISII CENTRAL', 'KISII SOUTH', 'KITUTU CENTRAL', 'MARANI', 'MASABA SOUTH', 'NYAMACHE', 'SAMETA')),
    (46, 'NYAMIRA', ('BORABU', 'MANGA', 'MASABA NORTH', 'NYAMIRA NORTH', 'NYAMIRA SOUTH')),
    (47, 'NAIROBI CITY', ('DAGORETTI', 'EMBAKASI', 'KAMUKUNJI', 'KASARANI', 'KIBRA', "LANG'ATA", 'MAKADARA', 'MATHARE', 'NJIRU', 'STAREHE', 'WESTLANDS')),
)


def _normalized(value):
    text = unicodedata.normalize('NFKC', str(value or '')).replace('\u2019', "'")
    return re.sub(r'[^a-z0-9]+', '_', text.casefold()).strip('_')


def _display_name(value):
    value = str(value or '').title()
    return re.sub(r"(?<=')[A-Z]", lambda match: match.group(0).lower(), value)


def _stable_code(prefix, value):
    suffix = re.sub(r'[^A-Z0-9]+', '-', str(value or '').upper()).strip('-')
    return f'{prefix}-{suffix}'[:64]


def _stage_issue(MappingIssue, *, location_type, raw_value, workflow, model, field, record_id, detail):
    normalized = _normalized(raw_value)
    if not normalized:
        return
    MappingIssue.objects.get_or_create(
        location_type=location_type,
        normalized_value=normalized,
        source_model=model,
        source_field=field,
        source_record_id=str(record_id),
        status='open',
        defaults={
            'raw_value': str(raw_value)[:255],
            'source_workflow': workflow,
            'detail': detail,
        },
    )


def seed_and_backfill_locations(apps, schema_editor):
    Location = apps.get_model('core', 'OperationalLocation')
    Alias = apps.get_model('core', 'OperationalLocationAlias')
    Policy = apps.get_model('core', 'LocationPolicyState')
    MappingIssue = apps.get_model('core', 'LocationMappingIssue')
    Farmer = apps.get_model('core', 'JawabuFarmerMaster')
    AccessGrant = apps.get_model('core', 'AccessGrant')
    OriginationApplication = apps.get_model('core', 'LoanOriginationApplication')
    OrderUpdate = apps.get_model('core', 'OrderApprovalUpdate')

    source_defaults = {
        'source_name': 'Kenya National Bureau of Statistics',
        'source_reference': KNBS_SOURCE_URL,
    }
    used_codes = set()
    seeded_location_ids = set()
    for branch in Location.objects.filter(location_type='branch').order_by('sort_order', 'pk'):
        base = _stable_code('JBL-BR', branch.name) or f'JBL-BR-{branch.pk}'
        code = base
        counter = 2
        while code.casefold() in used_codes:
            code = f'{base[:60]}-{counter}'
            counter += 1
        used_codes.add(code.casefold())
        Location.objects.filter(pk=branch.pk).update(code=code)
        seeded_location_ids.add(branch.pk)

    existing_counties = list(Location.objects.filter(location_type='county'))
    for county_number, source_county_name, sub_county_names in KENYA_COUNTY_SUB_COUNTIES:
        display_county_name = _display_name(source_county_name)
        accepted_names = {_normalized(source_county_name)}
        if county_number == 21:
            accepted_names.add('muranga')
        if county_number == 47:
            accepted_names.add('nairobi')
        county = next(
            (item for item in existing_counties if _normalized(item.name) in accepted_names),
            None,
        )
        previous_name = county.name if county else ''
        county_code = f'KE-{county_number:02d}'
        county_values = {
            'name': display_county_name,
            'code': county_code,
            'active': True,
            'sort_order': county_number,
            **source_defaults,
        }
        if county is None:
            county = Location.objects.create(location_type='county', **county_values)
            existing_counties.append(county)
        else:
            Location.objects.filter(pk=county.pk).update(**county_values)
            for field, value in county_values.items():
                setattr(county, field, value)
        used_codes.add(county_code.casefold())
        seeded_location_ids.add(county.pk)
        if previous_name and _normalized(previous_name) != _normalized(display_county_name):
            Alias.objects.get_or_create(
                location_type='county', normalized_alias=_normalized(previous_name),
                defaults={'location_id': county.pk, 'alias': previous_name, 'active': True},
            )

        for sub_order, source_sub_name in enumerate(sub_county_names, start=1):
            display_sub_name = _display_name(source_sub_name)
            sub_code = _stable_code(f'KE-{county_number:02d}-SC', source_sub_name)
            sub_county = Location.objects.filter(
                location_type='sub_county', parent_id=county.pk,
                name__iexact=display_sub_name,
            ).first()
            sub_values = {
                'name': display_sub_name,
                'code': sub_code,
                'parent_id': county.pk,
                'active': True,
                'sort_order': sub_order,
                **source_defaults,
            }
            if sub_county is None:
                sub_county = Location.objects.create(location_type='sub_county', **sub_values)
            else:
                Location.objects.filter(pk=sub_county.pk).update(**sub_values)
            used_codes.add(sub_code.casefold())
            seeded_location_ids.add(sub_county.pk)

    # Preserve any locally configured legacy county that is not part of the
    # reviewed KNBS seed. It remains visible for Admin retirement/review, but
    # must receive a stable code before the non-empty/unique constraints land.
    for legacy_location in Location.objects.exclude(pk__in=seeded_location_ids).order_by('pk'):
        prefix = 'KE-LEGACY' if legacy_location.location_type == 'county' else 'JBL-LEGACY'
        base = _stable_code(prefix, legacy_location.name) or f'{prefix}-{legacy_location.pk}'
        code = base
        counter = 2
        while code.casefold() in used_codes:
            code = f'{base[:60]}-{counter}'
            counter += 1
        used_codes.add(code.casefold())
        Location.objects.filter(pk=legacy_location.pk).update(
            code=code,
            source_name='Legacy operational configuration',
        )

    Policy.objects.update_or_create(
        pk=1,
        defaults={
            'mode': 'audit',
            'source_manifest': {
                'title': KNBS_SOURCE_TITLE,
                'url': KNBS_SOURCE_URL,
                'sha256': KNBS_SOURCE_SHA256,
                'retrieved_on': '2026-08-14',
                'county_count': 47,
                'sub_county_count': sum(len(items) for _code, _name, items in KENYA_COUNTY_SUB_COUNTIES),
            },
        },
    )

    locations = list(Location.objects.all())
    aliases = list(Alias.objects.select_related('location'))

    def resolve(raw_value, location_type, *, county=None):
        normalized = _normalized(raw_value)
        if not normalized:
            return None
        matches = [
            item for item in locations
            if item.location_type == location_type
            and (location_type != 'sub_county' or county is None or item.parent_id == county.pk)
            and (_normalized(item.name) == normalized or item.code.casefold() == str(raw_value).strip().casefold())
        ]
        if not matches:
            alias_ids = {
                item.location_id for item in aliases
                if item.location_type == location_type and item.normalized_alias == normalized and item.active
            }
            matches = [item for item in locations if item.pk in alias_ids]
        return matches[0] if len(matches) == 1 else None

    def resolve_or_issue(raw_value, location_type, *, workflow, model, field, record_id, county=None):
        if not str(raw_value or '').strip():
            return None
        location = resolve(raw_value, location_type, county=county)
        if location is None:
            _stage_issue(
                MappingIssue, location_type=location_type, raw_value=raw_value,
                workflow=workflow, model=model, field=field, record_id=record_id,
                detail='Legacy value did not uniquely match the verified canonical catalogue.',
            )
        return location

    for farmer in Farmer.objects.all().iterator():
        county = resolve_or_issue(
            farmer.county, 'county', workflow='jawabu_portal', model='JawabuFarmerMaster',
            field='county', record_id=farmer.pk,
        )
        sub_county = resolve_or_issue(
            farmer.sub_county, 'sub_county', workflow='jawabu_portal', model='JawabuFarmerMaster',
            field='sub_county', record_id=farmer.pk, county=county,
        )
        if county is None and sub_county is not None:
            county = next((item for item in locations if item.pk == sub_county.parent_id), None)
        branch = resolve_or_issue(
            farmer.branch, 'branch', workflow='jawabu_portal', model='JawabuFarmerMaster',
            field='branch', record_id=farmer.pk,
        )
        Farmer.objects.filter(pk=farmer.pk).update(
            branch_ref_id=branch.pk if branch else None,
            county_ref_id=county.pk if county else None,
            sub_county_ref_id=sub_county.pk if sub_county else None,
        )

    for grant in AccessGrant.objects.exclude(branch='').iterator():
        if _normalized(grant.branch) in {'all', 'global'} or str(grant.branch).strip() == '*':
            continue
        branch = resolve_or_issue(
            grant.branch, 'branch', workflow=grant.workflow, model='AccessGrant',
            field='branch', record_id=grant.pk,
        )
        if branch:
            AccessGrant.objects.filter(pk=grant.pk).update(branch_ref_id=branch.pk)

    for application in OriginationApplication.objects.exclude(branch='').iterator():
        branch = resolve_or_issue(
            application.branch, 'branch', workflow='loan_origination',
            model='LoanOriginationApplication', field='branch', record_id=application.pk,
        )
        if branch:
            OriginationApplication.objects.filter(pk=application.pk).update(
                branch_ref_id=branch.pk,
                location_snapshot={'branch': {'code': branch.code, 'name': branch.name, 'type': 'branch', 'parent_code': ''}},
            )

    for update in OrderUpdate.objects.all().iterator():
        fields = update.parsed_fields if isinstance(update.parsed_fields, dict) else {}
        county = resolve_or_issue(
            fields.get('county'), 'county', workflow='order_approval', model='OrderApprovalUpdate',
            field='county', record_id=update.pk,
        )
        sub_county = resolve_or_issue(
            fields.get('sub_county'), 'sub_county', workflow='order_approval', model='OrderApprovalUpdate',
            field='sub_county', record_id=update.pk, county=county,
        )
        if county is None and sub_county is not None:
            county = next((item for item in locations if item.pk == sub_county.parent_id), None)
        branch = resolve_or_issue(
            fields.get('branch'), 'branch', workflow='order_approval', model='OrderApprovalUpdate',
            field='branch', record_id=update.pk,
        )
        snapshot = {}
        for key, item in (('branch', branch), ('county', county), ('sub_county', sub_county)):
            if item:
                parent = next((parent for parent in locations if parent.pk == item.parent_id), None)
                snapshot[key] = {
                    'code': item.code, 'name': item.name, 'type': item.location_type,
                    'parent_code': parent.code if parent else '',
                }
        OrderUpdate.objects.filter(pk=update.pk).update(
            branch_ref_id=branch.pk if branch else None,
            county_ref_id=county.pk if county else None,
            sub_county_ref_id=sub_county.pk if sub_county else None,
            location_snapshot=snapshot,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_originationsigningpackage_requirement_evidence_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['branch__sort_order', 'branch__name', 'area__sort_order', 'area__name'],
            },
        ),
        migrations.CreateModel(
            name='LocationConfigurationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(db_index=True, max_length=40)),
                ('subject_id', models.CharField(db_index=True, max_length=120)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('before_values', models.JSONField(blank=True, default=dict)),
                ('after_values', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LocationMappingIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_type', models.CharField(choices=[('branch', 'Branch'), ('county', 'County'), ('sub_county', 'Sub-county')], db_index=True, max_length=20)),
                ('raw_value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(db_index=True, max_length=180)),
                ('source_workflow', models.CharField(db_index=True, max_length=40)),
                ('source_model', models.CharField(max_length=120)),
                ('source_field', models.CharField(max_length=80)),
                ('source_record_id', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='open', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationPolicyState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('audit', 'Audit only'), ('strict', 'Strict enforcement')], db_index=True, default='audit', max_length=16)),
                ('source_manifest', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location enforcement policy',
                'verbose_name_plural': 'Location enforcement policy',
            },
        ),
        migrations.CreateModel(
            name='OperationalLocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('branch', 'Branch'), ('county', 'County'), ('sub_county', 'Sub-county')], editable=False, max_length=20)),
                ('alias', models.CharField(max_length=160)),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=180)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['location_type', 'alias'],
            },
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='branch_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'branch'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='branch_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'branch'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jawabu_branch_records', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='county_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'county'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jawabu_county_records', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='sub_county_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'sub_county'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jawabu_sub_county_records', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='branch_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'branch'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origination_applications', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='location_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='operationallocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='operationallocation',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='operationallocation',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationallocation',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='operationallocation',
            name='source_reference',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='orderapprovalupdate',
            name='branch_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'branch'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_approval_branch_updates', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='orderapprovalupdate',
            name='county_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'county'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_approval_county_updates', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='orderapprovalupdate',
            name='location_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='orderapprovalupdate',
            name='sub_county_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'sub_county'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_approval_sub_county_updates', to='core.operationallocation'),
        ),
        migrations.AlterField(
            model_name='operationallocation',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='operationallocation',
            name='location_type',
            field=models.CharField(choices=[('branch', 'Branch'), ('county', 'County'), ('sub_county', 'Sub-county')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='area',
            field=models.ForeignKey(limit_choices_to={'location_type__in': ['county', 'sub_county']}, on_delete=django.db.models.deletion.PROTECT, related_name='serving_branch_assignments', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='branch',
            field=models.ForeignKey(limit_choices_to={'location_type': 'branch'}, on_delete=django.db.models.deletion.PROTECT, related_name='service_area_assignments', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_branch_service_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_branch_service_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationconfigurationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationmappingissue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapping_issues', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='locationmappingissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationpolicystate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationallocationalias',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationallocationalias',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='core.operationallocation'),
        ),
        migrations.RemoveConstraint(
            model_name='operationallocation',
            name='unique_operational_location_name_ci',
        ),
        migrations.RunPython(seed_and_backfill_locations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='operationallocation',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'), 'location_type',
                condition=models.Q(location_type__in=['branch', 'county']),
                name='unique_operational_location_name_ci',
            ),
        ),
        migrations.AddConstraint(
            model_name='operationallocation',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('name'), 'parent',
                condition=models.Q(location_type='sub_county'),
                name='unique_sub_county_name_per_county_ci',
            ),
        ),
        migrations.AddConstraint(
            model_name='operationallocation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_operational_location_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='operationallocation',
            constraint=models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='operational_location_code_required'),
        ),
        migrations.AddConstraint(
            model_name='branchservicearea',
            constraint=models.UniqueConstraint(fields=('branch', 'area'), name='unique_branch_service_area'),
        ),
        migrations.AddConstraint(
            model_name='branchservicearea',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('is_primary', True)), fields=('area',), name='unique_active_primary_branch_per_area'),
        ),
        migrations.AddConstraint(
            model_name='locationmappingissue',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('location_type', 'normalized_value', 'source_model', 'source_field', 'source_record_id'), name='unique_open_location_mapping_issue'),
        ),
        migrations.AddConstraint(
            model_name='operationallocationalias',
            constraint=models.UniqueConstraint(fields=('location_type', 'normalized_alias'), name='unique_location_alias_by_type'),
        ),
    ]
