# Generated by Django 5.1.6 on 2026-08-14 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_branchservicearea_locationconfigurationevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operationallocationalias',
            name='unique_location_alias_by_type',
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='county_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'county'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origination_county_applications', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='sub_county_ref',
            field=models.ForeignKey(blank=True, limit_choices_to={'location_type': 'sub_county'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origination_sub_county_applications', to='core.operationallocation'),
        ),
        migrations.AddField(
            model_name='operationallocationalias',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.operationallocation'),
        ),
        migrations.AddConstraint(
            model_name='operationallocationalias',
            constraint=models.UniqueConstraint(condition=models.Q(('location_type__in', ['branch', 'county'])), fields=('location_type', 'normalized_alias'), name='unique_location_alias_by_type'),
        ),
        migrations.AddConstraint(
            model_name='operationallocationalias',
            constraint=models.UniqueConstraint(condition=models.Q(('location_type', 'sub_county')), fields=('parent', 'normalized_alias'), name='unique_sub_county_alias_per_county'),
        ),
    ]
