# Generated by Django 5.1.6 on 2026-08-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_remove_operationallocationalias_unique_location_alias_by_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originationdatafield',
            name='data_type',
            field=models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('number', 'Number'), ('money', 'Money'), ('date', 'Date'), ('phone', 'Phone'), ('national_id', 'National ID'), ('choice', 'Choice'), ('boolean', 'Yes / No'), ('branch', 'Governed branch'), ('county', 'Governed county'), ('sub_county', 'Governed sub-county')], max_length=20),
        ),
        migrations.AlterField(
            model_name='originationreportingvalue',
            name='value_type',
            field=models.CharField(choices=[('text', 'Short text'), ('textarea', 'Long text'), ('number', 'Number'), ('money', 'Money'), ('date', 'Date'), ('phone', 'Phone'), ('national_id', 'National ID'), ('choice', 'Choice'), ('boolean', 'Yes / No'), ('branch', 'Governed branch'), ('county', 'Governed county'), ('sub_county', 'Governed sub-county')], max_length=20),
        ),
    ]
