# Generated by Django 5.1.6 on 2026-08-18 10:32

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
import re
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def seed_complaint_controls(apps, schema_editor):
    Category = apps.get_model('core', 'ComplaintCategory')
    Alias = apps.get_model('core', 'ComplaintCategoryAlias')
    Control = apps.get_model('core', 'ComplaintCaseControl')
    ParsedMessage = apps.get_model('core', 'ParsedMessage')
    Group = apps.get_model('core', 'GroupSheetConfiguration')
    Location = apps.get_model('core', 'OperationalLocation')
    Customer = apps.get_model('core', 'JawabuCustomer')

    configured_group_ids = []
    for group in Group.objects.all().iterator():
        workflow = group.workflow or {}
        if str(workflow.get('type') or 'case') == 'case':
            configured_group_ids.append(str(group.group_id))
    cases = ParsedMessage.objects.filter(group_id__in=configured_group_ids)

    general, _ = Category.objects.get_or_create(
        key='general-complaint',
        defaults={'label': 'General complaint', 'default_priority': 'normal', 'default_sla_hours': 72},
    )
    categories = {'general complaint': general}
    for label in cases.exclude(complaint_category='').values_list('complaint_category', flat=True).distinct():
        clean_label = ' '.join(str(label or '').split())
        normalized = re.sub(r'[^a-z0-9]+', ' ', clean_label.casefold()).strip()
        if not normalized:
            continue
        key_base = slugify(clean_label)[:70] or 'complaint'
        key = key_base
        suffix = 2
        while Category.objects.filter(key=key).exclude(label__iexact=clean_label).exists():
            key = f'{key_base[:74]}-{suffix}'
            suffix += 1
        category, _ = Category.objects.get_or_create(
            label__iexact=clean_label,
            defaults={'key': key, 'label': clean_label, 'default_priority': 'normal', 'default_sla_hours': 72},
        )
        categories[normalized] = category
        Alias.objects.get_or_create(
            normalized_alias=normalized,
            defaults={'category': category, 'alias': clean_label},
        )

    branches = {
        re.sub(r'[^a-z0-9]+', ' ', str(location.name).casefold()).strip(): location
        for location in Location.objects.filter(location_type='branch')
    }
    for case in cases.iterator():
        normalized_category = re.sub(
            r'[^a-z0-9]+', ' ', str(case.complaint_category or '').casefold(),
        ).strip()
        category = categories.get(normalized_category, general)
        normalized_branch = re.sub(
            r'[^a-z0-9]+', ' ', str(case.branch_region or '').casefold(),
        ).strip()
        branch = branches.get(normalized_branch)

        id_matches = Customer.objects.none()
        phone_matches = Customer.objects.none()
        if str(case.customer_id or '').strip():
            id_matches = Customer.objects.filter(national_id__iexact=str(case.customer_id).strip())
        if str(case.customer_phone or '').strip():
            digits = re.sub(r'\D', '', str(case.customer_phone))
            if digits.startswith('0') and len(digits) == 10:
                digits = '254' + digits[1:]
            elif len(digits) == 9:
                digits = '254' + digits
            phone_matches = Customer.objects.filter(primary_phone=digits)
        id_ids = set(id_matches.values_list('pk', flat=True))
        phone_ids = set(phone_matches.values_list('pk', flat=True))
        customer = None
        match_status = 'unmatched'
        if len(id_ids) == 1 and len(phone_ids) == 1 and id_ids != phone_ids:
            match_status = 'conflict'
        elif len(id_ids) == 1:
            customer = id_matches.first()
            match_status = 'exact_id'
        elif len(phone_ids) == 1:
            customer = phone_matches.first()
            match_status = 'exact_phone'
        elif len(id_ids) > 1 or len(phone_ids) > 1:
            match_status = 'ambiguous'

        started = case.timestamp or case.created_at or django.utils.timezone.now()
        Control.objects.get_or_create(
            parsed_message=case,
            defaults={
                'category': category,
                'branch_ref': branch,
                'customer': customer,
                'customer_match_status': match_status,
                'priority': category.default_priority,
                'sla_target_hours': category.default_sla_hours,
                'sla_started_at': started,
                'sla_due_at': started + timedelta(hours=category.default_sla_hours),
                'sync_status': 'success' if case.synced_to_sheets and not case.last_sync_error else 'pending',
            },
        )


def noop_reverse(apps, schema_editor):
    pass


def seed_complaint_capabilities(apps, schema_editor):
    from core.services.workflow_capabilities import capabilities_for_workflow

    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    for definition in capabilities_for_workflow('complaint_cases'):
        for role in definition.default_roles:
            Capability.objects.get_or_create(
                workflow='complaint_cases', role=role, capability_key=definition.key,
                defaults={'enabled': True, 'effect': 'allow'},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_invoice_name_change_letters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('default_priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('default_sla_hours', models.PositiveIntegerField(default=72)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Complaint categories',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCaseControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_match_status', models.CharField(choices=[('exact_id', 'Exact national ID'), ('exact_phone', 'Exact phone'), ('ambiguous', 'Ambiguous'), ('conflict', 'Conflicting identifiers'), ('unmatched', 'Unmatched')], default='unmatched', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], db_index=True, default='normal', max_length=10)),
                ('sla_target_hours', models.PositiveIntegerField(default=72)),
                ('sla_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Synced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaint_cases', to=settings.AUTH_USER_MODEL)),
                ('branch_ref', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'branch'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_cases', to='core.operationallocation')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_cases', to='core.jawabucustomer')),
                ('parsed_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_control', to='core.parsedmessage')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.complaintcategory')),
            ],
            options={
                'ordering': ['-sla_due_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCategoryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=160)),
                ('normalized_alias', models.CharField(editable=False, max_length=180, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='core.complaintcategory')),
            ],
            options={
                'verbose_name_plural': 'Complaint category aliases',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCategoryAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='core.complaintcategory')),
                ('group_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_category_availability', to='core.groupsheetconfiguration')),
            ],
            options={
                'verbose_name_plural': 'Complaint category availability',
            },
        ),
        migrations.CreateModel(
            name='ComplaintCaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payload_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('before_values', models.JSONField(blank=True, default=dict)),
                ('after_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.complaintcasecontrol')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'revision'], name='core_compla_case_id_b5e797_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('case', 'request_id'), name='unique_complaint_case_event_request')],
            },
        ),
        migrations.AddConstraint(
            model_name='complaintcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('label'), name='unique_complaint_category_label_ci'),
        ),
        migrations.AddConstraint(
            model_name='complaintcategory',
            constraint=models.CheckConstraint(condition=models.Q(('default_sla_hours__gt', 0)), name='complaint_category_sla_positive'),
        ),
        migrations.AddIndex(
            model_name='complaintcasecontrol',
            index=models.Index(fields=['assigned_to', 'priority'], name='core_compla_assigne_f1f0df_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcasecontrol',
            index=models.Index(fields=['sync_status', 'updated_at'], name='core_compla_sync_st_c9059a_idx'),
        ),
        migrations.AddConstraint(
            model_name='complaintcasecontrol',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='complaint_case_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='complaintcasecontrol',
            constraint=models.CheckConstraint(condition=models.Q(('sla_target_hours__gt', 0)), name='complaint_case_sla_positive'),
        ),
        migrations.AddConstraint(
            model_name='complaintcategoryavailability',
            constraint=models.UniqueConstraint(fields=('category', 'group_configuration'), name='unique_complaint_category_group'),
        ),
        migrations.RunPython(seed_complaint_controls, noop_reverse),
        migrations.RunPython(seed_complaint_capabilities, noop_reverse),
    ]
