# Generated by Django 5.1.6 on 2026-08-18 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_complaint_case_operational_controls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originationdocumenttemplate',
            options={'ordering': ['product_definition', 'display_order', 'document_key', '-version']},
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='primary_previewed_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='applicability_rule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='default_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='document_key',
            field=models.SlugField(default='primary', max_length=80),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='document_role',
            field=models.CharField(choices=[('primary', 'Primary LAF'), ('supporting', 'Supporting document')], db_index=True, default='primary', max_length=16),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='inclusion_mode',
            field=models.CharField(choices=[('required', 'Always required'), ('conditional_required', 'Required when rule matches'), ('optional', 'Officer selectable')], default='required', max_length=24),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='officer_selectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='signer_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='combined_document_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='document_manifest_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='OriginationApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('document_role', models.CharField(choices=[('primary', 'Primary LAF'), ('supporting', 'Supporting document')], max_length=16)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('inclusion_mode', models.CharField(choices=[('required', 'Always required'), ('conditional_required', 'Required when rule matches'), ('optional', 'Officer selectable')], max_length=24)),
                ('selection_source', models.CharField(choices=[('required', 'Required'), ('rule', 'Applicability rule'), ('default', 'Default selection'), ('officer', 'Officer selection')], default='required', max_length=16)),
                ('applicable', models.BooleanField(default=True)),
                ('selected', models.BooleanField(default=True)),
                ('template_snapshot', models.JSONField(default=dict)),
                ('schema_snapshot', models.JSONField(blank=True, default=dict)),
                ('signer_rules_snapshot', models.JSONField(blank=True, default=list)),
                ('field_payload', models.JSONField(blank=True, default=dict)),
                ('previewed_application_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packet_documents', to='core.loanoriginationapplication')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='core.originationdocumenttemplate')),
            ],
            options={
                'ordering': ['display_order', 'document_key'],
                'constraints': [models.UniqueConstraint(fields=('application', 'document_key'), name='unique_origination_application_document')],
            },
        ),
    ]
