# Generated by Django 5.1.6 on 2026-08-18 14:37

import django.db.models.deletion
from django.db import migrations, models


def pin_legacy_product_owned_assignments(apps, schema_editor):
    Assignment = apps.get_model('core', 'OriginationProductDocumentAssignment')
    Assignment.objects.filter(template__product_definition_id__isnull=False).update(
        version_policy='pinned',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_origination_shared_templates_and_repeatable_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='originationproductdocumentassignment',
            name='version_policy',
            field=models.CharField(choices=[('latest_compatible', 'Latest published compatible version'), ('pinned', 'Pin exact template version')], default='latest_compatible', help_text='Latest-compatible affects new applications only; every application snapshots its resolved version.', max_length=24),
        ),
        migrations.RunPython(
            pin_legacy_product_owned_assignments,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='originationproductdocumentassignment',
            name='template',
            field=models.ForeignKey(help_text='Compatibility baseline and family identity for this assignment.', on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='core.originationdocumenttemplate'),
        ),
    ]
