# Generated by Django 5.1.6 on 2026-08-20 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_origination_field_terminology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='recheck_assigned_to',
            field=models.ForeignKey(blank=True, help_text='Checker responsible for verifying the current correction cycle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_origination_rechecks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='test_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OriginationStampAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('environment', models.CharField(choices=[('test', 'Test only'), ('production', 'Production')], default='test', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('image_png', models.BinaryField()),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('byte_size', models.PositiveIntegerField()),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_origination_stamp_assets', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, limit_choices_to={'location_type': 'branch'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origination_stamp_assets', to='core.operationallocation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_origination_stamp_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'branch', '-version'],
            },
        ),
        migrations.CreateModel(
            name='OriginationSigningAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_key', models.SlugField(max_length=80)),
                ('slot_key', models.SlugField(max_length=80)),
                ('signer_role', models.CharField(max_length=80)),
                ('action_type', models.CharField(choices=[('signature', 'Signature'), ('stamp', 'Stamp')], max_length=16)),
                ('mode', models.CharField(choices=[('test', 'Test simulation'), ('verified', 'Verified production')], max_length=16)),
                ('request_id', models.CharField(db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origination_signing_actions', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.originationsigningpackage')),
                ('stamp_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signing_actions', to='core.originationstampasset')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='originationstampasset',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('name', 'environment', 'version'), name='unique_global_origination_stamp_version'),
        ),
        migrations.AddConstraint(
            model_name='originationstampasset',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('name', 'branch', 'environment', 'version'), name='unique_branch_origination_stamp_version'),
        ),
        migrations.AddConstraint(
            model_name='originationsigningaction',
            constraint=models.UniqueConstraint(fields=('package', 'document_key', 'slot_key'), name='unique_origination_signing_slot_action'),
        ),
        migrations.AddConstraint(
            model_name='originationsigningaction',
            constraint=models.UniqueConstraint(fields=('package', 'request_id'), name='unique_origination_signing_action_request'),
        ),
    ]
