# Generated by Django 5.1.6 on 2026-08-22 13:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_workflow_pilot_modes(apps, schema_editor):
    """Classify all pre-existing SPIN/TAT operational rows as the first pilot cycles."""
    State = apps.get_model('core', 'WorkflowDataModeState')
    SpinRequest = apps.get_model('core', 'SpinCreditRequest')
    SpinReview = apps.get_model('core', 'SpinBatchReviewItem')
    TatCase = apps.get_model('core', 'TatTrackerCase')
    Escalation = apps.get_model('core', 'WorkflowSlaEscalation')
    DailyMetric = apps.get_model('core', 'WorkflowTatDailyMetric')
    TatSequence = apps.get_model('core', 'TatCaseSequence')

    spin_cycle = uuid.uuid4()
    tat_cycle = uuid.uuid4()
    State.objects.update_or_create(
        pk=1,
        defaults={
            'spin_mode': 'pilot',
            'spin_pilot_cycle_id': spin_cycle,
            'spin_mode_version': 1,
            'tat_mode': 'pilot',
            'tat_pilot_cycle_id': tat_cycle,
            'tat_mode_version': 1,
        },
    )
    spin_scope = f'pilot:{spin_cycle}'
    tat_scope = f'pilot:{tat_cycle}'
    SpinRequest.objects.update(data_mode='pilot', pilot_cycle_id=spin_cycle, data_scope_key=spin_scope)
    SpinReview.objects.update(data_mode='pilot', pilot_cycle_id=spin_cycle, data_scope_key=spin_scope)
    TatCase.objects.update(data_mode='pilot', pilot_cycle_id=tat_cycle, data_scope_key=tat_scope)
    Escalation.objects.filter(workflow='tat_tracker').update(
        data_mode='pilot', pilot_cycle_id=tat_cycle, data_scope_key=tat_scope,
    )
    DailyMetric.objects.filter(workflow='tat_tracker').update(
        data_mode='pilot', pilot_cycle_id=tat_cycle, data_scope_key=tat_scope,
    )

    counters = {}
    for group_id, product_key, case_id in TatCase.objects.values_list('group_id', 'product_key', 'case_id'):
        parts = str(case_id or '').rsplit('-', 2)
        if len(parts) != 3:
            continue
        try:
            year = int(parts[-2])
            number = int(parts[-1])
        except (TypeError, ValueError):
            continue
        key = (str(group_id), str(product_key), year)
        counters[key] = max(counters.get(key, 0), number)
    for (group_id, product_key, year), max_number in counters.items():
        TatSequence.objects.update_or_create(
            group_id=group_id,
            product_key=product_key,
            year=year,
            defaults={'next_number': max_number + 1},
        )


def reverse_seed_workflow_pilot_modes(apps, schema_editor):
    # Field/model removal is handled by the reverse schema operations.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_origination_final_packet_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TatCaseSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=100)),
                ('product_key', models.CharField(db_index=True, max_length=80)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDataModeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('spin', 'SPIN'), ('tat_tracker', 'TAT Tracker')], db_index=True, max_length=32)),
                ('action', models.CharField(choices=[('mode_changed', 'Mode changed'), ('cycle_rotated', 'Pilot cycle rotated'), ('purge_started', 'Pilot purge started'), ('purge_completed', 'Pilot purge completed'), ('purge_failed', 'Pilot purge failed'), ('purge_cancelled', 'Pilot purge cancelled')], db_index=True, max_length=32)),
                ('old_mode', models.CharField(blank=True, choices=[('pilot', 'Pilot'), ('production', 'Production')], default='', max_length=16)),
                ('new_mode', models.CharField(blank=True, choices=[('pilot', 'Pilot'), ('production', 'Production')], default='', max_length=16)),
                ('old_cycle_id', models.UUIDField(blank=True, null=True)),
                ('new_cycle_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDataModeState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('spin_mode', models.CharField(choices=[('pilot', 'Pilot'), ('production', 'Production')], default='pilot', max_length=16)),
                ('spin_pilot_cycle_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('spin_mode_version', models.PositiveIntegerField(default=1, editable=False)),
                ('tat_mode', models.CharField(choices=[('pilot', 'Pilot'), ('production', 'Production')], default='pilot', max_length=16)),
                ('tat_pilot_cycle_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('tat_mode_version', models.PositiveIntegerField(default=1, editable=False)),
                ('active_spin_purge_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('active_tat_purge_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SPIN/TAT data mode',
                'verbose_name_plural': 'SPIN/TAT data modes',
            },
        ),
        migrations.CreateModel(
            name='WorkflowPilotFormulaReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow', models.CharField(choices=[('spin', 'SPIN'), ('tat_tracker', 'TAT Tracker')], db_index=True, max_length=32)),
                ('sheet_id', models.CharField(db_index=True, max_length=255)),
                ('sheet_tab', models.CharField(max_length=255)),
                ('configuration_fingerprint', models.CharField(max_length=64)),
                ('formula_fingerprint', models.CharField(max_length=64)),
                ('note', models.TextField()),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pilot purge Sheet readiness',
                'verbose_name_plural': 'pilot purge Sheet readiness',
                'ordering': ['workflow', 'sheet_tab', '-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPilotPurgeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('spin', 'SPIN'), ('tat_tracker', 'TAT Tracker'), ('both', 'SPIN and TAT Tracker')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('partial', 'Partially completed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('reason', models.TextField()),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('manifest_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('cutoff_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pilot purge run',
                'verbose_name_plural': 'pilot purge runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='spinbatchreviewitem',
            name='unique_spin_batch_review_source_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='spincreditrequest',
            name='unique_spin_request_source_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='tattrackercase',
            name='unique_tat_create_request_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='workflowslaescalation',
            name='unique_workflow_sla_escalation_day',
        ),
        migrations.RemoveConstraint(
            model_name='workflowtatdailymetric',
            name='unique_workflow_tat_daily_metric',
        ),
        migrations.AddField(
            model_name='spinbatchreviewitem',
            name='data_mode',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('production', 'Production')], db_index=True, default='pilot', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='spinbatchreviewitem',
            name='data_scope_key',
            field=models.CharField(db_index=True, default='pilot:legacy', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='spinbatchreviewitem',
            name='pilot_cycle_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='data_mode',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('production', 'Production')], db_index=True, default='pilot', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='data_scope_key',
            field=models.CharField(db_index=True, default='pilot:legacy', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='spincreditrequest',
            name='pilot_cycle_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='data_mode',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('production', 'Production')], db_index=True, default='pilot', editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='data_scope_key',
            field=models.CharField(db_index=True, default='pilot:legacy', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='tattrackercase',
            name='pilot_cycle_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='data_mode',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('production', 'Production')], db_index=True, default='production', max_length=16),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='data_scope_key',
            field=models.CharField(db_index=True, default='production', max_length=64),
        ),
        migrations.AddField(
            model_name='workflowslaescalation',
            name='pilot_cycle_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowtatdailymetric',
            name='data_mode',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('production', 'Production')], db_index=True, default='production', max_length=16),
        ),
        migrations.AddField(
            model_name='workflowtatdailymetric',
            name='data_scope_key',
            field=models.CharField(db_index=True, default='production', max_length=64),
        ),
        migrations.AddField(
            model_name='workflowtatdailymetric',
            name='pilot_cycle_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(seed_workflow_pilot_modes, reverse_seed_workflow_pilot_modes),
        migrations.AddIndex(
            model_name='spinbatchreviewitem',
            index=models.Index(fields=['data_mode', 'pilot_cycle_id', 'created_at'], name='core_spinba_data_mo_885389_idx'),
        ),
        migrations.AddIndex(
            model_name='spincreditrequest',
            index=models.Index(fields=['data_mode', 'pilot_cycle_id', 'created_at'], name='core_spincr_data_mo_00ff75_idx'),
        ),
        migrations.AddIndex(
            model_name='tattrackercase',
            index=models.Index(fields=['data_mode', 'pilot_cycle_id', 'created_at'], name='core_tattra_data_mo_0388f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='spinbatchreviewitem',
            constraint=models.UniqueConstraint(fields=('group_id', 'source_message_hash', 'data_scope_key'), name='unique_spin_batch_review_source_per_group'),
        ),
        migrations.AddConstraint(
            model_name='spincreditrequest',
            constraint=models.UniqueConstraint(fields=('group_id', 'source_message_hash', 'data_scope_key'), name='unique_spin_request_source_per_group'),
        ),
        migrations.AddConstraint(
            model_name='tattrackercase',
            constraint=models.UniqueConstraint(condition=models.Q(('create_request_id', ''), _negated=True), fields=('group_id', 'create_request_id', 'data_scope_key'), name='unique_tat_create_request_per_group'),
        ),
        migrations.AddConstraint(
            model_name='workflowslaescalation',
            constraint=models.UniqueConstraint(fields=('workflow', 'subject_id', 'stage_key', 'escalation_date', 'data_scope_key'), name='unique_workflow_sla_escalation_day'),
        ),
        migrations.AddConstraint(
            model_name='workflowtatdailymetric',
            constraint=models.UniqueConstraint(fields=('metric_date', 'workflow', 'group_id', 'branch', 'product_key', 'stage_key', 'responsible_role', 'responsible_actor', 'data_scope_key'), name='unique_workflow_tat_daily_metric'),
        ),
        migrations.AddConstraint(
            model_name='tatcasesequence',
            constraint=models.UniqueConstraint(fields=('group_id', 'product_key', 'year'), name='unique_tat_sequence_group_product_year'),
        ),
        migrations.AddField(
            model_name='workflowdatamodeevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_data_mode_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowdatamodestate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_data_mode_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowpilotformulareadiness',
            name='acknowledged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_workflow_pilot_formula_readiness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowpilotformulareadiness',
            name='group_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_pilot_formula_readiness', to='core.groupsheetconfiguration'),
        ),
        migrations.AddField(
            model_name='workflowpilotpurgerun',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_workflow_pilot_purges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='workflowdatamodeevent',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('workflow', 'action', 'request_id'), name='unique_workflow_mode_event_request'),
        ),
        migrations.AddConstraint(
            model_name='workflowpilotformulareadiness',
            constraint=models.UniqueConstraint(fields=('workflow', 'sheet_id', 'sheet_tab', 'configuration_fingerprint', 'formula_fingerprint'), name='unique_workflow_pilot_formula_readiness'),
        ),
        migrations.AddIndex(
            model_name='workflowpilotpurgerun',
            index=models.Index(fields=['scope', 'status', 'created_at'], name='core_workfl_scope_c69068_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowpilotpurgerun',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('scope', 'request_id'), name='unique_workflow_pilot_purge_request'),
        ),
    ]
