# Generated by Django 5.1.6 on 2026-08-22 15:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_workflow_pilot_modes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TatPrivateAlertConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('unconnected', 'Never connected'), ('blocked', 'Bot blocked or permission withdrawn'), ('temporary_failure', 'Temporarily failing')], db_index=True, default='unknown', max_length=24)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('last_connect_request_id', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tat_private_alert_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAT private alert connection',
                'verbose_name_plural': 'TAT private alert connections',
            },
        ),
        migrations.CreateModel(
            name='TatResponsibilityAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch', models.CharField(db_index=True, max_length=120)),
                ('role', models.CharField(db_index=True, max_length=80)),
                ('product_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('stage_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tat_responsibilities', to=settings.AUTH_USER_MODEL)),
                ('group_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tat_responsibility_assignments', to='core.groupsheetconfiguration')),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_tat_responsibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAT responsibility assignment',
                'verbose_name_plural': 'TAT responsibility assignments',
                'ordering': ['group_configuration', 'branch', 'role', '-stage_key', '-product_key'],
            },
        ),
        migrations.CreateModel(
            name='TatActionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_key', models.CharField(db_index=True, max_length=120)),
                ('stage_label', models.CharField(max_length=160)),
                ('responsible_role', models.CharField(db_index=True, max_length=80)),
                ('case_revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acted', 'Acted'), ('superseded', 'Superseded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('recipient_snapshot', models.JSONField(blank=True, default=dict)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_tat_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tasks', to='core.tattrackercase')),
                ('group_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tat_action_tasks', to='core.groupsheetconfiguration')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='core.tatactiontask')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.tatresponsibilityassignment')),
            ],
            options={
                'verbose_name': 'TAT action task',
                'verbose_name_plural': 'TAT action tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TatResponsibilityBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(default=1)),
                ('threshold_percent', models.PositiveSmallIntegerField(default=100, help_text='Existing SLA percentage at which this backup receives a private alert.')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.tatresponsibilityassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_tat_responsibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAT responsibility backup',
                'verbose_name_plural': 'TAT responsibility backups',
                'ordering': ['rank', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TatActionTaskLocator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tat_task_locators', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locators', to='core.tatactiontask')),
            ],
            options={
                'verbose_name': 'TAT task locator',
                'verbose_name_plural': 'TAT task locators',
                'indexes': [models.Index(fields=['task', 'recipient', 'expires_at'], name='core_tatact_task_id_c2af02_idx')],
            },
        ),
        migrations.CreateModel(
            name='TatActionTaskRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('primary', 'Primary'), ('backup', 'Backup'), ('role', 'Role member')], max_length=16)),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('threshold_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inbox_status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('acted', 'Acted'), ('superseded', 'Superseded')], db_index=True, default='unread', max_length=16)),
                ('delivery_state', models.CharField(choices=[('pending', 'Pending'), ('shadow', 'Shadow'), ('delivered', 'Delivered'), ('unreachable', 'Unreachable'), ('retry', 'Retry'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('deliver_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivery_attempts', models.PositiveSmallIntegerField(default=0)),
                ('telegram_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('delivery_error', models.CharField(blank=True, default='', max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='core.tatactiontask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tat_action_task_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TAT task recipient',
                'verbose_name_plural': 'TAT task recipients',
                'ordering': ['task', 'rank', 'created_at'],
                'indexes': [models.Index(fields=['user', 'inbox_status', 'created_at'], name='core_tatact_user_id_e0c060_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'user'), name='unique_tat_task_recipient')],
            },
        ),
        migrations.CreateModel(
            name='TatGroupExceptionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_role', models.CharField(max_length=80)),
                ('telegram_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('unresolved_count', models.PositiveIntegerField(default=0)),
                ('oldest_task_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tat_group_exception_statuses', to='core.groupsheetconfiguration')),
            ],
            options={
                'verbose_name': 'TAT group delivery exception',
                'verbose_name_plural': 'TAT group delivery exceptions',
                'constraints': [models.UniqueConstraint(fields=('group_configuration', 'responsible_role'), name='unique_tat_group_role_exception')],
            },
        ),
        migrations.AddIndex(
            model_name='tatresponsibilityassignment',
            index=models.Index(fields=['group_configuration', 'branch', 'role', 'active'], name='core_tatres_group_c_2b48dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='tatresponsibilityassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('group_configuration', 'branch', 'role', 'product_key', 'stage_key'), name='unique_active_tat_responsibility'),
        ),
        migrations.AddIndex(
            model_name='tatactiontask',
            index=models.Index(fields=['case', 'status', 'created_at'], name='core_tatact_case_id_571cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='tatactiontask',
            index=models.Index(fields=['group_configuration', 'responsible_role', 'status'], name='core_tatact_group_c_6a36ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='tatactiontask',
            constraint=models.UniqueConstraint(fields=('case', 'stage_key', 'case_revision'), name='unique_tat_task_case_stage_revision'),
        ),
        migrations.AddConstraint(
            model_name='tatresponsibilitybackup',
            constraint=models.UniqueConstraint(fields=('assignment', 'rank'), name='unique_tat_backup_rank'),
        ),
        migrations.AddConstraint(
            model_name='tatresponsibilitybackup',
            constraint=models.UniqueConstraint(fields=('assignment', 'user'), name='unique_tat_backup_user'),
        ),
        migrations.AddConstraint(
            model_name='tatresponsibilitybackup',
            constraint=models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='tat_backup_rank_positive'),
        ),
        migrations.AddConstraint(
            model_name='tatresponsibilitybackup',
            constraint=models.CheckConstraint(condition=models.Q(('threshold_percent__gte', 1)), name='tat_backup_threshold_positive'),
        ),
    ]
