# Generated by Django 5.1.6 on 2026-08-22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


CANONICAL_STAGE_ROLES = {
    'mpesa_to_admin': 'BRO',
    'mpesa_verified': 'BUSINESS_ADMIN',
    'ca_analysis_sent': 'CA',
    'bro_response': 'BRO',
    'valuation_ready': 'BM',
    'bm_tat_request': 'BM',
    'tat_scheduled': 'SECRETARY',
    'tat_held': 'SECRETARY',
    'decision': 'CHAIR',
    'minutes_shared': 'SECRETARY',
    'sanctions': 'LOAN_APPROVER',
    'bro_applied': 'BRO',
    'disbursement_register': 'BUSINESS_ADMIN',
    'register_approved': 'LOAN_APPROVER',
    'disbursement': 'FINANCE',
    'bm_response': 'BM',
}


def disable_conflicting_stage_routes(apps, schema_editor):
    Assignment = apps.get_model('core', 'TatResponsibilityAssignment')
    Event = apps.get_model('core', 'TatResponsibilityEvent')
    for assignment in Assignment.objects.exclude(stage_key='').iterator():
        expected_role = CANONICAL_STAGE_ROLES.get(str(assignment.stage_key or '').strip())
        current_role = str(assignment.role or '').strip().upper()
        if expected_role and current_role == expected_role:
            continue
        before = {
            'id': str(assignment.pk),
            'group_configuration_id': assignment.group_configuration_id,
            'branch': assignment.branch,
            'role': assignment.role,
            'product_key': assignment.product_key,
            'stage_key': assignment.stage_key,
            'primary_user_id': assignment.primary_user_id,
            'active': assignment.active,
        }
        was_active = assignment.active
        if was_active:
            Assignment.objects.filter(pk=assignment.pk).update(active=False)
        reason = (
            f'Legacy stage route expected role {expected_role}; stored role was {current_role}.'
            if expected_role
            else 'Legacy stage route uses a stage not recognized by the migration catalogue.'
        )
        Event.objects.create(
            assignment_id=assignment.pk,
            assignment_id_snapshot=assignment.pk,
            action='migration_review',
            reason=reason,
            before_snapshot=before,
            after_snapshot={**before, 'active': False},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_tatprivatealertconnection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TatResponsibilityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_id_snapshot', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('migration_review', 'Disabled for migration review')], db_index=True, max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tat_responsibility_events', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.tatresponsibilityassignment')),
            ],
            options={
                'verbose_name': 'TAT responsibility event',
                'verbose_name_plural': 'TAT responsibility events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment_id_snapshot', 'created_at'], name='tat_resp_evt_assign_idx')],
            },
        ),
        migrations.RunPython(disable_conflicting_stage_routes, migrations.RunPython.noop),
    ]
