# Generated by Django 5.1.6 on 2026-08-25 16:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_commercial_catalogue(apps, schema_editor):
    DataField = apps.get_model('core', 'OriginationDataField')
    DataFieldEvent = apps.get_model('core', 'OriginationDataFieldEvent')
    choices = {
        'repayment_tenor_unit': [
            {'code': 'week', 'label': 'Weeks'}, {'code': 'month', 'label': 'Months'},
        ],
        'contract_currency': [{'code': 'kes', 'label': 'KES'}],
        'contract_interest_method': [
            {'code': 'flat', 'label': 'Flat rate'},
            {'code': 'reducing', 'label': 'Reducing balance'},
        ],
        'contract_interest_rate_period': [
            {'code': 'monthly', 'label': 'Monthly'}, {'code': 'annual', 'label': 'Annual'},
        ],
        'contract_repayment_frequency': [
            {'code': 'weekly', 'label': 'Weekly'},
            {'code': 'fortnightly', 'label': 'Fortnightly'},
            {'code': 'monthly', 'label': 'Monthly'},
        ],
    }
    loan_fees_structure = {
        'min_items': 0, 'max_items': 20,
        'columns': [
            {'key': 'fee_key', 'label': 'Fee', 'type': 'text', 'required': True,
             'validation': {'max_length': 80}, 'editable': False},
            {'key': 'fee_label', 'label': 'Fee label', 'type': 'text', 'required': True,
             'validation': {'max_length': 160}, 'editable': False},
            {'key': 'collection_mode', 'label': 'Collection', 'type': 'choice', 'required': True,
             'options': [
                 {'code': 'upfront', 'label': 'Upfront'},
                 {'code': 'financed', 'label': 'Financed'},
             ], 'editable': False},
            {'key': 'amount', 'label': 'Amount', 'type': 'money', 'required': True,
             'validation': {'min': '0'}},
        ],
    }
    specs = [
        ('loan_amount', 'Loan Amount', 'money', 'metric'),
        ('repayment_tenor', 'Repayment Tenor', 'number', 'dimension'),
        ('repayment_tenor_unit', 'Tenor Unit', 'choice', 'dimension'),
        ('contract_currency', 'Currency', 'choice', 'dimension'),
        ('contract_interest_rate_percent', 'Interest Rate (%)', 'number', 'metric'),
        ('contract_interest_method', 'Interest Method', 'choice', 'dimension'),
        ('contract_interest_rate_period', 'Interest Rate Period', 'choice', 'dimension'),
        ('contract_repayment_frequency', 'Repayment Frequency', 'choice', 'dimension'),
        ('installment_count', 'Number of Installments', 'number', 'metric'),
        ('installment_amount', 'Regular Installment Amount', 'money', 'metric'),
        ('final_installment_amount', 'Final Installment Amount', 'money', 'metric'),
        ('financed_principal_amount', 'Financed Principal', 'money', 'metric'),
        ('total_interest_amount', 'Total Interest', 'money', 'metric'),
        ('total_repayment_amount', 'Total Repayment', 'money', 'metric'),
        ('financed_fee_total', 'Financed Fees Total', 'money', 'metric'),
        ('upfront_fee_total', 'Upfront Fees Total', 'money', 'metric'),
        ('loan_fees', 'Loan Fees', 'repeating_group', 'unavailable'),
    ]
    for key, label, data_type, reporting_use in specs:
        defaults = {
            'label': label, 'aliases': [], 'category': 'Commercial Terms',
            'data_type': data_type, 'source_type': 'user_input',
            'sensitivity': 'financial', 'masking_policy': 'partial',
            'reporting_use': reporting_use, 'export_allowed': False,
            'help_text': 'Enter the exact commercial value agreed for this application.',
            'choice_options': choices.get(key, []),
            'structure_schema': loan_fees_structure if key == 'loan_fees' else {},
            'active': True,
        }
        field = DataField.objects.filter(key=key).first()
        created = field is None
        changed = []
        if created:
            field = DataField.objects.create(key=key, **defaults)
        else:
            if field.data_type != data_type:
                raise RuntimeError(
                    f'Cannot seed commercial field {key}: existing type is {field.data_type}, expected {data_type}.',
                )
            # Preserve deliberately curated labels, aliases, reporting and
            # masking governance. Only enforce properties required for the
            # officer-entered contract and merge missing structural choices.
            for name in ('source_type', 'sensitivity', 'active'):
                if getattr(field, name) != defaults[name]:
                    setattr(field, name, defaults[name])
                    changed.append(name)
            if data_type == 'choice':
                existing = list(field.choice_options or [])
                existing_codes = {str(item.get('code') or '') for item in existing}
                for option in choices.get(key, []):
                    if option['code'] not in existing_codes:
                        existing.append(option)
                        changed.append('choice_options')
                field.choice_options = existing
            if data_type == 'repeating_group' and not field.structure_schema:
                field.structure_schema = loan_fees_structure
                changed.append('structure_schema')
            if changed:
                field.save()
        if created or changed:
            DataFieldEvent.objects.create(
                data_field=field,
                action='commercial_contract_seeded' if created else 'commercial_contract_governance_updated',
                metadata={
                    'key': key, 'contract_version': 1, 'migration': '0133',
                    'changed_fields': changed,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_invoice_review_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(seed_commercial_catalogue, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productversion',
            name='quote_tenor_field_key',
            field=models.SlugField(default='repayment_tenor', help_text='Origination/workflow variable containing the numeric tenor.', max_length=80),
        ),
        migrations.CreateModel(
            name='OriginationCommercialException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_revision', models.PositiveIntegerField()),
                ('entered_terms_sha256', models.CharField(max_length=64)),
                ('expected_quote_sha256', models.CharField(max_length=64)),
                ('covered_mismatch_codes', models.JSONField(default=list)),
                ('reason', models.TextField()),
                ('approval_reference', models.CharField(max_length=255)),
                ('approved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_exceptions', to='core.loanoriginationapplication')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_origination_commercial_exceptions', to=settings.AUTH_USER_MODEL)),
                ('product_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origination_commercial_exceptions', to='core.productversion')),
            ],
            options={
                'verbose_name': 'Origination commercial exception',
                'verbose_name_plural': 'Origination commercial exceptions',
                'ordering': ['-approved_at', 'id'],
                'indexes': [models.Index(fields=['application', 'application_revision'], name='orig_comm_exception_rev_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'application_revision', 'entered_terms_sha256', 'expected_quote_sha256'), name='unique_origination_commercial_exception')],
            },
        ),
    ]
