# Generated by Django 5.1.6 on 2026-08-26 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_origination_commercial_terms_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppDiagnosticDailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('workflow', models.CharField(db_index=True, max_length=40)),
                ('surface', models.CharField(db_index=True, max_length=40)),
                ('platform', models.CharField(db_index=True, max_length=16)),
                ('release', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('classification', models.CharField(db_index=True, max_length=40)),
                ('network_bucket', models.CharField(db_index=True, default='unknown', max_length=16)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mini App diagnostic daily aggregate',
                'verbose_name_plural': 'Mini App diagnostic daily aggregates',
                'ordering': ['-date', 'workflow', 'platform', 'classification'],
                'constraints': [models.UniqueConstraint(fields=('date', 'workflow', 'surface', 'platform', 'release', 'classification', 'network_bucket'), name='unique_miniapp_diagnostic_daily_rollup')],
            },
        ),
        migrations.CreateModel(
            name='MiniAppDiagnosticSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_session_uuid', models.UUIDField(db_index=True, unique=True)),
                ('workflow', models.CharField(choices=[('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40)),
                ('surface', models.CharField(db_index=True, max_length=40)),
                ('release', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('platform', models.CharField(db_index=True, default='other', max_length=16)),
                ('network_bucket', models.CharField(db_index=True, default='unknown', max_length=16)),
                ('device_memory_bucket', models.CharField(db_index=True, default='unknown', max_length=16)),
                ('classification', models.CharField(choices=[('active_visible', 'Active and visible'), ('backgrounded', 'Backgrounded'), ('backgrounded_not_resumed', 'Backgrounded and not resumed'), ('intentional_close', 'Intentional close'), ('client_error_suspected', 'Client error suspected'), ('startup_failure', 'Startup failure'), ('navigation_or_native_dismissal', 'Navigation or native dismissal'), ('stale_unconfirmed', 'Stale and unconfirmed'), ('abrupt_unknown_confirmed', 'Abrupt unknown, confirmed on later launch')], db_index=True, default='active_visible', max_length=40)),
                ('last_visibility', models.CharField(default='visible', max_length=12)),
                ('recovered_on_later_launch', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_signal_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniapp_diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mini App diagnostic session',
                'verbose_name_plural': 'Mini App diagnostic sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MiniAppDiagnosticEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_event_uuid', models.UUIDField()),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('route', models.CharField(blank=True, default='', max_length=80)),
                ('action', models.CharField(blank=True, default='', max_length=80)),
                ('visibility', models.CharField(default='visible', max_length=12)),
                ('online', models.BooleanField(default=True)),
                ('network_bucket', models.CharField(default='unknown', max_length=16)),
                ('status_bucket', models.CharField(blank=True, default='', max_length=24)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.miniappdiagnosticsession')),
            ],
            options={
                'verbose_name': 'Mini App diagnostic event',
                'verbose_name_plural': 'Mini App diagnostic events',
                'ordering': ['session', 'elapsed_ms', 'recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='miniappdiagnosticsession',
            index=models.Index(fields=['workflow', 'platform', 'started_at'], name='core_miniap_workflo_719f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='miniappdiagnosticsession',
            index=models.Index(fields=['classification', 'started_at'], name='core_miniap_classif_317189_idx'),
        ),
        migrations.AddIndex(
            model_name='miniappdiagnosticevent',
            index=models.Index(fields=['session', 'recorded_at'], name='core_miniap_session_4ba2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='miniappdiagnosticevent',
            index=models.Index(fields=['event_type', 'recorded_at'], name='core_miniap_event_t_71f2a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='miniappdiagnosticevent',
            constraint=models.UniqueConstraint(fields=('session', 'client_event_uuid'), name='unique_miniapp_diagnostic_client_event'),
        ),
    ]
