# Generated by Django 5.1.6 on 2026-08-27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_origination_frozen_unsigned_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginationConsentPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', max_length=16)),
                ('packet_clause', models.TextField()),
                ('signer_consent_text', models.TextField()),
                ('signer_completion_text', models.TextField()),
                ('resigning_text', models.TextField()),
                ('content_sha256', models.CharField(editable=False, max_length=64, unique=True)),
                ('approval_reference', models.CharField(max_length=160)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='OriginationSigningActionInvalidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=1000)),
                ('request_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='originationsigningaction',
            name='unique_origination_signing_slot_action',
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='final_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='final_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_reviewed_loan_origination_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='native_consent_attestation_reference',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='native_consent_attested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='native_consent_attested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attested_native_origination_consent_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originationsigningaction',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='core.originationsigningaction'),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='conditional_approval',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='consent_policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='final_approved_signed_document_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='final_decision',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='final_review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='final_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='final_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_reviewed_origination_signing_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanoriginationapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for review'), ('reviewed', 'Reviewed'), ('signing_pending', 'Signing pending'), ('partially_signed', 'Partially signed'), ('fully_signed', 'Fully signed'), ('signed_pending_approval', 'Signed — pending JBL approval'), ('approved', 'Approved and locked'), ('correction_required', 'Correction required'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='originationcorrectionitem',
            name='target_type',
            field=models.CharField(choices=[('field', 'Application field'), ('requirement', 'Product requirement'), ('document_field', 'Supporting-document field'), ('signature_slot', 'Signature slot')], max_length=20),
        ),
        migrations.AddField(
            model_name='originationconsentpolicyversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_origination_consent_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originationconsentpolicyversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_origination_consent_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originationconsentpolicyversion',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retired_origination_consent_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='originationdocumenttemplate',
            name='native_consent_policy',
            field=models.ForeignKey(blank=True, help_text='Approved consent wording embedded directly in this immutable source PDF.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='native_document_templates', to='core.originationconsentpolicyversion'),
        ),
        migrations.AddField(
            model_name='originationsigningpackage',
            name='consent_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signing_packages', to='core.originationconsentpolicyversion'),
        ),
        migrations.AddField(
            model_name='originationsigningactioninvalidation',
            name='action',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invalidation', to='core.originationsigningaction'),
        ),
        migrations.AddField(
            model_name='originationsigningactioninvalidation',
            name='invalidated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invalidated_origination_signing_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='originationconsentpolicyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='one_active_origination_consent_policy'),
        ),
    ]
