# Generated by Django 5.1.6 on 2026-08-28 20:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_staff_lifecycle_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compliance_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complianceauditevent',
            name='authority_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compliance_audit_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserHardDeletionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('actor_label', models.CharField(max_length=255)),
                ('reason_category', models.CharField(choices=[('departed_staff', 'Departed staff'), ('duplicate_account', 'Duplicate account'), ('security_incident', 'Security incident'), ('legal_request', 'Legal request'), ('test_data_cleanup', 'Test-data cleanup'), ('other', 'Other')], max_length=32)),
                ('reason_note', models.TextField(blank=True, default='')),
                ('target_count', models.PositiveIntegerField()),
                ('preview_fingerprint', models.CharField(max_length=64)),
                ('result_counts', models.JSONField(default=dict)),
                ('coverage_gaps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user hard-deletion batch',
                'verbose_name_plural': 'user hard-deletion batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedUserIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('username', models.CharField(max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('was_active', models.BooleanField(default=False)),
                ('was_staff', models.BooleanField(default=False)),
                ('was_superuser', models.BooleanField(default=False)),
                ('relationship_manifest', models.JSONField(default=list)),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deleted_identities', to='core.userharddeletionbatch')),
            ],
            options={
                'verbose_name': 'deleted user identity',
                'verbose_name_plural': 'deleted user identities',
                'ordering': ['-deleted_at'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'original_user_id'), name='unique_deleted_user_per_batch')],
            },
        ),
    ]
