# Generated by Django 5.1.6 on 2026-08-29 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_direct_superuser_staff_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTelegramOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_activation', 'Pending Telegram activation'), ('delivering', 'Delivering Telegram onboarding'), ('attention_required', 'Attention required'), ('complete', 'Complete')], db_index=True, default='pending_activation', max_length=32)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_onboarding', to='core.stafflifecyclechangeplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffTelegramGroupInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Invite ready'), ('sent', 'Sent'), ('joined', 'Joined'), ('attention_required', 'Attention required'), ('expired', 'Expired')], db_index=True, default='pending', max_length=32)),
                ('launcher_ready_at', models.DateTimeField(blank=True, null=True)),
                ('invite_created_at', models.DateTimeField(blank=True, null=True)),
                ('invite_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invite_digest', models.CharField(blank=True, default='', max_length=64)),
                ('pending_invite_url', models.TextField(blank=True, default='')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_onboarding_invitations', to='core.groupsheetconfiguration')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations', to='core.stafftelegramonboarding')),
            ],
            options={
                'ordering': ['group_configuration__display_name', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('onboarding', 'group_configuration'), name='unique_staff_onboarding_group_invite')],
            },
        ),
    ]
