# Generated by Django 5.1.6 on 2026-08-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_staff_telegram_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatnotificationprocessorrun',
            name='trigger_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tatnotificationprocessorrun',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tatnotificationprocessorrun',
            name='trigger_source',
            field=models.CharField(choices=[('scheduled', 'Scheduled runner'), ('admin', 'Manual Admin run')], db_index=True, default='scheduled', max_length=16),
        ),
        migrations.AddField(
            model_name='tatnotificationprocessorrun',
            name='triggered_by_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tatnotificationprocessorrun',
            name='triggered_by_username_snapshot',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tatprivatealertconnection',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tatprivatealertconnection',
            name='last_disconnect_request_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tatprivatealertconnection',
            name='last_test_request_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='tatprivatealertconnection',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('unconnected', 'Never connected'), ('disconnected', 'Disconnected by user'), ('blocked', 'Bot blocked or permission withdrawn'), ('temporary_failure', 'Temporarily failing')], db_index=True, default='unknown', max_length=24),
        ),
        migrations.CreateModel(
            name='TatPrivateAlertConnectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user_id_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('actor_id_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('actor_username_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('event_type', models.CharField(choices=[('connected', 'Connected'), ('connect_failed', 'Connection test failed'), ('disconnected', 'Disconnected'), ('test_succeeded', 'Test message delivered'), ('test_failed', 'Test message failed'), ('delivery_succeeded', 'Task alert delivered'), ('delivery_failed', 'Task alert failed')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('connected', 'Connected'), ('unconnected', 'Never connected'), ('disconnected', 'Disconnected by user'), ('blocked', 'Bot blocked or permission withdrawn'), ('temporary_failure', 'Temporarily failing')], max_length=24)),
                ('source', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('detail_code', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.tatprivatealertconnection')),
            ],
            options={
                'verbose_name': 'TAT private alert connection event',
                'verbose_name_plural': 'TAT private alert connection events',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('request_id',), name='unique_tat_alert_event_request')],
            },
        ),
        migrations.AddConstraint(
            model_name='tatnotificationprocessorrun',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('request_id',), name='unique_tat_notify_run_request'),
        ),
    ]
