# Generated by Django 5.1.6 on 2026-08-29 17:51

from django.db import migrations, models


TAT_ROLES = (
    'BRO', 'BUSINESS_ADMIN', 'CA', 'BM', 'SECRETARY', 'CHAIR',
    'LOAN_APPROVER', 'FINANCE', 'IT', 'MANAGEMENT',
)


def apply_tat_correction_policy(apps, schema_editor):
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    detail_roles = {'BRO', 'BUSINESS_ADMIN', 'IT'}
    for role in TAT_ROLES:
        detail_allowed = role in detail_roles
        Capability.objects.update_or_create(
            workflow='tat_tracker', role=role, capability_key='tat.case.correct',
            defaults={
                'enabled': detail_allowed,
                'effect': 'allow' if detail_allowed else 'deny',
            },
        )
        stage_allowed = role == 'IT'
        Capability.objects.update_or_create(
            workflow='tat_tracker', role=role, capability_key='tat.stage.correct',
            defaults={
                'enabled': stage_allowed,
                'effect': 'allow' if stage_allowed else 'deny',
            },
        )


def restore_previous_tat_correction_policy(apps, schema_editor):
    Capability = apps.get_model('core', 'WorkflowRoleCapability')
    previous_roles = {'BUSINESS_ADMIN', 'IT'}
    for role in TAT_ROLES:
        allowed = role in previous_roles
        Capability.objects.update_or_create(
            workflow='tat_tracker', role=role, capability_key='tat.case.correct',
            defaults={'enabled': allowed, 'effect': 'allow' if allowed else 'deny'},
        )
    Capability.objects.filter(
        workflow='tat_tracker', capability_key='tat.stage.correct',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_tat_private_alert_controls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflifecyclechangeplan',
            name='action',
            field=models.CharField(choices=[('onboard', 'Onboard staff'), ('add_workflow_access', 'Add workflow or group access'), ('access_change', 'Change role or scope'), ('transfer', 'Transfer staff'), ('leave', 'Temporary leave'), ('return', 'Return from leave'), ('offboard', 'Immediate offboarding'), ('telegram_identity_reset', 'Reset Telegram identity')], db_index=True, max_length=32),
        ),
        migrations.RunPython(
            apply_tat_correction_policy,
            restore_previous_tat_correction_policy,
        ),
    ]
