# Generated by Django 5.1.6 on 2026-08-31 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def normalize_legacy_job_rows(apps, schema_editor):
    Batch = apps.get_model('core', 'ComplaintCaseImportBatch')
    Item = apps.get_model('core', 'ComplaintCaseImportItem')
    Batch.objects.filter(status='processing').update(status='running')
    Batch.objects.filter(status='complete').update(status='completed')
    for item in Item.objects.exclude(parsed_message_id=None).iterator(chunk_size=500):
        item.status = 'created'
        item.outcome_reference = str(item.parsed_message_id)[:128]
        item.save(update_fields=['status', 'outcome_reference'])


def reverse_legacy_job_rows(apps, schema_editor):
    Batch = apps.get_model('core', 'ComplaintCaseImportBatch')
    Batch.objects.filter(status='running').update(status='processing')
    Batch.objects.filter(status='completed').update(status='complete')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_order_approval_request_replay'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurableJobRunnerHeartbeat',
            fields=[
                ('runner_key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('heartbeat_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'durable job runner heartbeat',
                'verbose_name_plural': 'durable job runner heartbeats',
            },
        ),
        migrations.AddField(
            model_name='complaintcaseimportbatch',
            name='analysis_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='complaintcaseimportbatch',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaintcaseimportbatch',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='complaintcaseimportbatch',
            name='last_error_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='complaintcaseimportbatch',
            name='lease_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='complaintcaseimportbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaintcaseimportbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='last_error_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='normalized_entry_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='outcome_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('created', 'Created'), ('matched', 'Matched existing'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AddField(
            model_name='complaintcaseimportitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(normalize_legacy_job_rows, reverse_legacy_job_rows),
        migrations.AlterField(
            model_name='complaintcaseimportbatch',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('partial', 'Partial'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='complaintcaseimportitem',
            name='parsed_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_import_item', to='core.parsedmessage'),
        ),
        migrations.AlterField(
            model_name='tatrepairjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32),
        ),
        migrations.AddIndex(
            model_name='complaintcaseimportbatch',
            index=models.Index(fields=['status', 'created_at'], name='cc_import_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintcaseimportitem',
            index=models.Index(fields=['batch', 'status', 'source_index'], name='cc_item_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tatrepairjob',
            index=models.Index(fields=['status', 'created_at'], name='tat_repair_status_created_idx'),
        ),
    ]
