# Generated by Django 5.1.6 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_durablejobrunnerheartbeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEndpointThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=80)),
                ('key_hash', models.CharField(max_length=64)),
                ('window_started_at', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'public endpoint throttle bucket',
                'verbose_name_plural': 'public endpoint throttle buckets',
                'indexes': [models.Index(fields=['scope', 'window_started_at'], name='core_public_scope_52c7ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash', 'window_started_at'), name='unique_public_endpoint_throttle_window')],
            },
        ),
    ]
