# Generated by Django 5.1.6 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_publicendpointthrottlebucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReleaseAudit',
            fields=[
                ('release_id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('backup_reference', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=160)),
                ('environment', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('preflight_passed', 'Preflight passed'), ('post_check_failed', 'Post-migration check failed'), ('bootstrap_failed', 'Superuser bootstrap failed'), ('migration_failed', 'Migration failed')], max_length=32)),
                ('migration_names', models.JSONField(default=list)),
                ('migration_plan_sha256', models.CharField(max_length=64)),
                ('readiness_results', models.JSONField(default=dict)),
                ('attempt_history', models.JSONField(default=list)),
                ('post_migration_check_passed', models.BooleanField(default=False)),
                ('superuser_bootstrap_result', models.CharField(blank=True, default='', max_length=32)),
                ('failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField()),
                ('migrations_completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'production release audit',
                'verbose_name_plural': 'production release audits',
                'ordering': ['-started_at'],
            },
        ),
    ]
