# Generated by Django 5.2.17 on 2026-09-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_requisition_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdocument',
            name='status',
            field=models.CharField(choices=[('preview', 'Preview'), ('pending_review', 'Pending Head of Rural review'), ('reviewed', 'Reviewed'), ('final', 'Final'), ('awaiting_scan', 'Awaiting signed scan'), ('completed', 'Completed'), ('superseded', 'Superseded'), ('failed', 'Failed')], db_index=True, default='preview', max_length=32),
        ),
    ]
