# Generated by Django 5.1.6 on 2026-09-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0188_media_attachment_portal_operation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionbatch',
            name='fulfillment_partner',
            field=models.CharField(choices=[('HB', 'HB'), ('ECOCONSERVE', 'Eco-conserve')], db_index=True, default='HB', help_text='Immutable partner route selected from the case fields at order finalization.', max_length=20),
        ),
        migrations.AddField(
            model_name='requisitionbatch',
            name='requisition_template',
            field=models.ForeignKey(blank=True, help_text='Exact validated template retained for this finalized order.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_batches', to='core.requisitiontemplate'),
        ),
        migrations.AddField(
            model_name='requisitiontemplate',
            name='fulfillment_partner',
            field=models.CharField(choices=[('HB', 'HB'), ('ECOCONSERVE', 'Eco-conserve')], db_index=True, default='HB', help_text='Partner whose branded requisition workbook this template generates.', max_length=20),
        ),
    ]
