# Generated by Django 5.2.17 on 2026-10-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_physical_scan_replacement'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='OriginationDataField',
                ),
                migrations.DeleteModel(
                    name='OriginationDataFieldEvent',
                ),
                migrations.DeleteModel(
                    name='OriginationProductDefinition',
                ),
                migrations.DeleteModel(
                    name='OriginationProductDefinitionEvent',
                ),
                migrations.DeleteModel(
                    name='OriginationFieldReviewIssue',
                ),
                migrations.DeleteModel(
                    name='OriginationDocumentTemplate',
                ),
                migrations.DeleteModel(
                    name='OriginationDocumentProductEligibility',
                ),
                migrations.DeleteModel(
                    name='OriginationProductDocumentAssignment',
                ),
                migrations.DeleteModel(
                    name='OriginationDocumentTemplateEvent',
                ),
                migrations.DeleteModel(
                    name='OriginationTemplateConfigurationRevision',
                ),
                migrations.DeleteModel(
                    name='LoanOriginationApplication',
                ),
                migrations.DeleteModel(
                    name='OriginationCommercialException',
                ),
                migrations.DeleteModel(
                    name='OriginationReportingValue',
                ),
                migrations.DeleteModel(
                    name='OriginationApplicationEvent',
                ),
                migrations.DeleteModel(
                    name='OriginationReviewerNotice',
                ),
                migrations.DeleteModel(
                    name='OriginationCorrectionRequest',
                ),
                migrations.DeleteModel(
                    name='OriginationCorrectionItem',
                ),
                migrations.DeleteModel(
                    name='OriginationRequirementEvidence',
                ),
                migrations.DeleteModel(
                    name='OriginationApplicationDocument',
                ),
                migrations.DeleteModel(
                    name='OriginationConsentPolicyVersion',
                ),
                migrations.DeleteModel(
                    name='OriginationSigningPackage',
                ),
                migrations.DeleteModel(
                    name='OriginationStampAsset',
                ),
                migrations.DeleteModel(
                    name='OriginationSignerSession',
                ),
                migrations.DeleteModel(
                    name='OriginationOtpChallenge',
                ),
                migrations.DeleteModel(
                    name='OriginationSigningRequestEvent',
                ),
                migrations.DeleteModel(
                    name='OriginationSigningAction',
                ),
                migrations.DeleteModel(
                    name='OriginationSigningActionInvalidation',
                ),
            ],
        ),
    ]
