# Generated by Django 5.2.17 on 2026-10-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0199_origination_domain_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrolchangerequest',
            name='workflow',
            field=models.CharField(blank=True, choices=[('loan_origination', 'Loan Origination'), ('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='workflow',
            field=models.CharField(choices=[('loan_origination', 'Loan Origination'), ('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='documentsignoffpolicy',
            name='workflow',
            field=models.CharField(choices=[('loan_origination', 'Loan Origination'), ('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], default='jawabu_portal', editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='emergencyaccessgrant',
            name='workflow',
            field=models.CharField(choices=[('loan_origination', 'Loan Origination'), ('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='miniappdiagnosticsession',
            name='workflow',
            field=models.CharField(choices=[('loan_origination', 'Loan Origination'), ('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='workflowrolecapability',
            name='workflow',
            field=models.CharField(choices=[('loan_origination', 'Loan Origination'), ('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='workflowrolecapabilityauditevent',
            name='workflow',
            field=models.CharField(choices=[('loan_origination', 'Loan Origination'), ('jawabu_portal', 'Jawabu Portal'), ('complaint_cases', 'Complaint Cases'), ('tat_tracker', 'TAT Tracker'), ('spin_credit_analysis', 'SPIN / Credit Analysis')], db_index=True, max_length=40),
        ),
    ]
