# Generated by Django 5.1.6 on 2026-10-06 12:28

import django.db.models.deletion
from django.db import migrations, models


def require_unique_numbers(apps, schema_editor):
    Batch = apps.get_model('core', 'RequisitionBatch')
    duplicates = Batch.objects.using(schema_editor.connection.alias).values('order_number').annotate(n=models.Count('pk')).filter(n__gt=1)
    if duplicates.exists():
        raise RuntimeError('Rollback blocked: order numbers were reused. Reconcile historical display numbers before restoring the legacy unique constraint.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_credit_decision_voice_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabufarmermaster',
            name='requisition_batch',
            field=models.ForeignKey(blank=True, db_comment='Exact current order workspace; display numbers may be reused after cancellation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to='core.requisitionbatch'),
        ),
        migrations.AlterField(
            model_name='requisitionbatch',
            name='order_number',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='requisitionbatch',
            name='status',
            field=models.CharField(choices=[('preview', 'Preview'), ('generated', 'Generated'), ('invoices_uploaded', 'Invoices Uploaded'), ('partially_invoiced', 'Partially Invoiced'), ('completed', 'Completed'), ('needs_review', 'Needs Review'), ('cancelled', 'Cancelled')], db_index=True, default='generated', max_length=32),
        ),
        migrations.RunPython(migrations.RunPython.noop, require_unique_numbers),
    ]
