# Generated by Django 5.1.6 on 2026-09-19 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0183_complaint_voice_transcription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBiogasAction',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable HomeBiogas action identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_order_number', models.CharField(db_comment='Immutable staff-facing order number captured at release.', max_length=128)),
                ('source_requisition_version', models.PositiveIntegerField(db_comment='Exact finalized requisition version captured at release.')),
                ('installation_status', models.CharField(choices=[('needs_planning', 'Needs planning'), ('pending_installation', 'Pending installation'), ('scheduled', 'Scheduled'), ('installed', 'Installed'), ('closed', 'Closed')], db_comment='Current server-validated installation state.', default='needs_planning', max_length=32)),
                ('installation_date', models.DateField(blank=True, db_comment='Scheduled date while scheduled, or actual completion date while installed.', null=True)),
                ('serial_number', models.CharField(blank=True, db_comment='Optional manufacturer serial number retained as text.', default='', max_length=128)),
                ('readiness_status', models.CharField(blank=True, choices=[('ready', 'Ready'), ('not_ready', 'Not ready'), ('not_confirmed', 'Not confirmed')], db_comment='Structured readiness state for pending or scheduled installation.', default='', max_length=24)),
                ('pending_installation_comment', models.TextField(blank=True, db_comment='Operational explanation while installation is pending or scheduled.', default='')),
                ('installation_report_status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('not_applicable', 'Not applicable')], db_comment='Whether the installation report was submitted to Jawabu.', default='', max_length=24)),
                ('commissioning_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('done', 'Done')], db_comment='Current commissioning state after installation.', default='', max_length=16)),
                ('commissioning_date', models.DateField(blank=True, db_comment='Scheduled date while pending, or actual completion date when commissioning is done.', null=True)),
                ('pending_commissioning_comment', models.TextField(blank=True, db_comment='Operational explanation while commissioning is pending.', default='')),
                ('revision', models.PositiveBigIntegerField(db_comment='Optimistic concurrency revision incremented by every accepted mutation.', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When the accepted requisition released this case to HomeBiogas.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='When the latest accepted HomeBiogas action was saved.')),
                ('created_by', models.ForeignKey(blank=True, db_comment='Staff actor whose accepted signoff released this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.OneToOneField(db_comment='Canonical Portal case being installed and commissioned.', on_delete=django.db.models.deletion.PROTECT, related_name='homebiogas_action', to='core.jawabufarmermaster')),
                ('source_requisition_batch', models.ForeignKey(db_comment='Exact finalized requisition batch that released this case to HomeBiogas.', on_delete=django.db.models.deletion.PROTECT, related_name='homebiogas_actions', to='core.requisitionbatch')),
                ('source_signoff', models.ForeignKey(db_comment='Accepted signed and stamped requisition scan that released this case.', on_delete=django.db.models.deletion.PROTECT, related_name='homebiogas_actions', to='core.documentphysicalsignoff')),
                ('updated_by', models.ForeignKey(blank=True, db_comment='Staff actor responsible for the latest accepted change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hb_operations_action_root',
                'db_table_comment': 'Django source of truth for post-order HomeBiogas installation and commissioning work.',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeBiogasActionEvent',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable HomeBiogas action event identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_comment='Stable machine-readable release, transition, or correction action.', max_length=48)),
                ('revision', models.PositiveBigIntegerField(db_comment='Record revision produced or observed by this event.')),
                ('actor_label', models.CharField(blank=True, db_comment='Immutable display label retained if the staff account later changes.', default='', max_length=255)),
                ('request_id', models.CharField(blank=True, db_comment='Idempotency key for user or internal retries.', default='', max_length=128)),
                ('previous_values', models.JSONField(blank=True, db_comment='Allowlisted prior operational values for audit interpretation.', default=dict)),
                ('new_values', models.JSONField(blank=True, db_comment='Allowlisted accepted operational values for audit interpretation.', default=dict)),
                ('reason', models.TextField(blank=True, db_comment='Required reason for consequential milestone corrections.', default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='When this immutable event was recorded.')),
                ('action', models.ForeignKey(db_comment='HomeBiogas record changed by this event.', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hb_operations.homebiogasaction')),
                ('actor', models.ForeignKey(blank=True, db_comment='Staff actor responsible for this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hb_operations_action_event',
                'db_table_comment': 'Append-only audit history for HomeBiogas installation and commissioning actions.',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='homebiogasaction',
            index=models.Index(fields=['installation_status', 'updated_at'], name='hb_action_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='homebiogasactionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('action', 'request_id'), name='unique_hb_action_request'),
        ),
    ]
