# Generated by Django 5.1.6 on 2026-10-05 09:23

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0200_alter_accesscontrolchangerequest_workflow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('event_id', models.CharField(db_comment='Verified Svix message identity; replay deduplication key.', max_length=100, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(db_comment='Resend email identity; no recipient address retained.', max_length=100)),
                ('event_type', models.CharField(db_comment='Allowlisted delivery event category.', max_length=40)),
                ('occurred_at', models.DateTimeField(db_comment='Signed provider event time.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Receipt time; evidence expires after 180 days.')),
            ],
            options={
                'db_table': 'report_delivery_webhook_event',
                'db_table_comment': 'Immutable verified provider event receipt, deduplicated by Svix identity; metadata retained 180 days.',
            },
        ),
        migrations.CreateModel(
            name='ApprovedRecipient',
            fields=[
                ('id', models.UUIDField(db_comment='Stable configuration identity.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch', models.CharField(blank=True, db_comment='Permitted branch; blank means all branches in the owning group.', max_length=120)),
                ('product', models.CharField(blank=True, db_comment='Permitted product code; blank means all products in the owning group.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Configuration creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last configuration change time.')),
                ('email', models.EmailField(db_comment='Explicitly approved recipient address, not a Portal identity.', max_length=254)),
                ('active', models.BooleanField(db_comment='Operator approval remains active.', default=True)),
                ('suppressed', models.BooleanField(db_comment='Bounce or complaint blocks all further messages pending IT review.', default=False)),
                ('suppression_reason', models.CharField(blank=True, db_comment='Provider event category; contains no customer data.', editable=False, max_length=40)),
                ('authorized_by', models.ForeignKey(db_comment='Approving actor whose current IT authority is rechecked before sending.', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_%(class)s_reports', to=settings.AUTH_USER_MODEL)),
                ('group_configuration', models.ForeignKey(db_comment='Owning Portal group; never inferred from an email address.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_report_configurations', to='core.groupsheetconfiguration')),
            ],
            options={
                'db_table': 'report_delivery_recipient_root',
                'db_table_comment': 'Authoritative approved email recipients and group/branch/product disclosure boundaries; retained until explicit administrative removal.',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(db_comment='Stable configuration identity.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch', models.CharField(blank=True, db_comment='Permitted branch; blank means all branches in the owning group.', max_length=120)),
                ('product', models.CharField(blank=True, db_comment='Permitted product code; blank means all products in the owning group.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Configuration creation time.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Last configuration change time.')),
                ('title', models.CharField(db_comment='Short operator-facing schedule name.', max_length=100)),
                ('preset', models.CharField(choices=[('pipeline', 'Pipeline'), ('outcomes', 'Outcomes'), ('finance', 'Finance')], db_comment='Allowlisted Portal report preset.', max_length=12)),
                ('county', models.CharField(blank=True, db_comment='Optional narrowing county filter.', max_length=120)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], db_comment='Completed Nairobi calendar period cadence.', default='daily', max_length=12)),
                ('send_time', models.TimeField(db_comment='Nairobi local dispatch time; weekly sends Monday, month/quarter on day one.', default=datetime.time(8, 0))),
                ('active', models.BooleanField(db_comment='Paused by default; runner processes only enabled schedules.', default=False)),
                ('skip_empty', models.BooleanField(db_comment='Skip genuinely empty captured reports, never generation failures.', default=False)),
                ('revision', models.PositiveIntegerField(db_comment='Configuration revision; stale queued work is blocked.', default=1, editable=False)),
                ('next_run_at', models.DateTimeField(blank=True, db_comment='Next scheduled UTC occurrence, derived from Nairobi cadence.', editable=False, null=True)),
                ('skipped_occurrences', models.PositiveIntegerField(db_comment='Older due periods deliberately skipped after downtime.', default=0, editable=False)),
                ('authorized_by', models.ForeignKey(db_comment='Approving actor whose current IT authority is rechecked before sending.', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_%(class)s_reports', to=settings.AUTH_USER_MODEL)),
                ('group_configuration', models.ForeignKey(db_comment='Owning Portal group; never inferred from an email address.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_report_configurations', to='core.groupsheetconfiguration')),
            ],
            options={
                'db_table': 'report_delivery_schedule_root',
                'db_table_comment': 'Authoritative scoped Portal report schedules; retained until administrative removal; no workflow state ownership.',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ReportDelivery',
            fields=[
                ('id', models.UUIDField(db_comment='Durable provider idempotency identity.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurrence', models.CharField(db_comment='Scheduled occurrence or client-supplied manual action UUID.', max_length=100)),
                ('configuration', models.JSONField(db_comment='Frozen group, filters, revision, report period and authorization context.', default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('retry', 'Retry'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('skipped', 'Skipped'), ('uncertain', 'Uncertain')], db_comment='Authoritative delivery state; delivered does not imply read.', default='queued', max_length=12)),
                ('payload', models.JSONField(db_comment='Exact Resend request and base64 attachments; erased after 30 days.', default=dict, editable=False)),
                ('payload_hash', models.CharField(blank=True, db_comment='SHA-256 of frozen request bytes retained as evidence.', editable=False, max_length=64)),
                ('snapshot', models.JSONField(db_comment='Captured report shared by summary/PDF/XLSX; erased after 30 days.', default=dict, editable=False)),
                ('provider_id', models.CharField(blank=True, db_comment='Resend email identity for webhook correlation.', editable=False, max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(db_comment='Bounded submission attempt count.', default=0, editable=False)),
                ('first_attempt_at', models.DateTimeField(db_comment='Start of provider 24-hour idempotency window.', editable=False, null=True)),
                ('next_attempt_at', models.DateTimeField(db_comment='Next eligible retry time.', default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(db_comment='Current worker ownership token.', editable=False, null=True)),
                ('lease_until', models.DateTimeField(db_comment='Bounded lease expiry for restart recovery.', editable=False, null=True)),
                ('error_code', models.CharField(blank=True, db_comment='Safe error category; never raw provider content.', editable=False, max_length=60)),
                ('last_event_at', models.DateTimeField(db_comment='Provider event timestamp for ordering evidence.', editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Reservation time; metadata expires after 180 days.')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Most recent status change.')),
                ('recipient', models.ForeignKey(db_comment='Single approved recipient; addresses are never shared.', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='report_delivery.approvedrecipient')),
                ('schedule', models.ForeignKey(db_comment='Schedule configuration retained for 180-day evidence.', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='report_delivery.reportschedule')),
            ],
            options={
                'db_table': 'report_delivery_message_root',
                'db_table_comment': 'Durable per-recipient report delivery and retry evidence; payload 30 days, metadata 180 days; source of truth for delivery only.',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(db_comment='Approved destination; must encompass the entire schedule scope.', on_delete=django.db.models.deletion.PROTECT, related_name='schedule_links', to='report_delivery.approvedrecipient')),
                ('schedule', models.ForeignKey(db_comment='Owning schedule.', on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='report_delivery.reportschedule')),
            ],
            options={
                'db_table': 'report_delivery_recipient_link',
                'db_table_comment': 'Explicit approved schedule membership; configuration link, retained with schedule.',
            },
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='recipients',
            field=models.ManyToManyField(related_name='schedules', through='report_delivery.ScheduleRecipient', to='report_delivery.approvedrecipient'),
        ),
        migrations.AddConstraint(
            model_name='approvedrecipient',
            constraint=models.UniqueConstraint(fields=('group_configuration', 'email', 'branch', 'product'), name='report_recipient_scope_unique'),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='report_delivery_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportdelivery',
            constraint=models.UniqueConstraint(fields=('schedule', 'recipient', 'occurrence'), name='report_delivery_occurrence_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedulerecipient',
            constraint=models.UniqueConstraint(fields=('schedule', 'recipient'), name='report_schedule_recipient_unique'),
        ),
    ]
