# Generated by Django 5.1.6 on 2026-10-05 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedrecipient',
            name='authorized_by',
            field=models.ForeignKey(db_comment='Approving actor whose current IT authority is rechecked before sending; deletion revokes delivery authority.', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_%(class)s_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='authorized_by',
            field=models.ForeignKey(db_comment='Approving actor whose current IT authority is rechecked before sending; deletion revokes delivery authority.', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_%(class)s_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportdelivery',
            index=models.Index(fields=['provider_id'], name='report_delivery_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookreceipt',
            index=models.Index(fields=['provider_id', 'occurred_at'], name='report_webhook_provider_idx'),
        ),
    ]
