# Generated by Django 5.1.6 on 2026-10-05 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_alter_accesscontrolchangerequest_workflow_and_more'),
        ('report_delivery', '0002_alter_approvedrecipient_authorized_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='approvedrecipient',
            name='report_recipient_scope_unique',
        ),
        migrations.AddField(
            model_name='approvedrecipient',
            name='workflow',
            field=models.CharField(choices=[('jawabu_portal', 'Portal'), ('tat_tracker', 'TAT'), ('complaint_cases', 'Complaints')], db_comment='Owning report workflow; approvals never transfer between Mini Apps.', default='jawabu_portal', max_length=24),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='workflow',
            field=models.CharField(choices=[('jawabu_portal', 'Portal'), ('tat_tracker', 'TAT'), ('complaint_cases', 'Complaints')], db_comment='Owning report workflow; approvals never transfer between Mini Apps.', default='jawabu_portal', max_length=24),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='preset',
            field=models.CharField(choices=[('pipeline', 'Pipeline'), ('outcomes', 'Outcomes'), ('finance', 'Finance'), ('tat', 'Tat'), ('complaints', 'Complaints')], db_comment='Allowlisted report preset for the owning workflow.', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='approvedrecipient',
            constraint=models.UniqueConstraint(fields=('workflow', 'group_configuration', 'email', 'branch', 'product'), name='report_recipient_scope_unique'),
        ),
    ]
