"""
URL routing for the core API.
"""
from django.urls import path
from .auth_views import telegram_session_login
from .views import (
    telegram_webhook,
    health_check,
    readiness_check,
    jawabu_farmers_review,
    jawabu_farmers_review_commit,
    miniapp_draft,
    fca_review,
    fca_review_commit,
    order_approval_form,
    order_approval_webapp_lookup,
    order_approval_webapp_suggest,
    order_approval_webapp_submit,
    spin_form,
    spin_form_submit,
    spin_form_requests,
    spin_form_settings,
    spin_form_settings_personal,
    spin_form_complete,
    spin_form_review_update,
    spin_batch_review_resolve,
    tat_tracker_app,
    tat_tracker_bootstrap,
    tat_tracker_home,
    tat_tracker_home_fragment,
    tat_tracker_search,
    tat_tracker_search_fragment,
    tat_tracker_target_settings,
    tat_tracker_settings,
    tat_tracker_settings_personal,
    tat_tracker_settings_request,
    tat_tracker_settings_review,
    tat_tracker_create,
    tat_tracker_identity_context,
    tat_tracker_detail,
    tat_tracker_update,
    tat_signature_webhook,
    process_messages,
    resend_unsynced,
    sync_from_sheets,
)
from .portal_views import (
    portal_home,
    portal_screen,
    portal_reports_screen,
    portal_invoices_screen,
    portal_case_history_detail,
    portal_navigation,
    portal_settings,
    portal_approval_delegations,
    portal_approval_delegation_revoke,
    portal_workspace,
    portal_workspace_views,
    portal_workspace_view_detail,
    portal_workspace_view_activate,
    portal_workspace_view_startup,
    portal_workspace_case_pin,
    portal_workspace_case_unpin,
    portal_workspace_recents_clear,
    portal_dashboard,
    portal_meta,
    portal_imports,
    portal_import_stage,
    portal_import_detail,
    portal_import_archive_attempt,
    portal_reports_catalogue,
    portal_report_preview,
    portal_reporting_relationships,
    portal_reports,
    portal_report_detail,
    portal_report_archive,
    portal_report_run,
    portal_report_export,
    portal_health,
    portal_set_maintenance,
    portal_jbl_queue,
    portal_jbl_queue_fragment,
    portal_my_visits,
    portal_queue_fragment,
    portal_log_jbl_visit,
    portal_jbl_visit_draft,
    portal_complete_jbl_visit,
    portal_upload_jbl_media,
    portal_jbl_media,
    portal_preview_jbl_media,
    portal_open_jbl_media,
    portal_open_jbl_media_signed,
    portal_open_legacy_jbl_media,
    portal_clear_approval_condition,
    portal_publication_attempt,
    portal_credit_queue,
    portal_set_credit_decision,
    portal_final_review_queue,
    portal_set_final_decision,
    portal_return_for_rework,
    portal_requisition_queue,
    portal_requisition_preview,
    portal_requisition_workbook_preview,
    portal_assign_order,
    portal_requisition_generate,
    portal_requisition_download,
    portal_requisition_batches,
    portal_requisition_batches_fragment,
    portal_requisition_batch_detail,
    portal_requisition_batch_download,
    portal_requisition_batch_retry_sync,
    portal_upload_batch_invoices,
    portal_invoice_pool,
    portal_invoice_detail,
    portal_invoice_farmer_candidates,
    portal_invoice_match,
    portal_invoice_unmatch,
    portal_invoice_ignore,
    portal_invoice_restore,
    portal_invoice_bulk_action,
    portal_invoice_pool_upload,
    portal_invoice_draft_edit,
    portal_invoice_batch_confirm,
    portal_payment_readiness,
    portal_payment_candidates,
    portal_payment_selection,
    portal_payment_preview_data,
    portal_payment_document_preview,
    portal_payment_document_finalize,
    portal_payment_document_approve,
    portal_payment_document_regenerate,
    portal_document_history,
    portal_document_physical_signoff_upload,
    portal_document_physical_signoff_retry,
    portal_payment_document_detail,
    portal_all_cases,
    portal_deferred,
    portal_farmer_detail,
    portal_auth_required,
)
from .complaint_case_views import (
    complaint_cases_app,
    complaint_cases_bootstrap,
    complaint_cases_settings_personal,
    complaint_cases_create,
    complaint_cases_list,
    complaint_cases_list_fragment,
    complaint_cases_detail,
    complaint_cases_update,
)

urlpatterns = [
    path('auth/telegram/', telegram_session_login, name='telegram_session_login'),
    path('health/', health_check, name='health_check'),
    path('readiness/', readiness_check, name='readiness_check'),
    path('order-approval/', order_approval_form, name='order_approval_form'),
    path('jawabu-farmers/review/', jawabu_farmers_review, name='jawabu_farmers_review'),
    path('jawabu-farmers/review/commit/', jawabu_farmers_review_commit, name='jawabu_farmers_review_commit'),
    path('miniapp-drafts/<str:workflow>/<str:context_key>/', miniapp_draft, name='miniapp_draft'),
    path('fca/review/', fca_review, name='fca_review'),
    path('fca/review/commit/', fca_review_commit, name='fca_review_commit'),
    path('spin/', spin_form, name='spin_form'),
    path('spin/submit/', spin_form_submit, name='spin_form_submit'),
    path('spin/requests/', spin_form_requests, name='spin_form_requests'),
    path('spin/settings/', spin_form_settings, name='spin_form_settings'),
    path('spin/settings/personal/', spin_form_settings_personal, name='spin_form_settings_personal'),
    path('spin/review/update/', spin_form_review_update, name='spin_form_review_update'),
    path('spin/batch-review/resolve/', spin_batch_review_resolve, name='spin_batch_review_resolve'),
    path('spin/complete/', spin_form_complete, name='spin_form_complete'),
    path('tat-tracker/', tat_tracker_app, name='tat_tracker_app'),
    path('tat-tracker/bootstrap/', tat_tracker_bootstrap, name='tat_tracker_bootstrap'),
    path('tat-tracker/home/', tat_tracker_home, name='tat_tracker_home'),
    path('tat-tracker/home/fragment/', tat_tracker_home_fragment, name='tat_tracker_home_fragment'),
    path('tat-tracker/search/', tat_tracker_search, name='tat_tracker_search'),
    path('tat-tracker/search/fragment/', tat_tracker_search_fragment, name='tat_tracker_search_fragment'),
    path('tat-tracker/target-settings/', tat_tracker_target_settings, name='tat_tracker_target_settings'),
    path('tat-tracker/settings/', tat_tracker_settings, name='tat_tracker_settings'),
    path('tat-tracker/settings/personal/', tat_tracker_settings_personal, name='tat_tracker_settings_personal'),
    path('tat-tracker/settings/proposals/', tat_tracker_settings_request, name='tat_tracker_settings_request'),
    path('tat-tracker/settings/proposals/review/', tat_tracker_settings_review, name='tat_tracker_settings_review'),
    path('tat-tracker/create/', tat_tracker_create, name='tat_tracker_create'),
    path('tat-tracker/identity-context/', tat_tracker_identity_context, name='tat_tracker_identity_context'),
    path('tat-tracker/detail/', tat_tracker_detail, name='tat_tracker_detail'),
    path('tat-tracker/update/', tat_tracker_update, name='tat_tracker_update'),
    path('complaints/', complaint_cases_app, name='complaint_cases_app'),
    path('complaints/bootstrap/', complaint_cases_bootstrap, name='complaint_cases_bootstrap'),
    path('complaints/settings/personal/', complaint_cases_settings_personal, name='complaint_cases_settings_personal'),
    path('complaints/cases/', complaint_cases_list, name='complaint_cases_list'),
    path('complaints/cases/fragment/', complaint_cases_list_fragment, name='complaint_cases_list_fragment'),
    path('complaints/cases/create/', complaint_cases_create, name='complaint_cases_create'),
    path('complaints/cases/<str:case_id>/', complaint_cases_detail, name='complaint_cases_detail'),
    path('complaints/cases/<str:case_id>/update/', complaint_cases_update, name='complaint_cases_update'),
    path('webhook/e-signatures/tat/', tat_signature_webhook, name='tat_signature_webhook'),
    path('webhook/telegram/', telegram_webhook, name='telegram_webhook'),
    path(
        'order-approval/webapp/submit/',
        order_approval_webapp_submit,
        name='order_approval_webapp_submit',
    ),
    path(
        'order-approval/webapp/lookup/',
        order_approval_webapp_lookup,
        name='order_approval_webapp_lookup',
    ),
    path(
        'order-approval/webapp/suggest/',
        order_approval_webapp_suggest,
        name='order_approval_webapp_suggest',
    ),
    path('process/messages/', process_messages, name='process_messages'),
    path('resync/unsynced/', resend_unsynced, name='resend_unsynced'),
    path('sync/from-sheets/', sync_from_sheets, name='sync_from_sheets'),

    # JBL Pipeline Portal
    path('portal/', portal_home, name='portal_home'),
    path('portal/cases/<str:farmer_id>/', portal_case_history_detail, name='portal_case_history_detail'),
    # Reports use drill-down routes so phone/browser Back returns through
    # report detail rather than a crowded all-in-one workspace.
    path('portal/s/reports/', portal_reports_screen, name='portal_reports_screen'),
    path('portal/s/reports/new/', portal_reports_screen, {'report_view': 'edit'}, name='portal_reports_new'),
    path('portal/s/reports/new/<str:report_step>/', portal_reports_screen, {'report_view': 'edit'}, name='portal_reports_new_step'),
    path('portal/s/reports/<str:report_id>/', portal_reports_screen, {'report_view': 'detail'}, name='portal_report_screen_detail'),
    path('portal/s/reports/<str:report_id>/edit/', portal_reports_screen, {'report_view': 'edit'}, name='portal_report_screen_edit'),
    path('portal/s/reports/<str:report_id>/edit/<str:report_step>/', portal_reports_screen, {'report_view': 'edit'}, name='portal_report_screen_edit_step'),
    path('portal/s/reports/<str:report_id>/run/', portal_reports_screen, {'report_view': 'run'}, name='portal_report_screen_run'),
    # Invoices use ordinary nested routes so Telegram and phone Back move
    # through the workspace instead of reopening one crowded all-in-one view.
    path('portal/s/invoices/', portal_invoices_screen, name='portal_invoices_screen'),
    path('portal/s/invoices/matched/', portal_invoices_screen, {'invoice_view': 'matched'}, name='portal_invoices_matched'),
    path('portal/s/invoices/ignored/', portal_invoices_screen, {'invoice_view': 'ignored'}, name='portal_invoices_ignored'),
    path('portal/s/invoices/upload/', portal_invoices_screen, {'invoice_view': 'upload'}, name='portal_invoices_upload'),
    path('portal/s/invoices/<str:invoice_id>/', portal_invoices_screen, {'invoice_view': 'detail'}, name='portal_invoice_screen_detail'),
    path('portal/s/<str:screen>/', portal_screen, name='portal_screen'),
    path('portal/navigation/', portal_navigation, name='portal_navigation'),
    path('portal/settings/', portal_settings, name='portal_settings'),
    path('portal/settings/delegations/', portal_approval_delegations, name='portal_approval_delegations'),
    path('portal/settings/delegations/<str:delegation_id>/revoke/', portal_approval_delegation_revoke, name='portal_approval_delegation_revoke'),
    path('portal/workspace/', portal_workspace, name='portal_workspace'),
    path('portal/workspace/views/', portal_workspace_views, name='portal_workspace_views'),
    path('portal/workspace/views/<str:view_id>/', portal_workspace_view_detail, name='portal_workspace_view_detail'),
    path('portal/workspace/views/<str:view_id>/activate/', portal_workspace_view_activate, name='portal_workspace_view_activate'),
    path('portal/workspace/views/<str:view_id>/startup/', portal_workspace_view_startup, name='portal_workspace_view_startup'),
    path('portal/workspace/cases/<str:farmer_id>/pin/', portal_workspace_case_pin, name='portal_workspace_case_pin'),
    path('portal/workspace/cases/<str:farmer_id>/unpin/', portal_workspace_case_unpin, name='portal_workspace_case_unpin'),
    path('portal/workspace/recents/clear/', portal_workspace_recents_clear, name='portal_workspace_recents_clear'),
    path('portal/dashboard/', portal_auth_required(portal_dashboard), name='portal_dashboard'),
    path('portal/meta/', portal_auth_required(portal_meta), name='portal_meta'),
    path('portal/imports/', portal_imports, name='portal_imports'),
    path('portal/imports/<str:kind>/stage/', portal_import_stage, name='portal_import_stage'),
    path('portal/imports/<str:batch_id>/', portal_import_detail, name='portal_import_detail'),
    path('portal/imports/archive-attempt/', portal_import_archive_attempt, name='portal_import_archive_attempt'),
    # IT-only, catalogue-constrained reports. These views are individually
    # Telegram-authenticated because report runs/export writes audit evidence.
    path('portal/reports/catalogue/', portal_reports_catalogue, name='portal_reports_catalogue'),
    path('portal/reports/preview/', portal_report_preview, name='portal_report_preview'),
    path('portal/reports/relationships/', portal_reporting_relationships, name='portal_reporting_relationships'),
    path('portal/reports/', portal_reports, name='portal_reports'),
    path('portal/reports/<str:report_id>/', portal_report_detail, name='portal_report_detail'),
    path('portal/reports/<str:report_id>/archive/', portal_report_archive, name='portal_report_archive'),
    path('portal/reports/<str:report_id>/run/', portal_report_run, name='portal_report_run'),
    path('portal/reports/<str:report_id>/export/', portal_report_export, name='portal_report_export'),
    path('portal/health/', portal_auth_required(portal_health), name='portal_health'),
    path('portal/health/maintenance/', portal_auth_required(portal_set_maintenance), name='portal_set_maintenance'),
    # Stage 2 - JBL Visit
    path('portal/jbl-queue/', portal_auth_required(portal_jbl_queue), name='portal_jbl_queue'),
    path('portal/jbl-queue/fragment/', portal_auth_required(portal_jbl_queue_fragment), name='portal_jbl_queue_fragment'),
    path('portal/my-visits/', portal_auth_required(portal_my_visits), name='portal_my_visits'),
    path('portal/queues/<str:queue_key>/fragment/', portal_auth_required(portal_queue_fragment), name='portal_queue_fragment'),
    path('portal/jbl-queue/<str:farmer_id>/', portal_auth_required(portal_log_jbl_visit), name='portal_log_jbl_visit'),
    path('portal/jbl-queue/<str:farmer_id>/draft/', portal_auth_required(portal_jbl_visit_draft), name='portal_jbl_visit_draft'),
    path('portal/jbl-queue/<str:farmer_id>/complete-visit/', portal_auth_required(portal_complete_jbl_visit), name='portal_complete_jbl_visit'),
    path('portal/publication/attempt/', portal_auth_required(portal_publication_attempt), name='portal_publication_attempt'),
    path('portal/jbl-queue/<str:farmer_id>/media/', portal_auth_required(portal_upload_jbl_media), name='portal_upload_jbl_media'),
    path('portal/jbl-queue/<str:farmer_id>/media/list/', portal_auth_required(portal_jbl_media), name='portal_jbl_media'),
    path('portal/jbl-queue/<str:farmer_id>/media/<str:attachment_id>/preview/', portal_auth_required(portal_preview_jbl_media), name='portal_preview_jbl_media'),
    # Short-lived link issued by the authorised media-list API for Telegram's
    # external browser, where the Mini App initData header is unavailable.
    path('portal/jbl-media-open/<str:token>/', portal_open_jbl_media_signed, name='portal_open_jbl_media_signed'),
    path('portal/jbl-queue/<str:farmer_id>/media/legacy/<int:media_index>/open/', portal_auth_required(portal_open_legacy_jbl_media), name='portal_open_legacy_jbl_media'),
    path('portal/jbl-queue/<str:farmer_id>/media/<str:attachment_id>/open/', portal_auth_required(portal_open_jbl_media), name='portal_open_jbl_media'),
    path('portal/approval-conditions/<str:condition_id>/clear/', portal_auth_required(portal_clear_approval_condition), name='portal_clear_approval_condition'),
    # Stage 3 - Credit Decision
    path('portal/credit-queue/', portal_auth_required(portal_credit_queue), name='portal_credit_queue'),
    path('portal/credit-queue/<str:farmer_id>/', portal_auth_required(portal_set_credit_decision), name='portal_set_credit_decision'),
    path('portal/final-review-queue/', portal_auth_required(portal_final_review_queue), name='portal_final_review_queue'),
    path('portal/final-review-queue/<str:farmer_id>/', portal_auth_required(portal_set_final_decision), name='portal_set_final_decision'),
    path('portal/cases/<str:farmer_id>/return-for-rework/', portal_auth_required(portal_return_for_rework), name='portal_return_for_rework'),
    # Stage 4 - Requisition / Order (GATED)
    path('portal/requisition-queue/', portal_auth_required(portal_requisition_queue), name='portal_requisition_queue'),
    path('portal/requisition-queue/preview/', portal_auth_required(portal_requisition_preview), name='portal_requisition_preview'),
    path('portal/requisition-queue/preview-workbook/', portal_auth_required(portal_requisition_workbook_preview), name='portal_requisition_workbook_preview'),
    path('portal/requisition-queue/generate/', portal_auth_required(portal_requisition_generate), name='portal_requisition_generate'),
    # Signed, short-lived link: Telegram opens this in the system browser,
    # where the Mini App initData header is not available.
    path('portal/requisition-download/<str:token>/', portal_requisition_download, name='portal_requisition_download'),
    path('portal/requisition-queue/<str:farmer_id>/', portal_auth_required(portal_assign_order), name='portal_assign_order'),
    path('portal/requisition-batches/', portal_auth_required(portal_requisition_batches), name='portal_requisition_batches'),
    path('portal/requisition-batches/fragment/', portal_auth_required(portal_requisition_batches_fragment), name='portal_requisition_batches_fragment'),
    path('portal/requisition-batches/upload-invoices/', portal_auth_required(portal_upload_batch_invoices), name='portal_upload_batch_invoices'),
    path('portal/requisition-batches/<str:order_number>/download/', portal_auth_required(portal_requisition_batch_download), name='portal_requisition_batch_download'),
    path('portal/requisition-batches/<str:order_number>/retry-sync/', portal_auth_required(portal_requisition_batch_retry_sync), name='portal_requisition_batch_retry_sync'),
    path('portal/requisition-batches/<str:order_number>/', portal_auth_required(portal_requisition_batch_detail), name='portal_requisition_batch_detail'),
    path('portal/invoice-pool/', portal_auth_required(portal_invoice_pool), name='portal_invoice_pool'),
    path('portal/invoice-pool/farmers/', portal_auth_required(portal_invoice_farmer_candidates), name='portal_invoice_farmer_candidates'),
    path('portal/invoice-pool/upload/', portal_auth_required(portal_invoice_pool_upload), name='portal_invoice_pool_upload'),
    path('portal/invoice-batches/<str:batch_id>/confirm/', portal_auth_required(portal_invoice_batch_confirm), name='portal_invoice_batch_confirm'),
    path('portal/invoice-pool/bulk-action/', portal_auth_required(portal_invoice_bulk_action), name='portal_invoice_bulk_action'),
    path('portal/invoice-pool/<str:invoice_id>/', portal_auth_required(portal_invoice_detail), name='portal_invoice_detail'),
    path('portal/invoice-pool/<str:invoice_id>/draft/', portal_auth_required(portal_invoice_draft_edit), name='portal_invoice_draft_edit'),
    path('portal/invoice-pool/<str:invoice_id>/match/', portal_auth_required(portal_invoice_match), name='portal_invoice_match'),
    path('portal/invoice-pool/<str:invoice_id>/unmatch/', portal_auth_required(portal_invoice_unmatch), name='portal_invoice_unmatch'),
    path('portal/invoice-pool/<str:invoice_id>/ignore/', portal_auth_required(portal_invoice_ignore), name='portal_invoice_ignore'),
    path('portal/invoice-pool/<str:invoice_id>/restore/', portal_auth_required(portal_invoice_restore), name='portal_invoice_restore'),
    path('portal/payment-documents/<str:order_number>/readiness/', portal_auth_required(portal_payment_readiness), name='portal_payment_readiness'),
    path('portal/payments/candidates/', portal_auth_required(portal_payment_candidates), name='portal_payment_candidates'),
    path('portal/payments/selection/', portal_auth_required(portal_payment_selection), name='portal_payment_selection'),
    path('portal/payment-documents/<str:order_number>/preview-data/', portal_auth_required(portal_payment_preview_data), name='portal_payment_preview_data'),
    path('portal/payment-documents/<str:order_number>/preview/', portal_auth_required(portal_payment_document_preview), name='portal_payment_document_preview'),
    path('portal/payment-documents/<str:order_number>/finalize/', portal_auth_required(portal_payment_document_finalize), name='portal_payment_document_finalize'),
    path('portal/payment-document/<str:document_id>/approve/', portal_auth_required(portal_payment_document_approve), name='portal_payment_document_approve'),
    path('portal/payment-document/<str:document_id>/regenerate/', portal_auth_required(portal_payment_document_regenerate), name='portal_payment_document_regenerate'),
    path('portal/document-history/', portal_auth_required(portal_document_history), name='portal_document_history'),
    path('portal/document-signoffs/<str:document_type>/<str:document_id>/upload/', portal_auth_required(portal_document_physical_signoff_upload), name='portal_document_physical_signoff_upload'),
    path('portal/document-signoffs/<str:signoff_id>/retry/', portal_auth_required(portal_document_physical_signoff_retry), name='portal_document_physical_signoff_retry'),
    path('portal/payment-document-history/<str:document_id>/', portal_auth_required(portal_payment_document_detail), name='portal_payment_document_detail'),
    # All cases + deferred
    path('portal/farmers/', portal_auth_required(portal_all_cases), name='portal_all_cases'),
    path('portal/farmers/<str:farmer_id>/', portal_auth_required(portal_farmer_detail), name='portal_farmer_detail'),
    path('portal/deferred/', portal_auth_required(portal_deferred), name='portal_deferred'),
]
