"""
URL routing for the core API.
"""
from django.urls import path
from .views import (
    telegram_webhook,
    health_check,
    jawabu_farmers_review,
    jawabu_farmers_review_commit,
    fca_review,
    fca_review_commit,
    order_approval_form,
    order_approval_webapp_lookup,
    order_approval_webapp_suggest,
    order_approval_webapp_submit,
    spin_form,
    spin_form_submit,
    spin_form_requests,
    spin_form_complete,
    tat_tracker_app,
    tat_tracker_bootstrap,
    tat_tracker_home,
    tat_tracker_search,
    tat_tracker_create,
    tat_tracker_detail,
    tat_tracker_update,
    process_messages,
    resend_unsynced,
    sync_from_sheets,
)
from .portal_views import (
    portal_home,
    portal_dashboard,
    portal_meta,
    portal_jbl_queue,
    portal_log_jbl_visit,
    portal_upload_jbl_media,
    portal_credit_queue,
    portal_set_credit_decision,
    portal_final_review_queue,
    portal_set_final_decision,
    portal_requisition_queue,
    portal_requisition_preview,
    portal_assign_order,
    portal_requisition_generate,
    portal_requisition_download,
    portal_requisition_batches,
    portal_requisition_batch_detail,
    portal_requisition_batch_download,
    portal_upload_batch_invoices,
    portal_all_cases,
    portal_deferred,
    portal_farmer_detail,
    portal_auth_required,
)

urlpatterns = [
    path('health/', health_check, name='health_check'),
    path('order-approval/', order_approval_form, name='order_approval_form'),
    path('jawabu-farmers/review/', jawabu_farmers_review, name='jawabu_farmers_review'),
    path('jawabu-farmers/review/commit/', jawabu_farmers_review_commit, name='jawabu_farmers_review_commit'),
    path('fca/review/', fca_review, name='fca_review'),
    path('fca/review/commit/', fca_review_commit, name='fca_review_commit'),
    path('spin/', spin_form, name='spin_form'),
    path('spin/submit/', spin_form_submit, name='spin_form_submit'),
    path('spin/requests/', spin_form_requests, name='spin_form_requests'),
    path('spin/complete/', spin_form_complete, name='spin_form_complete'),
    path('tat-tracker/', tat_tracker_app, name='tat_tracker_app'),
    path('tat-tracker/bootstrap/', tat_tracker_bootstrap, name='tat_tracker_bootstrap'),
    path('tat-tracker/home/', tat_tracker_home, name='tat_tracker_home'),
    path('tat-tracker/search/', tat_tracker_search, name='tat_tracker_search'),
    path('tat-tracker/create/', tat_tracker_create, name='tat_tracker_create'),
    path('tat-tracker/detail/', tat_tracker_detail, name='tat_tracker_detail'),
    path('tat-tracker/update/', tat_tracker_update, name='tat_tracker_update'),
    path('webhook/telegram/', telegram_webhook, name='telegram_webhook'),
    path(
        'order-approval/webapp/submit/',
        order_approval_webapp_submit,
        name='order_approval_webapp_submit',
    ),
    path(
        'order-approval/webapp/lookup/',
        order_approval_webapp_lookup,
        name='order_approval_webapp_lookup',
    ),
    path(
        'order-approval/webapp/suggest/',
        order_approval_webapp_suggest,
        name='order_approval_webapp_suggest',
    ),
    path('process/messages/', process_messages, name='process_messages'),
    path('resync/unsynced/', resend_unsynced, name='resend_unsynced'),
    path('sync/from-sheets/', sync_from_sheets, name='sync_from_sheets'),

    # JBL Pipeline Portal
    path('portal/', portal_home, name='portal_home'),
    path('portal/dashboard/', portal_auth_required(portal_dashboard), name='portal_dashboard'),
    path('portal/meta/', portal_auth_required(portal_meta), name='portal_meta'),
    # Stage 2 - JBL Visit
    path('portal/jbl-queue/', portal_auth_required(portal_jbl_queue), name='portal_jbl_queue'),
    path('portal/jbl-queue/<str:farmer_id>/', portal_auth_required(portal_log_jbl_visit), name='portal_log_jbl_visit'),
    path('portal/jbl-queue/<str:farmer_id>/media/', portal_auth_required(portal_upload_jbl_media), name='portal_upload_jbl_media'),
    # Stage 3 - Credit Decision
    path('portal/credit-queue/', portal_auth_required(portal_credit_queue), name='portal_credit_queue'),
    path('portal/credit-queue/<str:farmer_id>/', portal_auth_required(portal_set_credit_decision), name='portal_set_credit_decision'),
    path('portal/final-review-queue/', portal_auth_required(portal_final_review_queue), name='portal_final_review_queue'),
    path('portal/final-review-queue/<str:farmer_id>/', portal_auth_required(portal_set_final_decision), name='portal_set_final_decision'),
    # Stage 4 - Requisition / Order (GATED)
    path('portal/requisition-queue/', portal_auth_required(portal_requisition_queue), name='portal_requisition_queue'),
    path('portal/requisition-queue/preview/', portal_auth_required(portal_requisition_preview), name='portal_requisition_preview'),
    path('portal/requisition-queue/generate/', portal_auth_required(portal_requisition_generate), name='portal_requisition_generate'),
    path('portal/requisition-download/<str:token>/', portal_requisition_download, name='portal_requisition_download'),
    path('portal/requisition-queue/<str:farmer_id>/', portal_auth_required(portal_assign_order), name='portal_assign_order'),
    path('portal/requisition-batches/', portal_auth_required(portal_requisition_batches), name='portal_requisition_batches'),
    path('portal/requisition-batches/upload-invoices/', portal_auth_required(portal_upload_batch_invoices), name='portal_upload_batch_invoices'),
    path('portal/requisition-batches/<str:order_number>/download/', portal_requisition_batch_download, name='portal_requisition_batch_download'),
    path('portal/requisition-batches/<str:order_number>/', portal_auth_required(portal_requisition_batch_detail), name='portal_requisition_batch_detail'),
    # All cases + deferred
    path('portal/farmers/', portal_auth_required(portal_all_cases), name='portal_all_cases'),
    path('portal/farmers/<str:farmer_id>/', portal_auth_required(portal_farmer_detail), name='portal_farmer_detail'),
    path('portal/deferred/', portal_auth_required(portal_deferred), name='portal_deferred'),
]
