import csv
import io
from decimal import Decimal

from django.test import TestCase

from core.models import JawabuFarmerMaster
from core.services.system_export import (
    commit_system_export_review_batch,
    create_system_export_review_batch,
    parse_system_export,
)


HEADERS = [
    'Customer ID', 'Name', 'Mobile No', 'ID NO', 'Branch', 'Loan Officer',
    'Status', 'Loan Closure', 'Loan Cycle', 'Metropol CRB Credit Score',
    'Payment Efficiency', 'Product Name', 'Last Loan Amount', 'LGF Balance',
    'Last Disbursement Date', 'Customer Comments',
]


def export_csv(rows):
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=HEADERS)
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue().encode()


class SystemExportImportTests(TestCase):
    def setUp(self):
        self.farmer = JawabuFarmerMaster.objects.create(
            customer_name='Jane Wanjiku',
            national_id='12345678',
            primary_phone='254712345678',
            branch='Limuru',
            status='active',
        )

    def test_parser_keeps_zero_lgf_balance_and_ignores_blank_rows(self):
        rows, stats = parse_system_export(export_csv([{
            'Customer ID': '9001', 'Name': 'WANJIKU, JANE', 'Mobile No': '0712345678',
            'ID NO': '12345678', 'Branch': 'Embu', 'Loan Officer': 'Officer A',
            'Product Name': 'Biogas', 'LGF Balance': '0',
        }]), 'customers.csv')

        self.assertEqual(stats['total_rows'], 1)
        self.assertEqual(rows[0]['LGF Balance'], '0')
        self.assertEqual(rows[0]['Mobile No'], '254712345678')
        self.assertEqual(rows[0]['Matched Farmer ID'], str(self.farmer.id))
        self.assertEqual(rows[0]['Match Basis'], 'national_id')
        self.assertTrue(rows[0]['approved'])

    def test_xlsx_export_is_supported(self):
        from openpyxl import Workbook

        workbook = Workbook()
        sheet = workbook.active
        sheet.append(['Report generated by IMAB'])
        sheet.append(HEADERS)
        sheet.append([
            '9001', 'WANJIKU, JANE', '0712345678', '12345678', 'Embu',
            'Officer A', 'Active', '', '', '', '', 'Biogas', '', '0', '', '',
        ])
        output = io.BytesIO()
        workbook.save(output)

        rows, stats = parse_system_export(output.getvalue(), 'customers.xlsx')

        self.assertEqual(stats['total_rows'], 1)
        self.assertEqual(rows[0]['Customer ID'], '9001')
        self.assertEqual(rows[0]['LGF Balance'], '0')
        self.assertTrue(rows[0]['approved'])

    def test_commit_preserves_imab_name_and_updates_system_fields(self):
        batch, _stats = create_system_export_review_batch(
            group_id='-100sysup',
            telegram_message_id='sysup-1',
            sender='Officer',
            source_filename='customers.csv',
            content=export_csv([{
                'Customer ID': '9001', 'Name': 'WANJIKU, JANE', 'Mobile No': '0712345678',
                'ID NO': '12345678', 'Branch': 'Embu', 'Loan Officer': 'Officer A',
                'Product Name': 'Biogas', 'LGF Balance': '5000',
            }]),
        )

        result = commit_system_export_review_batch(batch, batch.parsed_rows, actor='Officer')

        self.assertTrue(result['success'])
        self.farmer.refresh_from_db()
        self.assertEqual(self.farmer.customer_no, '9001')
        self.assertIsNotNone(self.farmer.customer)
        self.assertEqual(self.farmer.customer.customer_no, '9001')
        self.assertEqual(self.farmer.imab_customer_name, 'WANJIKU, JANE')
        self.assertEqual(self.farmer.branch, 'Embu')
        self.assertEqual(self.farmer.system_branch, 'Embu')
        self.assertEqual(self.farmer.system_loan_officer, 'Officer A')
        self.assertEqual(self.farmer.payment_product, 'Biogas')
        self.assertEqual(self.farmer.system_deposit_paid_jbl, Decimal('5000'))
        self.assertEqual(batch.status, 'committed')
        self.assertTrue(self.farmer.pipeline_events.filter(source='system_export').exists())

    def test_conflicting_identifiers_require_review(self):
        other = JawabuFarmerMaster.objects.create(
            customer_name='Other Farmer', customer_no='9002', status='active',
        )
        rows, _stats = parse_system_export(export_csv([{
            'Customer ID': '9002', 'Name': 'WANJIKU, JANE', 'Mobile No': '0712345678',
            'ID NO': '12345678', 'Branch': 'Embu', 'Loan Officer': 'Officer A',
            'Product Name': 'Biogas', 'LGF Balance': '0',
        }]), 'customers.csv')

        self.assertEqual(rows[0]['Import Status'], 'review_needed')
        self.assertFalse(rows[0]['approved'])
        self.assertIn('different cases', rows[0]['Cleaning Notes'])
        self.assertNotEqual(rows[0]['Matched Farmer ID'], str(other.id))

    def test_name_order_is_a_manual_candidate_only(self):
        rows, _stats = parse_system_export(export_csv([{
            'Customer ID': '9009', 'Name': 'WANJIKU, JANE', 'Mobile No': '0712345679',
            'ID NO': '87654321', 'Branch': 'Embu', 'Loan Officer': 'Officer A',
            'Product Name': 'Biogas', 'LGF Balance': '0',
        }]), 'customers.csv')

        self.assertEqual(rows[0]['Import Status'], 'review_needed')
        self.assertFalse(rows[0]['approved'])
        self.assertEqual(rows[0]['Match Basis'], 'name_candidate')
        self.assertEqual(rows[0]['Match Candidates'][0]['id'], str(self.farmer.id))
        self.assertIn('manual confirmation', rows[0]['Cleaning Notes'])

    def test_invalid_edited_lgf_does_not_write_identity(self):
        batch, _stats = create_system_export_review_batch(
            group_id='-100sysup',
            telegram_message_id='sysup-invalid-lgf',
            sender='Officer',
            source_filename='customers.csv',
            content=export_csv([{
                'Customer ID': '9001', 'Name': 'WANJIKU, JANE', 'Mobile No': '0712345678',
                'ID NO': '12345678', 'Branch': 'Embu', 'Loan Officer': 'Officer A',
                'Product Name': 'Biogas', 'LGF Balance': '0',
            }]),
        )
        row = dict(batch.parsed_rows[0])
        row['approved'] = True
        row['LGF Balance'] = 'not-a-number'
        result = commit_system_export_review_batch(batch, [row], actor='Officer')

        self.assertFalse(result['success'])
        self.assertEqual(result['committed'], 0)
        self.farmer.refresh_from_db()
        self.assertEqual(self.farmer.customer_no, '')
        self.assertIsNone(self.farmer.customer)
        self.assertEqual(batch.status, 'pending_review')
