from pathlib import Path

from django.test import SimpleTestCase


class LoanOriginationFrontendTests(SimpleTestCase):
    def test_remote_signing_is_primary_and_assisted_signing_is_explicit(self):
        app_source = Path('core/static/miniapp/loan_origination.js').read_text(encoding='utf-8')
        signer_source = Path('core/static/miniapp/origination_signing.js').read_text(encoding='utf-8')
        signer_template = Path('core/templates/loan_origination/sign.html').read_text(encoding='utf-8')
        signer_styles = Path('core/static/miniapp/origination_signing.css').read_text(encoding='utf-8')

        self.assertIn("Send to signer's phone", app_source)
        self.assertIn('In-person assisted signing', app_source)
        self.assertIn('Send remotely instead', app_source)
        self.assertIn('data-target-access-mode', app_source)
        self.assertIn("session.access_mode === 'assisted'", signer_source)
        self.assertIn('wherever you are', signer_source)
        self.assertIn('signing-mode-banner', signer_template)
        self.assertIn("data-session-url=\"{% url 'loan_origination_signer_session' %}\"", signer_template)
        self.assertIn('<meta name="color-scheme" content="light">', signer_template)
        self.assertIn("origination_signing.css' %}?v=20260821-3", signer_template)
        self.assertIn('color-scheme: light;', signer_styles)
        self.assertIn('View signed LAF', app_source)
        self.assertIn('Open PDF', app_source)
        self.assertIn('function openSignedPacketPdf', app_source)
        self.assertIn("openPreview('__signed_packet__')", app_source)
        self.assertIn('function hasFinalSignedPacket()', app_source)
        self.assertIn('documentKey = resolveLatestPreviewKey(documentKey);', app_source)
        self.assertIn("if (hasFinalSignedPacket()) return 'Preview signed packet';", app_source)
        self.assertIn('/signed-packet/', app_source)
        self.assertIn("sessionStorage.setItem('jbl-origination-signing-token'", signer_source)
        self.assertIn('const token = fragmentToken || storedToken;', signer_source)
        self.assertIn("if (session.status === 'verified')", signer_source)
        self.assertIn("sessionStorage.removeItem('jbl-origination-signing-token'", signer_source)
        self.assertIn('session.consent_text', signer_source)
        self.assertIn('session.completion_text', signer_source)

    def test_miniapp_shell_is_not_cached_by_telegram_webview(self):
        response = self.client.get('/origination/')

        self.assertEqual(response.status_code, 200)
        self.assertIn('no-store', response['Cache-Control'])
        self.assertEqual(response['Pragma'], 'no-cache')

    def test_wizard_and_preview_contract_are_present(self):
        source = Path('core/static/miniapp/loan_origination.js').read_text(encoding='utf-8')
        template = Path('core/templates/loan_origination/app.html').read_text(encoding='utf-8')
        css = Path('core/static/miniapp/loan_origination.css').read_text(encoding='utf-8')

        for section in ('Applicant', 'Business', 'Loan', 'Security', 'Guarantors', 'Review'):
            self.assertIn(f"label: '{section}'", source)
        self.assertIn('grid-template-columns:repeat(2', css)
        self.assertIn('laf-field-wide', css)
        self.assertIn('/preview/', source)
        self.assertIn('previewedRevision !== current.revision', source)
        self.assertIn('URL.revokeObjectURL', source)
        self.assertIn('document-preview-overlay', template)
        self.assertIn('preview-regenerate', template)
        self.assertIn('@media (max-width: 390px)', css)
        self.assertIn('font-size: 16px !important', css)
        self.assertIn('position: sticky', css)
        self.assertNotIn('id="origination-refresh"', template)
        self.assertNotIn('id="preview-open"', template)
        self.assertIn('data-ui-version="20260827-4"', template)
        self.assertIn("loan_origination.css' %}?v=20260827-4", template)
        self.assertIn("loan_origination.js' %}?v=20260827-4", template)
        self.assertIn('maximumLiveViewportHeight', source)
        self.assertIn('setKeyboardViewportOpen', source)
        self.assertIn('.origination-keyboard-open .wizard-actions { display: none !important; }', css)
        self.assertIn('.origination-app select option', css)
        self.assertIn('-webkit-text-fill-color: var(--laf-dark)', css)
        self.assertIn('color-scheme: dark', css)
        self.assertIn('origination-select-overlay', template)
        self.assertIn('function enhanceSelect', source)
        self.assertIn('function openCustomSelect', source)
        self.assertIn("if (activeCustomSelect) return closeCustomSelect()", source)
        self.assertIn('function nativeDateControl', source)
        self.assertIn('type="date"', source)
        self.assertIn("formatKenyanDate", source)
        self.assertIn('function formatWholeKes', source)
        self.assertIn("'dd-mm-yy'", source)
        self.assertNotIn('origination-date-overlay', template)
        self.assertIn('function numericInputError', source)
        self.assertIn('data-numeric-input', source)
        self.assertIn('.origination-app input[type="checkbox"]::before', css)
        self.assertIn('-webkit-appearance: none', css)
        self.assertNotIn("['money', 'number'].includes(field.type) ? 'number'", source)
        self.assertIn('function keepFocusedInputVisible', source)
        self.assertIn('origination-input-active', source)
        self.assertIn('.wizard-actions { position: fixed', css)
        self.assertIn('.origination-keyboard-open .wizard-actions { display: none !important; }', css)
        self.assertIn('wizardSections()', source)
        self.assertIn('field.section_key', source)
        self.assertIn("field.type === 'textarea'", source)
        self.assertIn("stage.addEventListener('pointermove'", source)
        self.assertIn('setPointerCapture', source)
        self.assertIn('touch-action: none', css)
        self.assertIn('Math.min(300', source)
        self.assertIn('deliberateHorizontalSwipe', source)
        self.assertIn('navigatePreviewPage(deltaX < 0 ? 1 : -1)', source)
        self.assertIn('previewPageUrls.size > 3', source)
        self.assertIn('void fetchPreviewPage(pageNumber)', source)
        self.assertIn('indexedDB.open(RECOVERY_DB', source)
        self.assertIn("name: 'AES-GCM'", source)
        self.assertIn('pendingSaveRequestId', source)
        self.assertIn('function storageGet', source)
        self.assertIn('const volatileStorage = new Map()', source)
        self.assertIn('The application was created, but its editor could not open.', source)
        self.assertIn('saveInFlight', source)
        self.assertIn('data-evidence-upload', source)
        self.assertIn('navigator.mediaDevices?.getUserMedia', source)
        self.assertIn("facingMode: { ideal: 'environment' }", source)
        self.assertIn('data-correction-target', source)
        self.assertIn('mainFormOwnsField', source)
        self.assertIn("field.source_type === 'system'", source)
        self.assertIn('one full-packet preview at the final check', source)
        self.assertIn('data-clear-guarantor-two', source)
        self.assertIn("querySelectorAll('.laf-grid').forEach", source)
        self.assertIn('previewDocumentKey', source)
        self.assertIn("openPreview('__packet__')", source)
        self.assertIn("openPreview('__review_packet__')", source)
        self.assertIn('/prepare-review-packet/', source)
        self.assertIn('/review-packet/preview/', source)
        self.assertIn('data-correction-instruction', source)
        self.assertIn('Cancel packet and edit', source)
        self.assertIn("capabilities.can_start_signing ? [['prepare', 'Prepare packet']]", source)
        self.assertIn("capabilities.can_start_signing || capabilities.can_staff_sign ? [['signing', 'Signing']]", source)
        self.assertIn("page_size: '10'", source)
        self.assertIn('listRequestGeneration', source)
        self.assertIn('listSearchTimer', source)
        self.assertIn('Submit for packet preparation', source)
        self.assertIn("['fully_signed', 'approved'].includes(current?.status) ? ''", source)
        self.assertIn('Automatic archival in progress', source)
        self.assertNotIn('>Archive signed packet<', source)
        self.assertNotIn('data-sheet-cancel>Cancel</button><button type="submit" form="origination-create"', source)
        self.assertIn('.workflow-readiness', css)
        self.assertIn("openPreview('__test_signing__')", source)
        self.assertIn('recheck_assigned_to_name', source)
        self.assertIn('data-test-sign-slot', source)
        self.assertIn('holistic signature', source)
        self.assertIn('Capture one TEST signature', source)
        self.assertIn('function openSignatureSheet', source)
        self.assertIn('data-test-signature-canvas', source)
        self.assertIn('signature_capture: capture', source)
        self.assertIn('Do not enter or draw a real signature.', source)
        self.assertIn('.test-signature-panel canvas', css)
        self.assertIn('await openPreview(documentKey);', source)
        self.assertIn("signedPacketPreview = previewDocumentKey === '__signed_packet__'", source)
        self.assertIn('[data-document-select]:checked:not(:disabled)', source)
        self.assertIn("addEventListener('click', () => openPreview())", source)
        self.assertIn("if (typeof documentKey !== 'string') documentKey = '';", source)
        self.assertNotIn("addEventListener('click', openPreview)", source)
        self.assertIn('origination-review-overlay', template)
        self.assertIn('queue-tabs', css)
        self.assertIn('origination-sheet-overlay', template)
        self.assertIn('wizard-progress-compact', source)
        self.assertIn('data-primary-action', source)
        self.assertIn('syncTelegramControls', source)
        self.assertIn("tg?.onEvent?.('viewportChanged'", source)
        self.assertIn("tg?.onEvent?.('themeChanged'", source)
        self.assertIn('listScrollY', source)
        self.assertIn('applyListFilters', source)
        self.assertIn('trapModalFocus', source)
        self.assertIn('iconSvg', source)
        self.assertNotIn('class="app-hero"', source)
        self.assertNotIn('window.prompt', source)

    def test_superuser_template_calibration_workspace_is_present(self):
        template = Path('core/templates/admin/core/originationdocumenttemplate/calibrate.html').read_text(encoding='utf-8')
        source = Path('core/static/admin/origination_calibration.js').read_text(encoding='utf-8')
        styles = Path('core/static/admin/origination_calibration.css').read_text(encoding='utf-8')
        for control in ('calibration-canvas', 'calibration-save', 'calibration-publish', 'cal-filled', 'calibration-add-signature'):
            self.assertIn(control, template)
        self.assertIn('global-apply', template)
        self.assertIn('global-font', template)
        for control in ('cal-mobile-fields', 'cal-mobile-inspector', 'cal-mobile-global', 'cal-mobile-view'):
            self.assertIn(control, template)
        self.assertIn('aria-labelledby="calibration-sheet-title"', template)
        self.assertIn('aria-controls="calibration-sidebar" aria-expanded="false"', template)
        self.assertIn('origination_calibration.css\' %}?v=19', template)
        self.assertIn('origination_calibration.js\' %}?v=19', template)
        self.assertIn('cal-snap-toggle', template)
        self.assertIn('cal-guide-horizontal', template)
        self.assertIn('cal-guide-vertical', template)
        self.assertIn('cal-guide-clear', template)
        self.assertIn('cal-table-rows', template)
        self.assertIn('detectPdfLines', source)
        self.assertIn('snapBox', source)
        self.assertIn('configuration.calibration_guides', source)
        self.assertIn('calibration-manual-guide', styles)
        self.assertIn('class="calibration-inspector" hidden open', template)
        self.assertIn('calibration-inspector-body', template)
        self.assertIn('.calibration-sidebar > * { flex: 0 0 auto; }', styles)
        self.assertIn('max-height: min(430px, 54vh)', styles)
        self.assertIn('screenPointToPage', source)
        self.assertIn('screenDeltaToPage', source)
        self.assertIn('pageBoxToScreen', source)
        self.assertIn('TAP_DISTANCE = 10', source)
        self.assertIn('TAP_DURATION = 350', source)
        self.assertIn('Idempotency-Key', source)
        self.assertIn('writeInFlight', source)
        self.assertIn('HISTORY_LIMIT = 50', source)
        self.assertIn('HISTORY_BYTE_LIMIT = 5 * 1024 * 1024', source)
        self.assertIn('savedBaselineHash = snapshotHash', source)
        self.assertIn("setOperationState('publishing')", source)
        self.assertIn("zoomMode = mobileLayout() ? 'fit-width' : 'manual'", source)
        self.assertIn('calibration-readiness', template)
        self.assertIn('calibration-navigator', template)
        self.assertIn("button.classList.remove('is-active')", source)
        self.assertIn('--cal-sheet-surface: #ffffff', styles)
        self.assertIn('background-color: var(--cal-sheet-surface) !important', styles)
        self.assertIn('.calibration-mobile-dock button.is-active', styles)
        self.assertNotIn('←', template)
        self.assertNotIn('↻', template)
        self.assertIn('preview_format', Path('core/static/miniapp/loan_origination.js').read_text(encoding='utf-8'))
        self.assertIn('beforeunload', source)

    def test_superuser_visual_product_builder_is_present(self):
        template = Path('core/templates/admin/core/originationproductdefinition/change_form.html').read_text(encoding='utf-8')
        source = Path('core/static/admin/origination_product_builder.js').read_text(encoding='utf-8')

        for control in ('origination-product-builder', 'opb-sections', 'opb-signers', 'add-section', 'add-signer'):
            self.assertIn(control, template)
        for field_type in ('textarea', 'money', 'national_id', 'choice', 'boolean'):
            self.assertIn(field_type, source)
        self.assertIn('Add field', source)
        self.assertIn('Add slot', source)
        self.assertIn('Choose or create a canonical field', source)
        self.assertIn('data-picker-create', source)
        self.assertIn('data-create-field-url', template)
        self.assertIn("origination_product_builder.js' %}?v=9", template)
        self.assertIn('data-repeatable-widths', source)
        self.assertIn('data-repeatable-min-rows', source)
        self.assertNotIn('Every active canonical input field is already attached.', source)
        self.assertIn('Use Applicant for the person applying', source)
        self.assertIn("schema.identity_contract = 'applicant_v1'", source)
        self.assertIn('data-section-prop="key"', source)
        self.assertIn('readonly aria-readonly="true"', source)
        self.assertIn('data-validation-prop="min"', source)
        self.assertIn('data-validation-prop="pattern"', source)
        self.assertIn('looksLikeNationalId', source)
        self.assertIn("['number', 'text'].includes(item.type)", source)
        self.assertIn('identityField.required = true', source)
