# Generated by Django 5.1.6 on 2026-09-29 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalRecognitionPeriodSnapshot',
            fields=[
                ('id', models.BigAutoField(db_comment='Immutable Portal performance snapshot identifier.', primary_key=True, serialize=False)),
                ('group_configuration_id', models.BigIntegerField(db_comment='Owning Portal group configuration identifier.')),
                ('period_kind', models.CharField(db_comment='Month, quarter, or year.', max_length=8)),
                ('period_key', models.CharField(db_comment='Canonical calendar period key.', max_length=12)),
                ('facts', models.JSONField(db_comment='Frozen attributed action facts; never returned directly to a client.')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_comment='When the settled period was first captured.')),
            ],
            options={
                'db_table': 'portal_recognition_period_snapshot',
                'db_table_comment': 'Immutable settled Portal performance facts; current grants still govern visibility.',
                'constraints': [models.UniqueConstraint(fields=('group_configuration_id', 'period_kind', 'period_key'), name='unique_portal_recognition_period_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='PortalRecognitionLiveStanding',
            fields=[
                ('id', models.BigAutoField(db_comment='Live Portal rank checkpoint identifier.', primary_key=True, serialize=False)),
                ('context_key', models.CharField(db_comment='Digest of viewer, grants, period and filters.', max_length=64, unique=True)),
                ('group_configuration_ids', models.JSONField(db_comment='Portal configurations represented by this checkpoint.', default=list)),
                ('ranks', models.JSONField(db_comment='Opaque participant keys and last observed competition ranks.', default=dict)),
                ('signature', models.CharField(blank=True, db_comment='Digest of last observed standing scores and ranks.', max_length=64)),
                ('movement', models.JSONField(db_comment='Movement from the previous distinct standing.', default=dict)),
                ('observed_at', models.DateTimeField(db_comment='Time the standing calculation began.')),
                ('expires_at', models.DateTimeField(db_comment='Checkpoint expiry for bounded on-demand cleanup.')),
                ('viewer', models.ForeignKey(db_comment='Viewer whose grants scoped the standing.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_recognition_live_standing',
                'db_table_comment': 'Expiring per-viewer Portal performance movement baseline, never a final award.',
                'indexes': [models.Index(fields=['expires_at'], name='portal_live_expiry_idx')],
            },
        ),
    ]
