# Generated by Django 5.1.6 on 2026-09-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portalrecognitionperiodsnapshot',
            name='unique_portal_recognition_period_snapshot',
        ),
        migrations.AddField(
            model_name='portalrecognitionperiodsnapshot',
            name='score_policy_version',
            field=models.PositiveSmallIntegerField(db_comment='Immutable scoring policy used for these facts.', default=1),
        ),
        migrations.AddConstraint(
            model_name='portalrecognitionperiodsnapshot',
            constraint=models.UniqueConstraint(fields=('group_configuration_id', 'period_kind', 'period_key', 'score_policy_version'), name='unique_portal_recognition_versioned_period'),
        ),
    ]
