# Generated by Django 5.1.6 on 2026-09-25 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0192_portal_reset_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.CharField(db_comment='Permanent app-prefixed test identifier; never reused.', max_length=32, primary_key=True, serialize=False)),
                ('app', models.CharField(db_comment='Workflow being verified, such as portal or tat_tracker.', max_length=32)),
                ('journey', models.CharField(db_comment='User journey or cross-cutting area.', max_length=100)),
                ('description', models.CharField(db_comment='Short human-readable verification objective.', max_length=255)),
                ('steps', models.TextField(db_comment='Actions a tester performs manually.')),
                ('expected', models.TextField(db_comment='Expected observable outcome and important alternative.')),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], db_comment='Manual test ordering priority.', default='normal', max_length=12)),
                ('automation_gap', models.BooleanField(db_comment='Automatable check retained temporarily because CI coverage has not been verified.', default=False)),
                ('active', models.BooleanField(db_comment='False retires the test without deleting its result history.', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Registry creation timestamp.')),
            ],
            options={
                'db_table': 'qa_tracker_test_case_root',
                'db_table_comment': 'Stable QA test registry; retained after retirement; no customer data.',
                'ordering': ['app', 'journey', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestCycle',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable QA release-cycle identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app', models.CharField(db_comment='Workflow covered by this release checklist.', max_length=32)),
                ('release', models.CharField(db_comment='Release or deployed version label.', max_length=80)),
                ('environment', models.CharField(choices=[('pilot', 'Pilot'), ('staging', 'Staging'), ('production', 'Production')], db_comment='Environment tested.', max_length=24)),
                ('build_commit', models.CharField(blank=True, db_comment='Optional deployed commit SHA, not customer data.', max_length=40)),
                ('branch', models.CharField(blank=True, db_comment='Optional branch scope; blank means all branches in the group.', max_length=120)),
                ('product', models.CharField(blank=True, db_comment='Optional product scope; blank means all products in the group.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='QA cycle creation timestamp.')),
                ('created_by', models.ForeignKey(db_comment='Staff member who opened the QA cycle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group_configuration', models.ForeignKey(db_comment='Exact configured Telegram group covered by this QA run.', on_delete=django.db.models.deletion.PROTECT, related_name='qa_test_cycles', to='core.groupsheetconfiguration')),
            ],
            options={
                'db_table': 'qa_tracker_test_cycle_root',
                'db_table_comment': 'Scoped release checklist; retained to compare QA results across releases.',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable QA execution identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_description', models.CharField(db_comment='Description snapshot at execution time.', max_length=255)),
                ('test_steps', models.TextField(db_comment='Steps snapshot at execution time.')),
                ('test_expected', models.TextField(db_comment='Expected result snapshot at execution time.')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('blocked', 'Blocked')], db_comment='Human Pass, Fail, or Blocked decision.', max_length=12)),
                ('severity', models.CharField(blank=True, choices=[('blocker', 'Blocker'), ('major', 'Major'), ('minor', 'Minor')], db_comment='Impact of a failed check; blank for non-failures.', max_length=12)),
                ('bug_reference', models.CharField(blank=True, db_comment='Optional issue tracker reference; no customer identifiers.', max_length=100)),
                ('notes', models.TextField(blank=True, db_comment='Privacy-safe observation; not a place for customer data.')),
                ('request_key', models.UUIDField(db_comment='Client-generated idempotency key for double-submission and retry.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Execution timestamp; used to choose latest result.')),
                ('cycle', models.ForeignKey(db_comment='Release and exact access scope of this execution.', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='qa_tracker.testcycle')),
                ('test_case', models.ForeignKey(db_comment='Permanent registry test identifier.', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='qa_tracker.testcase')),
                ('tester', models.ForeignKey(db_comment='Staff member who recorded the observed result.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qa_tracker_test_run_event',
                'db_table_comment': 'Append-only human QA executions; retained across releases for regression comparison.',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestEvidence',
            fields=[
                ('id', models.UUIDField(db_comment='Immutable screenshot metadata identifier.', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drive_file_id', models.CharField(db_comment='Private Google Drive object ID; never a public URL.', max_length=255)),
                ('filename', models.CharField(db_comment='Generated non-PII screenshot filename.', max_length=180)),
                ('mime_type', models.CharField(db_comment='Validated PNG or JPEG media type.', max_length=32)),
                ('size_bytes', models.PositiveIntegerField(db_comment='Validated original screenshot size.')),
                ('sha256', models.CharField(db_comment='Content digest for evidence integrity and duplicate recognition.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Screenshot upload timestamp.')),
                ('run', models.ForeignKey(db_comment='Execution evidenced by this screenshot.', on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='qa_tracker.testrun')),
            ],
            options={
                'db_table': 'qa_tracker_test_evidence_link',
                'db_table_comment': 'Private Drive screenshot references for QA runs; object retention follows approved Drive policy.',
            },
        ),
        migrations.AddConstraint(
            model_name='testcycle',
            constraint=models.UniqueConstraint(fields=('app', 'release', 'environment', 'group_configuration', 'branch', 'product'), name='qa_cycle_unique_scope_release'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['cycle', 'test_case', '-created_at'], name='qa_run_cycle_case_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='testevidence',
            constraint=models.UniqueConstraint(fields=('run', 'sha256'), name='qa_evidence_unique_run_hash'),
        ),
    ]
