# Generated by Django 5.1.6 on 2026-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcycle',
            name='app',
            field=models.CharField(choices=[('portal', 'Portal'), ('tat_tracker', 'TAT Tracker'), ('complaints', 'Complaints'), ('spin', 'SPIN'), ('origination', 'Origination')], db_comment='Workflow covered by this release checklist.', max_length=32),
        ),
    ]
