# Generated by Django 5.1.6 on 2026-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_tracker', '0003_seed_portal_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcycle',
            name='case_ids',
            field=models.JSONField(blank=True, db_comment='Frozen active test IDs included when this release checklist was created.', default=list),
        ),
    ]
