# Generated by Django 5.2.17 on 2026-10-04 09:34

import django.db.models.deletion
from django.db import migrations, models
from ._ownership import comment_forward, comment_reverse


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_alter_accesscontrolchangerequest_workflow_and_more'),
        ('origination', '0001_domain_ownership'),
    ]

    operations = [
        migrations.RunPython(comment_forward, comment_reverse),
        migrations.AddField(
            model_name='loanoriginationapplication',
            name='group_configuration',
            field=models.ForeignKey(blank=True, db_comment='Origination creation scope; historical applications remain ungrouped.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origination_applications', to='core.groupsheetconfiguration'),
        ),
    ]
