# Generated by Django 5.1.6 on 2026-09-29 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tat_recognition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TatRecognitionLiveStanding',
            fields=[
                ('id', models.BigAutoField(db_comment='Live standing checkpoint identifier.', primary_key=True, serialize=False)),
                ('group_id', models.CharField(db_comment='TAT group for reset and pilot cleanup.', max_length=100)),
                ('scope_key', models.CharField(db_comment='Production or Pilot cycle represented by this standing.', max_length=64)),
                ('context_key', models.CharField(db_comment='SHA-256 of viewer, access grants, period, view, and selected filters.', max_length=64, unique=True)),
                ('ranks', models.JSONField(db_comment='Last confirmed opaque participant keys mapped to competition ranks.', default=dict)),
                ('signature', models.CharField(blank=True, db_comment='SHA-256 of last confirmed scores and ranks; excludes names.', max_length=64)),
                ('movement', models.JSONField(db_comment='Current rank change against the previous confirmed standing.', default=dict)),
                ('observed_at', models.DateTimeField(db_comment='Time scoring began, used to reject stale concurrent results.')),
                ('expires_at', models.DateTimeField(db_comment='Checkpoint expires after the live period settles.')),
                ('viewer', models.ForeignKey(db_comment='Viewer whose current access scope defines this standing.', on_delete=django.db.models.deletion.CASCADE, related_name='tat_recognition_live_standings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tat_recognition_live_standing',
                'db_table_comment': 'Expiring per-viewer TAT recognition rank baselines; not an authoritative score or final award.',
                'indexes': [models.Index(fields=['expires_at'], name='tat_live_expiry_idx')],
            },
        ),
    ]
