# Generated by Django 5.1.6 on 2026-09-23 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0189_fulfillment_partner_orders'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersequencestate',
            name='partner',
            field=models.CharField(choices=[('HB', 'HB'), ('ECOCONSERVE', 'Eco-conserve')], db_comment='Fulfilment partner whose official order numbers this sequence governs.', default='HB', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordersequencestate',
            name='group_configuration',
            field=models.ForeignKey(db_comment='Jawabu group whose official paper numbering this sequence governs.', on_delete=django.db.models.deletion.PROTECT, related_name='requisition_order_sequences', to='core.groupsheetconfiguration'),
        ),
        migrations.AddConstraint(
            model_name='ordersequencestate',
            constraint=models.UniqueConstraint(fields=('group_configuration', 'partner'), name='unique_requisition_sequence_partner'),
        ),
    ]
