# Generated by Django 5.1.6 on 2026-10-06 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_jawabufarmermaster_requisition_batch_and_more'),
        ('requisitions', '0002_fulfillment_partner_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberClaim',
            fields=[
                ('id', models.BigAutoField(db_comment='Internal number-slot identifier.', primary_key=True, serialize=False)),
                ('number', models.PositiveBigIntegerField(db_comment='Printed numeric component; never a document identity.')),
                ('batch', models.OneToOneField(blank=True, db_comment='Current owner; null only after explicit release.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='number_claim', to='core.requisitionbatch')),
                ('sequence', models.ForeignKey(db_comment='Locked group/partner allocator owning this number.', on_delete=django.db.models.deletion.PROTECT, related_name='number_claims', to='requisitions.ordersequencestate')),
            ],
            options={
                'db_table': 'requisition_order_number_claim',
                'db_table_comment': 'Lifetime authoritative number slots; released slots may be reassigned under the sequence lock.',
                'constraints': [models.UniqueConstraint(fields=('sequence', 'number'), name='unique_order_number_claim')],
            },
        ),
        migrations.CreateModel(
            name='OrderWorkbookVersion',
            fields=[
                ('id', models.BigAutoField(db_comment='Internal retained-workbook identifier.', primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(db_comment='Monotonic workbook version within this workspace.')),
                ('filename', models.CharField(db_comment='Original generated filename.', max_length=255)),
                ('file_content', models.BinaryField(db_comment='Exact immutable generated workbook bytes.')),
                ('checksum', models.CharField(db_comment='SHA-256 binding for these bytes.', max_length=64)),
                ('farmer_ids', models.JSONField(db_comment='Immutable case UUID membership for these bytes.', default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Generation timestamp.')),
                ('actor', models.ForeignKey(db_comment='Staff user who generated this version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(db_comment='Immutable workspace identity, independent of reused display numbers.', on_delete=django.db.models.deletion.PROTECT, related_name='workbook_versions', to='core.requisitionbatch')),
            ],
            options={
                'db_table': 'requisition_order_workbook_version',
                'db_table_comment': 'Authoritative immutable workbook versions; lifetime financial evidence, not a Drive cache.',
                'constraints': [models.UniqueConstraint(fields=('batch', 'version'), name='unique_order_workbook_version')],
            },
        ),
        migrations.CreateModel(
            name='OrderWorkspaceEvent',
            fields=[
                ('id', models.BigAutoField(db_comment='Internal append-only workspace-event identifier.', primary_key=True, serialize=False)),
                ('action', models.CharField(db_comment='Generated, appended or cancelled.', max_length=24)),
                ('version', models.PositiveIntegerField(db_comment='Current workbook version at the change.')),
                ('request_id', models.CharField(db_comment='Idempotency key for this action.', max_length=128)),
                ('metadata', models.JSONField(db_comment='Change evidence, including released display numbers and membership.', default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Committed change timestamp.')),
                ('actor', models.ForeignKey(db_comment='Accountable staff user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(db_comment='Workspace changed by this event.', on_delete=django.db.models.deletion.PROTECT, related_name='workspace_events', to='core.requisitionbatch')),
            ],
            options={
                'db_table': 'requisition_order_workspace_event',
                'db_table_comment': 'Append-only authoritative order workspace audit; retained with financial evidence.',
                'constraints': [models.UniqueConstraint(condition=models.Q(('request_id', ''), _negated=True), fields=('request_id',), name='unique_order_workspace_request')],
            },
        ),
    ]
