from django.urls import path
from core.api.legacy_routes import legacy_get_redirect
from .auth import origination_auth_required
from .views import (
    origination_signer_session,
    origination_signer_packet_preview,
    origination_signer_consent,
    origination_signer_otp,
    origination_signer_verify,
    origination_africastalking_delivery_report,
    portal_origination_application_detail,
    portal_origination_confirm_signing,
    portal_origination_final_review,
    portal_origination_quote_preview,
    portal_origination_applications,
    portal_origination_evidence_download,
    portal_origination_evidence_remove,
    portal_origination_evidence_upload,
    portal_origination_products,
    portal_origination_prepare_review_packet,
    portal_origination_prepare_signing,
    portal_origination_recall,
    portal_origination_restart,
    portal_origination_review_packet_preview,
    portal_origination_reviewer_notice_seen,
    portal_origination_signer_session,
    portal_origination_reset_signer_session,
    portal_origination_staff_signature,
    portal_origination_production_stamp,
    portal_origination_archive_signed,
    portal_origination_signed_packet,
    portal_origination_current_signing_packet,
    portal_origination_test_signing_action,
    portal_origination_test_signing_preview,
    portal_origination_signing_requirements,
    portal_origination_preview,
    portal_origination_review,
    portal_origination_correction_takeover,
    portal_origination_submit,
    portal_origination_document_selection,
    portal_origination_document_fields,
    portal_origination_document_preview,
    portal_origination_packet_preview,
)

urlpatterns = [
    path('origination/', legacy_get_redirect('loan_origination_app'), name='legacy_api_loan_origination_app'),
    path('s/', legacy_get_redirect('loan_origination_signing_short_app'), name='legacy_api_loan_origination_signing_short_app'),
    path('origination/sign/', legacy_get_redirect('loan_origination_signing_app'), name='legacy_api_loan_origination_signing_app'),
    path('origination/sign/api/session/', origination_signer_session, name='loan_origination_signer_session'),
    path('origination/sign/api/packet/', origination_signer_packet_preview, name='loan_origination_signer_packet'),
    path('origination/sign/api/consent/', origination_signer_consent, name='loan_origination_signer_consent'),
    path('origination/sign/api/otp/', origination_signer_otp, name='loan_origination_signer_otp'),
    path('origination/sign/api/verify/', origination_signer_verify, name='loan_origination_signer_verify'),
    path('origination/webhooks/africastalking/delivery/', origination_africastalking_delivery_report, name='loan_origination_africastalking_delivery'),
    path('origination/api/products/', origination_auth_required(portal_origination_products), name='loan_origination_products'),
    path('origination/api/applications/', origination_auth_required(portal_origination_applications), name='loan_origination_applications'),
    path('origination/api/applications/<str:application_id>/', origination_auth_required(portal_origination_application_detail), name='loan_origination_application_detail'),
    path('origination/api/applications/<str:application_id>/quote-preview/', origination_auth_required(portal_origination_quote_preview), name='loan_origination_quote_preview'),
    path('origination/api/applications/<str:application_id>/submit/', origination_auth_required(portal_origination_submit), name='loan_origination_submit'),
    path('origination/api/applications/<str:application_id>/confirm-signing/', origination_auth_required(portal_origination_confirm_signing), name='loan_origination_confirm_signing'),
    path('origination/api/applications/<str:application_id>/recall/', origination_auth_required(portal_origination_recall), name='loan_origination_recall'),
    path('origination/api/applications/<str:application_id>/restart/', origination_auth_required(portal_origination_restart), name='loan_origination_restart'),
    path('origination/api/applications/<str:application_id>/preview/', origination_auth_required(portal_origination_preview), name='loan_origination_preview'),
    path('origination/api/applications/<str:application_id>/documents/selection/', origination_auth_required(portal_origination_document_selection), name='loan_origination_document_selection'),
    path('origination/api/applications/<str:application_id>/documents/<slug:document_key>/fields/', origination_auth_required(portal_origination_document_fields), name='loan_origination_document_fields'),
    path('origination/api/applications/<str:application_id>/documents/<slug:document_key>/preview/', origination_auth_required(portal_origination_document_preview), name='loan_origination_document_preview'),
    path('origination/api/applications/<str:application_id>/packet/preview/', origination_auth_required(portal_origination_packet_preview), name='loan_origination_packet_preview'),
    path('origination/api/applications/<str:application_id>/review/', origination_auth_required(portal_origination_review), name='loan_origination_review'),
    path('origination/api/applications/<str:application_id>/final-review/', origination_auth_required(portal_origination_final_review), name='loan_origination_final_review'),
    path('origination/api/applications/<str:application_id>/correction/takeover/', origination_auth_required(portal_origination_correction_takeover), name='loan_origination_correction_takeover'),
    path('origination/api/applications/<str:application_id>/prepare-review-packet/', origination_auth_required(portal_origination_prepare_review_packet), name='loan_origination_prepare_review_packet'),
    path('origination/api/applications/<str:application_id>/review-packet/preview/', origination_auth_required(portal_origination_review_packet_preview), name='loan_origination_review_packet_preview'),
    path('origination/api/applications/<str:application_id>/prepare-signing/', origination_auth_required(portal_origination_prepare_signing), name='loan_origination_prepare_signing'),
    path('origination/api/reviewer-notices/<str:notice_id>/seen/', origination_auth_required(portal_origination_reviewer_notice_seen), name='loan_origination_reviewer_notice_seen'),
    path('origination/api/applications/<str:application_id>/signer-sessions/', origination_auth_required(portal_origination_signer_session), name='loan_origination_signer_sessions'),
    path('origination/api/applications/<str:application_id>/signer-sessions/reset/', origination_auth_required(portal_origination_reset_signer_session), name='loan_origination_reset_signer_session'),
    path('origination/api/applications/<str:application_id>/staff-signature/', origination_auth_required(portal_origination_staff_signature), name='loan_origination_staff_signature'),
    path('origination/api/applications/<str:application_id>/production-stamp/', origination_auth_required(portal_origination_production_stamp), name='loan_origination_production_stamp'),
    path('origination/api/applications/<str:application_id>/archive-signed/', origination_auth_required(portal_origination_archive_signed), name='loan_origination_archive_signed'),
    path('origination/api/applications/<str:application_id>/signed-packet/', origination_auth_required(portal_origination_signed_packet), name='loan_origination_signed_packet'),
    path('origination/api/applications/<str:application_id>/current-signing-packet/', origination_auth_required(portal_origination_current_signing_packet), name='loan_origination_current_signing_packet'),
    path('origination/api/applications/<str:application_id>/test-signing/action/', origination_auth_required(portal_origination_test_signing_action), name='loan_origination_test_signing_action'),
    path('origination/api/applications/<str:application_id>/test-signing/preview/', origination_auth_required(portal_origination_test_signing_preview), name='loan_origination_test_signing_preview'),
    path('origination/api/applications/<str:application_id>/signing-requirements/', origination_auth_required(portal_origination_signing_requirements), name='loan_origination_signing_requirements'),
    path('origination/api/applications/<str:application_id>/requirements/<slug:requirement_key>/evidence/', origination_auth_required(portal_origination_evidence_upload), name='loan_origination_evidence_upload'),
    path('origination/api/evidence/<str:evidence_id>/remove/', origination_auth_required(portal_origination_evidence_remove), name='loan_origination_evidence_remove'),
    path('origination/api/evidence/<str:evidence_id>/download/', origination_auth_required(portal_origination_evidence_download), name='loan_origination_evidence_download'),
]
