flowchart LR
  access["Access"]
  audit["Audit"]
  catalog["Catalog"]
  complaints["Complaints"]
  credit_assessment["Credit Assessment"]
  homebiogas_operations["Homebiogas Operations"]
  integration["Integration"]
  jawabu["Jawabu"]
  order_approval["Order Approval"]
  origination["Origination"]
  payments["Payments"]
  platform["Platform"]
  portal_recognition["Portal Recognition"]
  report_delivery["Report Delivery"]
  requisitions["Requisitions"]
  spin["Spin"]
  tat["Tat"]
  tat_recognition["Tat Recognition"]
  access --> catalog
  access --> platform
  complaints --> catalog
  complaints --> jawabu
  complaints --> platform
  credit_assessment --> tat
  homebiogas_operations --> jawabu
  homebiogas_operations --> platform
  integration --> platform
  jawabu --> catalog
  jawabu --> order_approval
  jawabu --> platform
  order_approval --> catalog
  order_approval --> jawabu
  origination --> catalog
  origination --> jawabu
  origination --> platform
  payments --> jawabu
  payments --> platform
  platform --> complaints
  platform --> jawabu
  report_delivery --> platform
  requisitions --> platform
  spin --> catalog
  tat --> catalog
  tat --> platform
