erDiagram
  requisition_order_sequence_event {
    string id
  }
  requisition_order_sequence_state {
    string id
  }
  requisition_order_sequence_state ||--o{ requisition_order_sequence_event : contains
