erDiagram
  core_spinbatchreviewitem {
    string id
  }
  core_spincreditrequest {
    string id
  }
  core_spinrequestsequence {
    string id
  }
  core_spincreditrequest ||--o{ core_spinbatchreviewitem : contains
